### ISSUE TITLE
ask_save_file doesn't return anything in OS X 10.5

### ISSUE THREAD

**Issue by tiegz** [shoes/shoes-deprecated#1]
I tried this on two different machines running Leopard. Note that "ask_save_folder" works, but "ask_save_file" does not work. I checked the Cocoa docs and apparently one of the functions used is deprecated (albeit in 10.6).

```
    Shoes.app :title => "ask_save_file test" do
      file = ask_save_file
      para "The file was #{file} and the file class is #{file.class}"
    end
```

**Comment by greatseth** [comment]
What version of Shoes? It works for me with Shoes r1250 and OS X 10.5.8.

**Comment by tiegz** [comment]
Aha! There lies the problem. It looks like both machines had Raisins. I can't get the current revision to build, but I see in the logs that the problem was fixed back in January. Thx!
