### ISSUE TITLE
Update Japanese translation for the Manual

### ISSUE THREAD

**Issue by steveklabnik** [shoes/shoes-deprecated#100]
This is just something tiny, [this commit](https://github.com/shoes/shoes/commit/2ddf4aaf823cb126a14c5a3b6cb075be73534a55) updates the README to refer to the correct thing to do for Linux.

[And this one](https://github.com/shoes/shoes/commit/71a5f61e82dab856c6d49afd06ed58051df748a5).

Ash, would you mind doing the translation to JA?

**Comment by ashbb** [comment]
Okay, I'll translate them and send you the updated manual-ja.txt.
