### ISSUE TITLE
shoes -v is horribly wrong

### ISSUE THREAD

**Issue by steveklabnik** [shoes/shoes-deprecated#101]
$ shoes -v
shoes policeman (0.r1567) [x86_64-linux Ruby1.9.1]

heh. This should also be backported to Shoes 3.0.

Thanks @manveru.

**Comment by pjfitzgibbons** [comment]
Do you mean the version (0.r1567) ?
Should we be reporting something like 3.2.r1234 "Walkabout" [platform info] ?

**Comment by steveklabnik** [comment]
Yeah, that's exactly what I mean. Your version string would be great. The 3.2 is the most important thing, rather than the old r number. It was taken directly from SVN back in the day...

**Comment by heartpunk** [comment]
Looks like this should be closed, no?

**Comment by PragTob** [comment]
Yups, good catch. Thanks @tehgeekmeister
