### ISSUE TITLE
"UTF_7 is not a clas" Error running Shoes in Ubuntu 10.10 64bits

### ISSUE THREAD

**Issue by jesusangelm** [shoes/shoes-deprecated#105]
running shoes in ubuntu 10.10 64bits i see this error:

angel@JAM-Laptop:~/programacion/repos_git/shoes/dist$ ./shoes
UTF_7 is not a class

my #{SHOES_HOME} is ~/programacion/repos_git/shoes/

**Comment by steveklabnik** [comment]
Did you compile this shoes yourself? Or are you using the package?

**Comment by jesusangelm** [comment]
yes, i compile shoes on Linux. following the steps in the wiki: Building-Shoes-on-Linux...
sorry for my bad english

**Comment by steveklabnik** [comment]
> sorry for my bad english

No worries, your English is fine. :)

Did you build Shoes with 1.9.2 or 1.9.1?

**Comment by jesusangelm** [comment]
Ruby 1.9.2  using RVM

**Comment by steveklabnik** [comment]
Okay. Could you try with 1.9.1 please? Technically, 1.9.2 support is experimental.

**Comment by wielkiborsuk** [comment]
Hey, I just stumbled on the same problem. I already tried ruby 1.9.1
Maybe it has something to do with my compilation problem? (I needed to link or copy libraries libjpeg.so and libsqlite3.so from lib32 to lib - alternatively edit the make/linux/tasks.rb)

Eagerly waiting for help.

edit: OK, i tried package install, seems to work, maybe it's the right solution :)

**Comment by steveklabnik** [comment]
> edit: OK, i tried package install, seems to work, maybe it's the right solution :)

Well, it's right in the sense that it works for you, but it's not in that it _should_ compile and work for you. I build my copies of Shoes on Arch Linux, what distro are you on?

**Comment by gderosa** [comment]
Hello! Maybe I've fixed the problem with a tiny patch. 

https://github.com/gderosa/shoes/commit/b6681d0be26e1a3d3454ff4754b28f95b97af9d5

Just sent a pull request. Let me know what you think.

**Comment by jesusangelm** [comment]
thanx! gderosa this work.
