### ISSUE TITLE
Old version of built in rubygems

### ISSUE THREAD

**Issue by simonszu** [shoes/shoes-deprecated#107]
It seems that shoes has an old version of rubygems installed, because whenever i try to install a gem which requires the rack-gem, i get an error saying that rack needs rubygems 1.8.1 or higher. 

So rack and every depending gems are not installable.

**Comment by steveklabnik** [comment]
Well, I'm not sure why Rack would work anyway...

The version of Rubygems that's distributed with Shoes is 1.3.6 at the  moment. It'll be upgraded to 1.3.7 when we move Shoes to Ruby 1.9.2, but It's not likely we'll distribute anything higher than that until we move to 1.9.3. Which should be easier than the move to 1.9.2.

Updating the built-in Rubygems isn't really something that's going to be supported for a long time, if ever.
