### ISSUE TITLE
Raisins Packager doesn't work on Windows

### ISSUE THREAD

**Issue by hyperlogic** [shoes/shoes-deprecated#11]
Trying to package up a directory into a windows exe results in the following error in the console.

Error in C:/Program Files (x86)/Common Files/Shoes/0.r1134/ruby/lib/resolv-replace.rb line 10

Hostname not known: hacketyhack.net

The package app just hangs and never completes....

**Comment by hyperlogic** [comment]
It also doesn't work on the Policeman either, possibly due to the binject extension not being built.

**Comment by grossbart** [comment]
I think this is because hacketyhack.net is no longer available. The source code should be rewritten and recompiled to point to the GitHub files.

**Comment by atomicules** [comment]
This can be closed out. This was actually fixed back in August. See these two commits:
a10af621fcf2f1dc86386460a9817b2a932a6084
689480d383b4de6a7a758681d0a70c239471d89c

You can back-port this to Raisins by replacing the pack.rb file with the latest.

**Comment by codeodor** [comment]
Perhaps you guys could package a new build or whatnot? I downloaded Shoes for OSX relatively recently (sometime in December 2009) and it still points to hacketyhack.net. Updating my local source thanks to your commits. 

Appreciate it!

**Comment by atomicules** [comment]
That is a good idea. I.e. Repackage Raisins with new pack.rb. That or we start putting Policeman builds up somewhere. Or just release a patch for Raisins.  That might be best.

**Comment by ashbb** [comment]
Hi all,

Please try Policeman ([Shoes-0.r1414.exe](http://www.rin-shun.com/shoes/index.html)) Packager.

**Comment by atomicules** [comment]
Closing this as although it is/was a nice idea to back-port fixes to Raisins and make a new Raisins release we have not had enough resource available. Once Shoes 3 is officially released this issue is redundant anyway and there are already builds available for Shoes 3. Plus, users can - if they want - fix Raisins by replacing the pack.rb file.

**Comment by steveklabnik** [comment]
Closing, Raisins isn't really supported.
