### ISSUE TITLE
:resizable=>false doesn't work right

### ISSUE THREAD

**Issue by duckinator** [shoes/shoes-deprecated#110]
There's a problem in the following example, from the manual (Shoes -> App):

``` ruby

Shoes.app(:title => "White Circle",
  :width => 200, :height => 200, :resizable => false) {
    background black
    fill white
    oval :top => 20, :left => 20, :radius => 160
}

```

It can not be made LARGER, but it can be made SMALLER.

In case it's system-specific:
$ uname -a
Linux bestia 2.6.39-ARCH #1 SMP PREEMPT Mon Jun 6 22:37:55 CEST 2011 x86_64 AMD Phenom(tm) II X4 925 Processor AuthenticAMD GNU/Linux
$ ruby -v 
ruby 1.9.2p180 (2011-02-18 revision 30909) [x86_64-linux]

ArchLinux, git HEAD, used shoes-git.

Let me know if you need any other info.

EDIT: Typos, typos EVERYWHERE!

**Comment by ashbb** [comment]
Umm,... strange. It can be made neither LARGER nor SMALLER on my Windows 7 with Shoes 3 (0.r1514). This issue may happen on Linux only...

ps. Two trivial typos. `full` -> `fill`, `;radius` -> `:radius`.

**Comment by steveklabnik** [comment]
I will double check on OSX tonight.

**Comment by duckinator** [comment]
Typos are my fault, will fix them now. Sorry. Was up for over 20 hours at the time :)

**Comment by phinze** [comment]
Seems to work AOK on OSX Lion.

**Comment by steveklabnik** [comment]
Works fine on snow leopard.

@duckinator, I'm going to close this. If you can reproduce on Arch HEAD, please re-open.

**Comment by duckinator** [comment]
I can't reopen this, but I can confirm it's still there on Arch HEAD.

**Comment by steveklabnik** [comment]
Damn.

**Comment by steveklabnik** [comment]
@duckinator, does this issue still exist?

**Comment by duckinator** [comment]
@steveklabnik I'm rather sick so didn't exactly bother checking email/github/etc until like 5 seconds ago. Just wrote a note to test this tomorrow.

**Comment by steveklabnik** [comment]
No worries dude. take your time, I'm just curious.

**Comment by duckinator** [comment]
@steveklabnik Sorry for taking so long, but it's still there on Arch when using shoes HEAD.

**Comment by steveklabnik** [comment]
Great! Thanks. hope you're feeling well.

Well, it's not great that it still exists... heh.

**Comment by ccoupe** [comment]
I can confirm on Ubuntu 11.04 that you can make the window smaller.
