### ISSUE TITLE
Linux/gem

### ISSUE THREAD

**Issue by lemonadestand** [shoes/shoes-deprecated#112]
I have Linux (Ubuntu, to be precise) and I can't get shoes 2 or 3. Also, the gem is not made yet, can you help me?

**Comment by steveklabnik** [comment]
Can you elaborate on 'can't get?' What did you try to do? The official way to get Shoes on Linux is to build your own, here: https://github.com/shoes/shoes/wiki/Building-Shoes-on-Linux

**Comment by lemonadestand** [comment]
can't get means when I do the build your own code everything is installed but the app. The shoes 2 download is no longer up I think? I'm new to ruby, so I don't know much about it.

**Comment by ccoupe** [comment]
Ah, there is no Shoes icon or menu item installed on Ubuntu. Shoes is not installed in the System. 

From the terminal, cd down into the directory where you build shoes. For me, it's ~/ccoupe/Projects/shoes
From there, just './dist/shoes' to run it. 

With patience, one can create an icon and menu item in Gnome (not sure about Unity) to point to your Shoes.

**Comment by steveklabnik** [comment]
Yeah, I'm closing this, but not because I want to ignore you, it's just not really a bug. Please let us know if Cecil's suggestion fixes things.

If you'd like Shoes 2, you can find it here: http://shoesrb.com/downloads You'll face the same issue.

**Comment by lemonadestand** [comment]
thanks for the help. Like I said, I just started messing with ruby, so I'm a little slow.

**Comment by steveklabnik** [comment]
No worries! We are absolutely here to help. Please let me know if I can do anything else to help you at all. And you did get it running, yes?
