### ISSUE TITLE
Create a GitHub -> ML bridge

### ISSUE THREAD

**Issue by steveklabnik** [shoes/shoes-deprecated#115]
I'm going to write a little script that sends updates from GitHub to the ML.

**Comment by steveklabnik** [comment]
A very initial version of this is up: [here](http://librelist.com/browser//shoes/2011/7/13/the-new-github-ml-bridge/)

**Comment by ccoupe** [comment]
Can we close this ticket?

**Comment by PragTob** [comment]
I guess so, people that are interested in dev can watch on github and can configure their emails here and most people on the current ML would be scared away by that I believe. Plus we got notifications in IRC now.
