### ISSUE TITLE
Update manual about visit

### ISSUE THREAD

**Issue by steveklabnik** [shoes/shoes-deprecated#116]
The manual says visit won't open Google, but it does.

**Comment by ashbb** [comment]
Umm,... I think the following (the manual says) is correct.

> Absolute URLs (such as http://google.com) are okay, but google.com (without `http://`) won't work.

**Comment by steveklabnik** [comment]
I Just tried it. It opens Google in your browser.

**Comment by ashbb** [comment]
This opens Google in your browser.

```
Shoes.app{visit 'http://google.com'}
```

But this doesn't.

```
Shoes.app{visit 'google.com'}
```

**Comment by steveklabnik** [comment]
Yes, exactly.

**Comment by steveklabnik** [comment]
Basically, I mis-read the manual. I thought it said that google would _never_ work.

Whoops!
