### ISSUE TITLE
Shoes 3.0 not working on OS X 10.7

### ISSUE THREAD

**Issue by ticup** [shoes/shoes-deprecated#119]
Just letting you know that Shoes 3.0 crashes on startup on OSX 10.7.
Shoes 2.0 on the other hand doesn't.

**Comment by steveklabnik** [comment]
Yep! Thanks!

This is the same bug as this one: https://github.com/hacketyhack/hacketyhack/issues/109

I don't have a copy of Lion yet. As soon as I figure out how I'm gonna handle having three OSXes on one box, I'll fix this.

**Comment by wasnotrice** [comment]
As a temporary fix, you can replace libiconv.2.dylib (Shoes.app/Contents/MacOS/libiconv.2.dylib) with [this patched libiconv.dylib from the GnuCash project](https://bugzilla.gnome.org/attachment.cgi?id=192432). I don't know what the patch consists of, but it works. Cross-posted from https://github.com/hacketyhack/hacketyhack/issues/109 (same fix).

**Comment by schappim** [comment]
The fix doesn't seem to work for me: 

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/libiconv.2.dylib
  Referenced from: /Applications/Shoes.app/Contents/MacOS/libpangocairo-1.0.0.dylib
  Reason: Incompatible library version: libpangocairo-1.0.0.dylib requires version 8.0.0 or later, but libiconv.2.dylib provides version 7.0.0

Similar results can be found: https://github.com/hacketyhack/hacketyhack/issues/109

**Comment by wasnotrice** [comment]
I wonder what's different between our systems. I installed my dependencies via Homebrew as an experiment. Looks like I have pango 1.28.4 and cairo 1.10.2

**Comment by steveklabnik** [comment]
We have some progress-ish on this, thanks to @wasnotrice. :)

**Comment by steveklabnik** [comment]
I just merged the homebrew code into develop, so this should be fixed. I'm gonna shoot for a release soon, but until then, you can build a Shoes. :)
