### ISSUE TITLE
Shoes error when installing gems

### ISSUE THREAD

**Issue by cyberarm** [shoes/shoes-deprecated#124]
Shoes error when installing gems via `Shoes.setup`

![Shoes console](http://cyber.kodingen.com/cyber/files/shoes-gem-instation-error.png)

**Comment by steveklabnik** [comment]
Which gem are you trying to install?

**Comment by cyberarm** [comment]
https://github.com/osgcc/osgcc4-feuq/blob/master/client/client.rb (manually installed gems)
every gem I try to install fails.

**Comment by steveklabnik** [comment]
Hm, okay.
