### ISSUE TITLE
Shoes on 32-bit Mac OS X 10.6

### ISSUE THREAD

**Issue by ghost** [shoes/shoes-deprecated#126]
So I've building shoes on my Mac, and here is how far I got:
- I installed the deps
- I did `rake install`
- I got a gem in `pkg/`

What do I do next to make a `.app`. I tried `grep`ing through the code a bit, but I'm still a bit confused as to what should happen next.

~~EDIT~~

Now the build fails, there is a line in app.c which is apparently causing problems.

**Comment by ghost** [comment]
Wait, sorry; I figured it out it's `rake build`.

**Comment by ghost** [comment]
I got this:

```
gcc -I. -c -oshoes/app.o -Wall -I/usr/include -I/usr/local/Cellar/pixman/0.22.0/include/pixman-1 -I/usr/local/Cellar/freetype/2.3.12/include/freetype2 -I/usr/local/Cellar/freetype/2.3.12/include -I/usr/X11/include/cairo -I/usr/X11/include -I/usr/X11/include/libpng12 -D_REENTRANT -I/usr/local/Cellar/pango/1.28.4/include/pango-1.0 -I/usr/local/Cellar/glib/2.28.8/include/glib-2.0 -I/usr/local/Cellar/glib/2.28.8/lib/glib-2.0/include -I/usr/local/Cellar/gettext/0.18.1.1/include -I/usr/local/Cellar/glib/2.28.8/include  -I/Users/humza/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/i386-darwin8.11.1 -I/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1 -I/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/i386-darwin8.11.1 -O  -DRUBY_1_9 -DSHOES_QUARTZ -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -fpascal-strings  -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wshorten-64-to-32 -Wno-long-long  -fno-common -pipe -x objective-c -fobjc-exceptions -isysroot /Developer/SDKs/MacOSX10.6.sdk -arch x86_64 shoes/app.c
In file included from /Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby.h:32,
                 from ./shoes/app.h:14,
                 from shoes/app.c:6:
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:108: error: size of array ‘ruby_check_sizeof_long’ is negative
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:112: error: size of array ‘ruby_check_sizeof_voidp’ is negative
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:1048: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:1048: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:1049: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:1049: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:1055: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:1056: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:1057: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:1152: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:1153: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:1154: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:1154: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:1155: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:1155: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:1156: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:1156: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:1157: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:1158: warning: function declaration isn’t a prototype
In file included from /Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:1326,
                 from /Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby.h:32,
                 from ./shoes/app.h:14,
                 from shoes/app.c:6:
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/missing.h:169: warning: redundant redeclaration of ‘ffs’
In file included from /Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/intern.h:29,
                from /Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:1327,
                from /Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby.h:32,
                from ./shoes/app.h:14,
                from shoes/app.c:6:
```

 /Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/st.h:69: error: size of array ‘st_check_for_sizeof_st_index_t’ is negative
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/st.h:73: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/st.h:74: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/st.h:109: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/st.h:110: warning: function declaration isn’t a prototype
In file included from /Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:1327,
                 from /Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby.h:32,
                 from ./shoes/app.h:14,
                 from shoes/app.c:6:
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/intern.h:84: warning: redundant redeclaration of ‘rb_uint2big’
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:552: warning: previous declaration of ‘rb_uint2big’ was here
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/intern.h:85: warning: redundant redeclaration of ‘rb_int2big’
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:553: warning: previous declaration of ‘rb_int2big’ was here
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/intern.h:86: warning: redundant redeclaration of ‘rb_uint2inum’
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:229: warning: previous declaration of ‘rb_uint2inum’ was here
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/intern.h:87: warning: redundant redeclaration of ‘rb_int2inum’
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:226: warning: previous declaration of ‘rb_int2inum’ was here
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/intern.h:99: warning: redundant redeclaration of ‘rb_ll2inum’
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:234: warning: previous declaration of ‘rb_ll2inum’ was here
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/intern.h:100: warning: redundant redeclaration of ‘rb_ull2inum’
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:236: warning: previous declaration of ‘rb_ull2inum’ was here
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/intern.h:169: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/intern.h:172: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/intern.h:173: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/intern.h:174: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/intern.h:180: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/intern.h:307: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/intern.h:338: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/intern.h:394: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/intern.h:395: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/intern.h:802: warning: function declaration isn’t a prototype
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/intern.h:804: warning: redundant redeclaration of ‘rb_iv_set’
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:1116: warning: previous declaration of ‘rb_iv_set’ was here
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/intern.h:805: warning: redundant redeclaration of ‘rb_iv_get’
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:1115: warning: previous declaration of ‘rb_iv_get’ was here
In file included from /Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby.h:32,
                 from ./shoes/app.h:14,
                 from shoes/app.c:6:
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:1408: warning: redundant redeclaration of ‘st_strcasecmp’
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/st.h:118: warning: previous declaration of ‘st_strcasecmp’ was here
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/ruby.h:1409: warning: redundant redeclaration of ‘st_strncasecmp’
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/include/ruby-1.9.1/ruby/st.h:119: warning: previous declaration of ‘st_strncasecmp’ was here
In file included from ./shoes/canvas.h:16,
                 from ./shoes/app.h:40,
                 from shoes/app.c:6:
./shoes/config.h:97:26: error: cairo-quartz.h: No such file or directory
In file included from shoes/app.c:6:
./shoes/app.h:90: warning: function declaration isn’t a prototype
In file included from shoes/app.c:8:
./shoes/ruby.h:44: warning: function declaration isn’t a prototype
In file included from shoes/app.c:11:
./shoes/native.h:24: warning: function declaration isn’t a prototype
./shoes/native.h:26: warning: function declaration isn’t a prototype
./shoes/native.h:28: warning: function declaration isn’t a prototype
./shoes/native.h:44: warning: function declaration isn’t a prototype
shoes/app.c:106: warning: no previous prototype for ‘shoes_app_resize’
shoes/app.c: In function ‘shoes_app_window’:
shoes/app.c:120: warning: initialization discards qualifiers from pointer target type
shoes/app.c:143: warning: implicit conversion shortens 64-bit value into a 32-bit value
shoes/app.c:145: warning: implicit conversion shortens 64-bit value into a 32-bit value
shoes/app.c: In function ‘shoes_app_get_width’:
shoes/app.c:171: warning: comparison is always true due to limited range of data type
shoes/app.c:171: warning: comparison is always true due to limited range of data type
shoes/app.c: In function ‘shoes_app_get_height’:
shoes/app.c:179: warning: comparison is always true due to limited range of data type
shoes/app.c:179: warning: comparison is always true due to limited range of data type
shoes/app.c: At top level:
shoes/app.c:217: warning: no previous prototype for ‘shoes_app_title’
shoes/app.c:275: warning: function declaration isn’t a prototype
shoes/app.c: In function ‘shoes_app_run’:
shoes/app.c:337: warning: implicit conversion shortens 64-bit value into a 32-bit value
rake aborted!
Command failed with status (1): [gcc -I. -c -oshoes/app.o -Wall -I/usr/incl...]

Tasks: TOP => build => build_os => dist/shoes => dist/libshoes.dylib => shoes/app.o
(See full trace by running task with --trace)

Looks like I'll have to fix up something in `app.c` then... also, are the warnings OK? Can I ignore them?

**Comment by ghost** [comment]
Gah, sorry I don't know much C. Apparently it's something with this line:

```
     return rb_funcall2(exec->block, s_call, RARRAY_LEN(exec->args), vargs);
```

**Comment by ghost** [comment]
Wait sorry, here is `--trace`:

/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/file_utils.rb:53:in `block in create_shell_runner'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/file_utils.rb:45:in`call'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/file_utils.rb:45:in `sh'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/file_utils_ext.rb:36:in`sh'
/Volumes/HD-II/humza/shoes/make/make.rb:28:in `cc'
/Volumes/HD-II/humza/shoes/Rakefile:127:in`block in <top (required)>'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:203:in `call'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:203:in`block in execute'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:200:in `each'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:200:in`execute'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/monitor.rb:201:in`mon_synchronize'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:176:in`block in invoke_prerequisites'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:174:in `each'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:174:in`invoke_prerequisites'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/monitor.rb:201:in`mon_synchronize'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:176:in`block in invoke_prerequisites'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:174:in `each'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:174:in`invoke_prerequisites'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/monitor.rb:201:in`mon_synchronize'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:176:in`block in invoke_prerequisites'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:174:in `each'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:174:in`invoke_prerequisites'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/monitor.rb:201:in`mon_synchronize'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:176:in`block in invoke_prerequisites'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:174:in `each'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:174:in`invoke_prerequisites'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/Users/humza/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/monitor.rb:201:in`mon_synchronize'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:144:in`invoke'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:112:in `invoke_task'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:90:in`block (2 levels) in top_level'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:90:in `each'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:90:in`block in top_level'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:84:in`top_level'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:62:in `block in run'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:129:in`standard_exception_handling'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/bin/rake:32:in`<top (required)>'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/bin/rake:19:in `load'
/Users/humza/.rvm/gems/ruby-1.9.2-p180/bin/rake:19:in`<main>'
Tasks: TOP => build => build_os => dist/shoes => dist/libshoes.dylib => shoes/app.o

**Comment by steveklabnik** [comment]
Since you're in the other thread too, I'm gonna close this one. ;)
