### ISSUE TITLE
Installation failing on Fedora 13

### ISSUE THREAD

**Issue by b1ackb0x** [shoes/shoes-deprecated#129]
I am just starting with ruby and shoes and was trying to install Shoes 3 (Policeman) on Fedora 13 using rvm and ruby 1.9.2 but rake is failing with the following error:

*\* Execute dist/libshoes.so
gcc -o dist/libshoes.so shoes/canvas.o shoes/ruby.o shoes/image.o shoes/world.o shoes/effects.o shoes/app.o shoes/internal.o shoes/native/gtk.o shoes/http/curl.o  -pthread -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lgdk_pixbuf-2.0 -lpangocairo-1.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0 -lcurl -fPIC -shared -lruby -lcairo -lpangocairo-1.0 -lungif -ljpeg -lrt -L/usr/local/rvm/rubies/ruby-1.9.2-p290/lib -lcairo -pthread -lpango-1.0 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0
/usr/bin/ld: cannot open output file dist/libshoes.so: No such file or directory
collect2: ld returned 1 exit status
rake aborted!
Command failed with status (1): [gcc -o dist/libshoes.so shoes/canvas.o sho...]

Here is the series of steps that I followed to install shoes:
1) yum install --all dependencies--
2) rvm gemset create 'shoes'
3) rvm use 1.9.2@shoes
4) gem install rake (so that rake installed in shoes gemset)
5) gem install bundler
6) cd ~/.shoes
7) bundle install
8) rake

I have attached the complete rake output with --trace and -v <a href="https://gist.github.com/1166126">here</a>.

Here is my gem env. that I am using. rvm is installed in /usr/local/rvm:

RubyGems Environment:
- RUBYGEMS VERSION: 1.8.6
- RUBY VERSION: 1.9.2 (2011-07-09 patchlevel 290) [i686-linux]
- INSTALLATION DIRECTORY: /usr/local/rvm/gems/ruby-1.9.2-p290@shoes
- RUBY EXECUTABLE: /usr/local/rvm/rubies/ruby-1.9.2-p290/bin/ruby
- EXECUTABLE DIRECTORY: /usr/local/rvm/gems/ruby-1.9.2-p290@shoes/bin
- RUBYGEMS PLATFORMS:
  - ruby
  - x86-linux
- GEM PATHS:
  - /usr/local/rvm/gems/ruby-1.9.2-p290@shoes
  - /usr/local/rvm/gems/ruby-1.9.2-p290@global
- GEM CONFIGURATION:
  - :update_sources => true
  - :verbose => true
  - :benchmark => false
  - :backtrace => false
  - :bulk_threshold => 1000
- REMOTE SOURCES:
  - http://rubygems.org/

and the list of gems:

**\* LOCAL GEMS ***

builder (3.0.0)
bundler (1.0.18)
cucumber (1.0.2)
diff-lcs (1.1.2)
gherkin (2.4.11)
json (1.5.3)
mechanize (1.0.0)
nokogiri (1.4.4)
rake (0.9.2 ruby)
rspec (2.6.0)
rspec-core (2.6.4)
rspec-expectations (2.6.0)
rspec-mocks (2.6.0)
shoes-cucumber (0.0.1)
term-ansicolor (1.0.6)

I looked elsewhere but could not find any solution. I also have ruby 1.9.2 built from source on my system. I tried un-installing ruby on my system and then use rvm only but that didn't work either. Is it because of the ruby version other than rvm installed on my machine? Or is it some issue with rake?

**Comment by steveklabnik** [comment]
Hm, this is very strange. Can you 'rm -rf dist' to delete the dist folder and try running again?

It's not compiling anything for some strange reason.

Oh, and I'd take a pull request to put Rake in the gemfile. ;)

**Comment by b1ackb0x** [comment]
Did that, but getting the same error. It looks like the dist folder is not getting created at all. I also tried it with rake clean but no use.

```
** Execute dist/libshoes.so
gcc -o dist/libshoes.so shoes/canvas.o shoes/ruby.o shoes/image.o shoes/world.o shoes/effects.o shoes/app.o shoes/internal.o shoes/native/gtk.o shoes/http/curl.o  -pthread -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lgdk_pixbuf-2.0 -lpangocairo-1.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0 -lcurl -fPIC -shared -lruby -lcairo -lpangocairo-1.0 -lungif -ljpeg -lrt -L/usr/local/rvm/rubies/ruby-1.9.2-p290/lib -lcairo -pthread -lpango-1.0 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0
/usr/bin/ld: cannot open output file dist/libshoes.so: No such file or directory
collect2: ld returned 1 exit status
rake aborted!
Command failed with status (1): [gcc -o dist/libshoes.so shoes/canvas.o sho...]
```

**Comment by steveklabnik** [comment]
Hm, this is very strange. @wasnotrice, @wilkie, @ccoupe, any ideas?

**Comment by wasnotrice** [comment]
I ran into this as well. Here's a pull request that should fix it.

https://github.com/shoes/shoes/pull/130

**Comment by steveklabnik** [comment]
It's been merged. Please let us know if this works, so we can close!

**Comment by b1ackb0x** [comment]
It worked! Thanks a lot for your help. :)

**Comment by wasnotrice** [comment]
b1ackb0x: Glad to hear! Thanks for the report, and have fun with Shoes!
