### ISSUE TITLE
Build Fails on Ubuntu(x86_64-linux) (Policeman r 1256)

### ISSUE THREAD

**Issue by edahood** [shoes/shoes-deprecated#13]
I have been trying to build shoes and am really frustrated.  I would either love some help fixing it or if someone could update the "Recent Builds" download with an X86_64-linux for (build 1256) that would be awesome.  Here is the error I get:
gcc -I. -c -oshoes/http/curl.o -Wall -I/usr/include -I/usr/local/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/local/include/pango-1.0 -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/opt/ruby/lib/ruby/1.9.1/x86_64-linux -I/opt/ruby/include/ruby-1.9.1 -I/opt/ruby/include/ruby-1.9.1/x86_64-linux -O  -DRUBY_1_9 -DSHOES_GTK -fPIC -I/usr/local/include/cairo -I/usr/local/include/pango-1.0 -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12  shoes/http/curl.c
gcc -o dist/libshoes.so shoes/ruby.o shoes/world.o shoes/image.o shoes/internal.o shoes/effects.o shoes/app.o shoes/canvas.o shoes/native/gtk.o shoes/http/curl.o  -L/usr/local/lib -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lpangoft2-1.0 -lgdk_pixbuf-2.0 -lm -lpangocairo-1.0 -lgio-2.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lgmodule-2.0 -lglib-2.0 -lcurl -lidn -lssl -lcrypto -llber -lldap -lrt -lgssapi_krb5 -lgssapi_krb5 -lssl -lcrypto -lz -fPIC -shared  -lruby -lpng -lcairo -lpangocairo-1.0 -lungif -ljpeg -lrt -L/opt/ruby/lib -L/usr/local/lib -lcairo -L/usr/local/lib -lpango-1.0 -lgobject-2.0 -lgmodule-2.0 -lglib-2.0
/usr/bin/ld: cannot find -lruby
collect2: ld returned 1 exit status
rake aborted!
Command failed with status (1): [gcc -o dist/libshoes.so shoes/ruby.o shoes...]
/home/eliot/myruby/tutorials/shoes/Rakefile:457:in `block in <top (required)>'
(See full trace by running task with --trace)

**Comment by zaius** [comment]
Having the same problem. Looks like it can't find the curl-config command, but it's definitely installed. Did you manage to get it working?

**Comment by atomicules** [comment]
I'd be interested to hear if anyone has got Shoes to build on 64bit linux. Please consider posting to the mailing list if you are trying to build on 64bit Linux, as we also have someone attempting on Snow Leopard (64 bit OSX). Build problems could be related.

**Comment by zaius** [comment]
I did get it working! No idea what I had to do though - I think I installed a million different packages trying to work out what was going wrong. 

I had to set LD_LIBRARY_PATH to /usr/lib to get rake to find curl-config. If anyone else has troubles, let me know and I can possibly examine my history file.

**Comment by atomicules** [comment]
Zaius, you got it to build on 64bit Linux? Fantastic! It really would be a great help if you could figure out what steps you had to do. Here is someone else's recent attempt, [64 Bit Arch](http://groups.google.com/group/shoooes/browse_thread/thread/4ffb5db404a55bf1/94fc09de6438f6ee?lnk=gst&q=64+bit#94fc09de6438f6ee)

**Comment by zaius** [comment]
I did a search through my history, and it looks like these were all the commands I ran:

git clone git://github.com/shoes/shoes.git
sudo apt-get install git-core libcairo2-dev libpixman-1-dev libpango1.0-dev libungif4-dev libjpeg62-dev libgtk2.0-dev vlc libvlc-dev libportaudio19-dev libsqlite3-dev libcurl4-openssl-dev ruby1.8-dev
sudo apt-get install portaudio19-dev
export LD_LIBRARY_PATH=/usr/lib
sudo apt-get install libgif-dev
sudo apt-get install libsqlite3-dev
rake

I'm on ubuntu 9.10. Here's my uname
Linux ideapad 2.6.31-17-generic #54-Ubuntu SMP Thu Dec 10 17:01:44 UTC 2009 x86_64 GNU/Linux

**Comment by zaius** [comment]
I should add, I've been seeing segfaults on some programs, so I'm guessing it's not completely working. I have no idea how to go about fixing that, but I'll see what I can do.

**Comment by zaius** [comment]
Actually, no, I lied. The segfaults were the reason I started trying to compile it myself. It's working fine now. Apologies if my bad memory has caused confusion.

**Comment by atomicules** [comment]
Zaius, thanks very much for the info.
