### ISSUE TITLE
 rake osx:deps:install fails on osx 10.7.1

### ISSUE THREAD

**Issue by jtmkrueger** [shoes/shoes-deprecated#131]
Here's my stacktrace:

`
~/ruby/shoes(develop) > rake osx:deps:install --trace
Package pango was not found in the pkg-config search path.
Perhaps you should add the directory containing`pango.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pango' found
Package pango was not found in the pkg-config search path.
Perhaps you should add the directory containing `pango.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pango' found
** Invoke osx:deps:install (first_time)
** Invoke osx:deps:bootstrap (first_time)
** Execute osx:deps:bootstrap
cd /usr/local
fatal: Not a git repository (or any of the parent directories): .git
git remote add shoes git://github.com/wasnotrice/homebrew.git
fatal: Not a git repository (or any of the parent directories): .git
rake aborted!
Command failed with status (128): [git remote add shoes git://github.com/wasn...]
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/file_utils.rb:53:in`block in create_shell_runner'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/file_utils.rb:45:in `call'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/file_utils.rb:45:in`sh'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/file_utils_ext.rb:36:in `sh'
/Users/john_t_krueger/Ruby/shoes/Rakefile:159:in`block (4 levels) in <top (required)>'
/Users/john_t_krueger/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/fileutils.rb:121:in `chdir'
/Users/john_t_krueger/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/fileutils.rb:121:in`cd'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/file_utils_ext.rb:36:in `cd'
/Users/john_t_krueger/Ruby/shoes/Rakefile:157:in`block (3 levels) in <top (required)>'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/task.rb:205:in `call'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/task.rb:205:in`block in execute'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/task.rb:200:in `each'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/task.rb:200:in`execute'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/Users/john_t_krueger/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/monitor.rb:201:in`mon_synchronize'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/task.rb:176:in`block in invoke_prerequisites'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/task.rb:174:in `each'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/task.rb:174:in`invoke_prerequisites'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/Users/john_t_krueger/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/monitor.rb:201:in`mon_synchronize'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/task.rb:144:in`invoke'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/application.rb:112:in `invoke_task'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/application.rb:90:in`block (2 levels) in top_level'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/application.rb:90:in `each'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/application.rb:90:in`block in top_level'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/application.rb:84:in`top_level'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/application.rb:62:in `block in run'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/application.rb:129:in`standard_exception_handling'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/gems/rake-0.9.2/bin/rake:32:in`<top (required)>'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/bin/rake:19:in `load'
/Users/john_t_krueger/.rvm/gems/ruby-1.9.2-p290@shoes/bin/rake:19:in`<main>'
Tasks: TOP => osx:deps:install => osx:deps:bootstrap
`

**Comment by jtmkrueger** [comment]
I installed bundler in a new gemset, ran bundle install then rake osx:deps:install.

**Comment by steveklabnik** [comment]
This is the relevant part:

```
cd /usr/local
fatal: Not a git repository (or any of the parent directories): .git
git remote add shoes git://github.com/wasnotrice/homebrew.git
```

Interesting. Let me guess: do you have homebrew installed?

**Comment by jtmkrueger** [comment]
Just installed it right before I tried to install shoes...  also just tried running in a new terminal buffer.

**Comment by steveklabnik** [comment]
Hm. Okay. The issue is that your /usr/local is not a git repository. Mine is. I _thought_ this is because of homebrew... @wasnotrice, any ideas?

A temporary fix would be to do a 'git init' inside your /usr/local directory, but I'd really like to find the root cause.

**Comment by jtmkrueger** [comment]
So do you want me to wait on running `git init` inside my `/usr/local`?

**Comment by steveklabnik** [comment]
It depends. If you'd like to get shoes going, just go ahead and do it, but if you'd like to help figure it out... I'm doing some googling. Either one is fine!

**Comment by jtmkrueger** [comment]
I'm fine with helping out @steveklabnik if shoes can be better of than when I started using it, that would be cool!

**Comment by steveklabnik** [comment]
Awesome. This build process is a work in progress, so fixing some bugs would be sweeeeet. I don't have 10.7 myself, so it's hard for me to test.

I'm asking in ##homebrew on irc, but nobody's answered yet. If you're into irc, you should jump on #shoes. Otherwise, I'll keep you notified here with what I find!

**Comment by steveklabnik** [comment]
Ah ha!

Check this thread: https://github.com/mxcl/homebrew/issues/5128

>  But the installer script just untars the homebrew tarball into /usr/local, and as @digitalcardboard noted, when brew update is run for the first time, it runs git init, and then after pulling down from the github repo it tries to checkout the master branch which results in all the conflicts that you are seeing. 

So, we've run 'brew update' before, i bet. Try that? See if it makes a  git repo there.

**Comment by jtmkrueger** [comment]
This is the issue I had after running `brew update` http://pastie.org/2440053

**Comment by jtmkrueger** [comment]
tried running `rake`, It failed then tried `brew install -vd cairo`: http://pastie.org/2440097

Heres the brew doctor output: http://pastie.org/2440102

**Comment by wasnotrice** [comment]
This issue turned out to be a conflict between homebrew and macports (see line 177 of http://pastie.org/2440053). Should be closed
