### ISSUE TITLE
link "something", :click => url doesn't use my default browser

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes-deprecated#138]
Hey there,
when I use:

```
para (link "something", :click => url)
```

in my programs (same thing happens when using hacketyhack) it starts the Chromium browser not Firefox, which is my default browser and all other applications open links with Firefox. I am running Linux Mint 11 x64 (based upon Ubuntu 11.04) and Firefox and Chromium are the only browsers installed.

Or is it a friendly suggestion, that I should change my browser? ;-)

edit: Just for the record: Launchy.open(url) does the thing I'd suspect to happen (open the homepage in a new tab in Firefox). And it doesn't matter whether Firefox is open or not, it always opens Chromium.

**Comment by steveklabnik** [comment]
Hm. How strange. I'd imagine we want to respect the default browser.

**Comment by PragTob** [comment]
Yeah that'd be great :-) But I fear that this lies buried deep somewhere in the C-code, but as it's not performance critical why not use launchy for it as it seems to do the trick and it's one less thing for Shoes to worry about (delete more code!) :-)

**Comment by nashby** [comment]
@steveklabnik I found the problem: https://github.com/shoes/shoes/blob/develop/shoes/native/gtk.c#L611
so it runs `/etc/alternatives/x-www-browser` and it looks like it run chrome every time and I can't change it with GUI tool that ships with Ubuntu (but I can change it through command line). And BTW, `/etc/alternatives/x-www-browser` works only in debian like systems like ubuntu, etc. So, I think we can't change it to `xdg-open` command. Looks like this tool respects default browser. What do you think?

**Comment by steveklabnik** [comment]
Ah ha! That makes total sense. Sounds good to me!

**Comment by PragTob** [comment]
xdg-open certainly seems to work for me. Thanks for looking into it!
