### ISSUE TITLE
Mac version just locks up

### ISSUE THREAD

**Issue by trvrplk** [shoes/shoes-deprecated#141]
launched the mac version but nothing happened

**Comment by trvrplk** [comment]
now it launches, but quits upon launch

**Comment by steveklabnik** [comment]
Are you on OSX Lion?

**Comment by trvrplk** [comment]
yes, but Shoes 2 works on Lion. Wierd.

**Comment by steveklabnik** [comment]
Yeah, it's a path issue.

We almost have it fixed. See the other thread for details.

**Comment by sobko** [comment]
Which other thread?  Hackety Hack is working on Lion now (yay) , but the Shoes 3 app still fails.

**Comment by steveklabnik** [comment]
Argh, I didn't post it. Let me post it up.
