### ISSUE TITLE
Ubuntu package is out of date

### ISSUE THREAD

**Issue by jrgifford** [shoes/shoes-deprecated#143]
So, I was looking through the Ubuntu packages, and I found [`shoes`](http://packages.ubuntu.com/oneiric/shoes) - version 0.r396-5, from 2008. So, way I see it, there are two options:
- Update it.
- Get it removed.

**Comment by steveklabnik** [comment]
If you can make this happen, id love it. I filed some paperwork a year ago,
never heard back.

**Comment by jrgifford** [comment]
Ok, did some digging. Looks like Ubuntu gets it from Debian, which means I'd have to go up one more. Want me to try to package it and then get it uploaded, or do you want me to get it removed, or.....?

**Comment by steveklabnik** [comment]
Try to package and upload it! :)

**Comment by jrgifford** [comment]
Guess I've got a project for tonight. :)

**Comment by jrgifford** [comment]
Status update: https://gist.github.com/1233849 - I've got one, not
sure I made things the right way though.

**Comment by jrgifford** [comment]
Another status update: It's working, just need to get debian to accept it. And they don't seem interested in answering my emails... I'll look into making a PPA if I don't get a response in a few days.

**Comment by steveklabnik** [comment]
Cool. :)

**Comment by jrgifford** [comment]
OK, PPA for 11.10/Oneiric is up. - https://launchpad.net/~jamesgifford/+archive/shoesrb

Next step is to poke at some Ubuntu guys and get them to sponsor the upload into the main repositories. 

However, until #155 is fixed, I can't do anything with it. :(

**Comment by steveklabnik** [comment]
It doesn't look like this is going to get taken care of any time soon, because the Ubuntu guys suck.
