### ISSUE TITLE
Shoes build fails on Ubuntu 11.04 (Natty)

### ISSUE THREAD

**Issue by ccoupe** [shoes/shoes-deprecated#148]
It seems that Ubuntu 11.04 has moved /usr/lib/libjpeg.so and /usr/lib/libsqlite3.so into  /usr/lib/i386-linux-gnu/ (32bit) OR /usr/lib/x86_64-linux-gnu/ (64bit).  In shoes/make/linux/tasks.rb the code needs to know more about where the .so's really are.   Apologies is this is a duplicate bug report.

**Comment by steveklabnik** [comment]
This was fixed with your patch right?

**Comment by ccoupe** [comment]
yes, the patch fixes the issue for ubuntu 64bit but should be tested on other Linux configs to make sure nothing bad happens.

**Comment by steveklabnik** [comment]
Cool. I think #147 should handle that, so I'll leave this closed.
