### ISSUE TITLE
building with rbenv ruby 1.9.2p290 on OS X Lion

### ISSUE THREAD

**Issue by memon** [shoes/shoes-deprecated#150]
I am trying to build shoes on OS X Lion. I use rbenv with ruby-build to install ruby 1.9.2p290 but I can't get past the 

rake osx:deps:install

It keeps repeating these 2 lines

/Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/file_utils_ext.rb:36:in `cd'
/Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rake-0.9.2/lib/rake/dsl_definition.rb:156:in`cd'

and after a while it just says stack level too deep and quits

**Comment by steveklabnik** [comment]
Hm. That's no good...

**Comment by memon** [comment]
just tried again without rbenv.

installed 1.9.2 with homebrew and still same issue.

**Comment by steveklabnik** [comment]
Yeah, it appears to be something with cd ... what shell are you using?

**Comment by memon** [comment]
bash with iTerm

after your comment I also tried with zsh same issue

**Comment by memon** [comment]
fixed

uninstalled all versions of rake and reinstalled

**Comment by steveklabnik** [comment]
Crazy. Hrm.
