### ISSUE TITLE
building with rbenv rubinius 2.0 on OS X Lion

### ISSUE THREAD

**Issue by memon** [shoes/shoes-deprecated#151]
I am trying to build shoes on OS X Lion with rbenv using rubinius 2.0. I can't get past rake osx:deps:install

the output is:

A syntax error has occurred:
    Invalid char `\317' in expression
    near line /Users/ali/.rbenv/versions/rbx-2.0.0-dev/bin/rake:1, column 1

Code:
????
^

Backtrace:
     Rubinius::Melbourne#syntax_error at /Users/ali/.rbenv/versions
                                         /rbx-2.0.0-dev/runtime/18
                                         /melbourne.rbc:62
       Rubinius::Melbourne#parse_file at /Users/ali/.rbenv/versions
                                         /rbx-2.0.0-dev/runtime/18
                                         /melbourne.rbc:78
 Rubinius::Compiler::FileParser#parse at /Users/ali/.rbenv/versions
                                         /rbx-2.0.0-dev/runtime/18/compiler
                                         /stages.rbc:232
  Rubinius::Compiler::Parser(Rubinius::Compiler::FileParser)#run at \
          /Users/ali/.rbenv/versions/rbx-2.0.0-dev/runtime/18/compiler/stages.rbc:215
               Rubinius::Compiler#run at /Users/ali/.rbenv/versions
                                         /rbx-2.0.0-dev/runtime/18/compiler
                                         /compiler.rbc:370
           Rubinius::Compiler.compile at /Users/ali/.rbenv/versions
                                         /rbx-2.0.0-dev/runtime/18/compiler
                                         /compiler.rbc:82
     Rubinius::CodeLoader#compile_file at kernel/delta/codeloader.rb:164
        Rubinius::CodeLoader#load_file at kernel/delta/codeloader.rb:145
      Rubinius::CodeLoader#load_script at kernel/delta/codeloader.rb:61
      Rubinius::CodeLoader.load_script at kernel/delta/codeloader.rb:107
               Rubinius::Loader#script at kernel/loader.rb:626
                 Rubinius::Loader#main at kernel/loader.rb:780

**Comment by steveklabnik** [comment]
Building with RBX isn't currently supported, but this is good to know!
