### ISSUE TITLE
You have to purge $SHOES/dist/* manually when trying a new build

### ISSUE THREAD

**Issue by jrgifford** [shoes/shoes-deprecated#152]
When you try to build shoes on Ubuntu, you have to purge `$SHOES/dist/*`, otherwise it won't compile correctly. 

Shouldn't this be part of the build script?

**Comment by steveklabnik** [comment]
Hrm. `rake clean` should take care of this kind of thing.

What happens if you don't kill it?

**Comment by wasnotrice** [comment]
I don't think `rake clean` is part of the build, though. It's for sure not on OS X, although that directory is purged in the OS X build. We should make `task *:build => :clean` where `*` is the OS namespace

**Comment by steveklabnik** [comment]
Sure, it's not part of the build, but that's because it's not required.

If it really is, I'm not opposed to adding it.

**Comment by jrgifford** [comment]
RE: what happens if it isn't purged on Ubuntu 11.04/11.10.

It generally exits with something like this:

> checking for sqlite3_load_extension()... yes
> creating Makefile
> gcc -shared -o sqlite3_native.so database.o sqlite3.o exception.o statement.o -L. -L/home/jrg/.rvm/rubies/ruby-1.9.2->p290/lib -Wl,-R/home/jrg/.rvm/rubies/ruby-1.9.2-p290/lib -L/usr/local/lib -Wl,-R/usr/local/lib -L/opt/local/lib -Wl,->R/opt/local/lib -L/usr/lib -Wl,-R/usr/lib -L.  -rdynamic -Wl,-export-dynamic   -Wl,-R -Wl,/home/jrg/.rvm/rubies/ruby-1.9.2->p290/lib -L/home/jrg/.rvm/rubies/ruby-1.9.2-p290/lib -lruby -lsqlite3  -lpthread -lrt -ldl -lcrypt -lm   -lc
> rake aborted!
> File exists - (libruby.so, dist/libruby.so.1.9)
> 
> Tasks: TOP => default => build => linux:build => old_build
> (See full trace by running task with --trace)

The exact `File exists` error will change, if you purge the `libruby.so, dist/libruby.so.1.9` files and run `rake` again, it'll do something else (normally `File exists - (libgif.so.4, dist/libungif.so.4)`).

**Comment by ccoupe** [comment]
rake clean is an important task step for developers. Try compiling with 1.9.1. Now try compiling with 1.9.2 w/o the rake clean.

**Comment by wasnotrice** [comment]
Closing this issue. Use `rake clean` when you want to delete `dist`. If you want to clean and build all at once, just do `rake clean && rake`
