### ISSUE TITLE
Mac 10.7.1 Shoes 3.1 won't package an app.

### ISSUE THREAD

**Issue by sobko** [shoes/shoes-deprecated#153]
The console says:

  no such file to load -- binject
 internal:lib/rubygems/custom_require:29:in 'require'

as soon as you choose "Package an App" from the menu.  What is internal:lib?  I have rvm set up on my machine - is this messing with Shoes?

**Comment by steveklabnik** [comment]
How are you packaging? There are three ways.

**Comment by sobko** [comment]
I open Shoes.app  From the window, I select "Package an app".  I don't even get the choose file dialog, because of the above error.

I also tried:

I open Shoes.app.  From menu, I select "Package".  Shoes quits unexpectedly with long error message.

What is the third way?

**Comment by steveklabnik** [comment]
Cool. The third way is totally undocumented, but it's how I compile Hackety Hack. You need a .app.yml file, and you can compile `rake APP=....` instead of just `rake`.

If I remember correctly, the packager via the menu has been broken for a bit. I really do need to take a look into it, so this is a good bug report.

**Comment by steveklabnik** [comment]
This is probably a 1.9.1 to 1.9.2 thing, with `.` being removed from `$:`. @wasnotrice, thoughts?

**Comment by ccoupe** [comment]
Ah, my long lost friend binject.  I'm still on Shoes 3.0 where binject is built by both 1.9.1 and 1.9.2. As steve noted when it is built correctly, it has lots of limitations.

**Comment by wasnotrice** [comment]
Thanks for the report. The reqs are not being copied into the correct place in the app on universal builds. Working on a fix.

**Comment by wasnotrice** [comment]
This binject issue is fixed by ef1b32128da6019d7687a30a38d6e70b5bc75e62. I think this fix will play nice with linux and windows builds, but it is untested on those platforms. Do note, however, that the GUI packager is actually still broken, and you are better off packaging like @steveklabnik [suggested](#issuecomment-2508192)

**Comment by kelso** [comment]
I have this problem too on OS X 10.8.2.

**Comment by lonny** [comment]
Shoes is useless to me unless I can package apps. Messages in this thread are over a year old, with apparently no resolution. Can you explain how to make the .app.yml file? What does it have to have in it?

I am also on OS X 10.8.2. When I click "Package an App." on the main window, nothing happens. When I choose it from the menu, Shoes crashes.

An empty .app.yml file didn't do anything. And rake gives me "No Rakefile found".

**Comment by steveklabnik** [comment]
Shoes development is frozen while we work on Shoes 4: https://github.com/shoes/shoes4

**Comment by lonny** [comment]
I went to the shoes4 site on github, and followed the directions exactly as written: cloned into a "shoes4" directory, installed jruby (1.7.2) via rvm, ran bundle install, created a directory under shoes4 (in this case just called "t"), installed bundler gem, ran bundle install, rake gem, installed the shoes pre1 gem, ran all the specs and they work (a few "pending" but no errors).

All good so far.

Then ran "bin/swt-shoooes t/myapp.rb" (which is actually a "get file name" example from the original shoes). It runs.

Then I created an app.yaml ("yaml", not "yml", as shown on the github page), and changed nothing but the name ("Welcome") and shortname ("welcome") of the app. Put it in the same directory ("t") as my .rb file.

Then ran "bin/shoes -p swt:app t/myapp.rb" ... and it doesn't work. This is the error:

Psych::SyntaxError: (<unknown>): could not found expected ':' while scanning a simple key at line 18 column 1
              parse at org/jruby/ext/psych/PsychParser.java:221
 parse_stream at /Users/lonny/.rvm/rubies/jruby-1.7.2/lib/ruby/1.9/psych.rb:205
              parse at /Users/lonny/.rvm/rubies/jruby-1.7.2/lib/ruby/1.9/psych.rb:153
                load at /Users/lonny/.rvm/rubies/jruby-1.7.2/lib/ruby/1.9/psych.rb:129
                load at /Users/lonny/shoes/shoes4/lib/shoes/package/configuration.rb:75
         package at /Users/lonny/shoes/shoes4/lib/shoes/cli.rb:58
                 run at /Users/lonny/shoes/shoes4/lib/shoes/cli.rb:85
             (root) at -e:1

Any ideas?

**Comment by steveklabnik** [comment]
Can you file a bug over there, please? I'm not sure if the Shoes 4 team is following these bugs as closely as I am ;)

Sounds like the yaml is getting generated wrong.

**Comment by lonny** [comment]
I will. Just curious, though, because I am new to Shoes: which yaml do you mean? The yaml file I have with my app is a copy of their example, with nothing but the app name changed. The error message says line 18 column 1 but that's just whitespace.

**Comment by steveklabnik** [comment]
I just meant 'Psych::SyntaxError: ' is a YAML-related error.
