### ISSUE TITLE
Error in build instructions for OS X

### ISSUE THREAD

**Issue by FrankDMartinez** [shoes/shoes-deprecated#158]
Hi,
    I am trying to build Shoes for OS X 10.5 and the instructions for building on 10.6 and 10.7 say to change a line in the Rakefile which reads "dylibs << '/usr/local/etc/pango/pango.modules'". One problem: no such line exists in the Rakefile. Soooo, what do I do instead?

**Comment by wasnotrice** [comment]
First of all, it would be great if you can build Shoes for 10.5! You should know, however, that it hasn't yet been done, so you will be the first.

Looks like you are trying to build Shoes using MacPorts. Homebrew is preferred, so it might be easier to use Homebrew if you can. As you have noticed from the instruction, the MacPorts build process is currently filled with modifications and workarounds, and you have discovered that at least one of them is out of date.

That said, we should fix the instructions that are outdated. I'll offer some ideas, and please update the wiki when you figure out what works :)

I think what you want to do is set `modules_file` to the path of `pango.modules` in your MacPorts tree. It's on [line 330 of the Rakefile](https://github.com/shoes/shoes/blob/develop/Rakefile#L330)

Give that a shot and see if it works!

**Comment by FrankDMartinez** [comment]
Thanks, I will let You know. I did try the 'homebrew' approach but it fails during the 'rake osx:deps:install' phase. I filed an issue with the Maintainers and am waiting for it to be addressed since I have no idea how to proceed in order to fix it Myself.

**Comment by wasnotrice** [comment]
I'd recommend sticking with homebrew if you can. Looks like they've already fixed your issue!

https://github.com/mxcl/homebrew/issues/8510

**Comment by FrankDMartinez** [comment]
Well, something happened alright but I do not think it was what I wanted. Using 'rake --trace', I get the output found at https://gist.github.com/1358286. Any thoughts on how to proceed? Apart from the erros prompted by the use of the '-arch' option, one piece which strikes Me as possibly incorrect is the reference to the 10.6 SDK but that information is possibly less urgent at this stage than the '-arch' errors. I am not certain enough how the command line is being created to alter this Myself.

**Comment by wasnotrice** [comment]
Right, so the SDK is hard-coded at the moment to 10.6, and I think it's in more than one place in the code :( Haven't gotten around to refactoring that yet...You probably have to change that. You would change instances in `Rakefile` and `make/darwin/env.rb` (ignore `make/darwin/tasks.rb`). Maybe the -arch flag is not available with your version of gcc? My version (that works) is 4.2.1. Here's the [output of gcc -v](https://gist.github.com/1358321) on my machine.

**Comment by FrankDMartinez** [comment]
Okay, so, this has really become two issues then (1) homebrew: I did a 'brew update' after clearing out the *.gz files from ~/Library/Caches/Homebrew and am getting a new error on 'rake osx:deps:install' relating to -march options (this seems related to the fact homebrew is trying to use GCC 4.2 when My system is set to use GCC 4.5 from mac ports) but I can discuss that with the homebrew People and (2) My GCC 4.2 is build 5577 (https://gist.github.com/1358364).

Switching to GCC 4.2 (via 'port select'), homebrew ... (trying it out) ... still fails on the same spot. Yep, definitely need to discuss with the homebrew People.

Making the changes in Rakefile and make/darwin/env.rb, well, no reference in Rakefile but in the env.rb I have two. Upon changing them and running rake, I get warnings about converting 64 bit types to 32 bit values. These warnings cause rake to abort since, for whatever reason, the compiler is being passed a -Werror=shorten-64-to-32 option. As far as I can tell, this option is not requested by the Rakefile, yes?

**Comment by FrankDMartinez** [comment]
So ... does Anyone have any thoughts about the rakefile with respect to -Werror=shorten-64-to-32 option or why the rake command is trying to use that option?

**Comment by jwoertink** [comment]
I tried building shoes on 10.6.8 today. Followed the instructions on https://github.com/shoes/shoes/wiki/Building-Shoes-on-Mac-OS-X-10.6-and-10.7 for packaging using homebrew. Here is the output I get when I run the final rake

https://gist.github.com/1795791

I checked my gcc -v, and it's gcc version 4.2.1 (Apple Inc. build 5666) (dot 3)
I did notice though that after running rake osx:deps:install that pango didn't get installed. I ended up running

```
brew install pango
rake
```

Not sure if this is a bug, or my system being stupid, but if it is then hopefully this helps someone.

**Comment by wasnotrice** [comment]
Did you get any message about why pango wasnt installed?

**Comment by jwoertink** [comment]
I wasn't really paying attention too much, but I think it might have had something to do with not using the LLVM, and using the GCC instead.... I'll try and see if I can recreate it somehow.

**Comment by steveklabnik** [comment]
I'm marking this as 'fixed' for now, since we've fixed the instructions. If anyone wants to tackle 10.5 again, let's make a new issue based on the current state of things.
