### ISSUE TITLE
build error:  In function ‘shoes_app_window’:

### ISSUE THREAD

**Issue by pronix** [shoes/shoes-deprecated#16]
when run standart rake
get error

gcc -I. -c -oshoes/app.o -Wall -I/usr/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/ruby/1.8/i386-linux -O  -DSHOES_GTK -fPIC -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12  shoes/app.c
shoes/app.c: In function ‘shoes_app_window’:
shoes/app.c:140: error: ‘s_always_on_top’ undeclared (first use in this function)
shoes/app.c:140: error: (Each undeclared identifier is reported only once
shoes/app.c:140: error: for each function it appears in.)
rake aborted!
Command failed with status (1): [gcc -I. -c -oshoes/app.o -Wall -I/usr/incl...]
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:994:in `sh'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1009:in`call'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1009:in `sh'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1093:in`sh'

**Comment by atomicules** [comment]
What platform are you trying to build on? Linux? As far as I know it should build fine on 32 bit Linux. I see references to Ruby 1.8, the latest Shoes code probably requires 1.9 now. Please provide a bit more info, or post to the mailing list and one of the Linux users will be able to help out.

**Comment by atomicules** [comment]
Pronix is using "fedora12 - 32bit and ruby 1,8.6". Posted to Shoes mailing list to request help from Linux users.

**Comment by steveklabnik** [comment]
As far as I know, Shoooes needs Ruby 1.9.1.

**Comment by pronix** [comment]
build on linux fedora12 with ruby191 - same error

**Comment by ashbb** [comment]
I could build Policeman with Ubuntu Linux 2.6.  
Look at [a tiny note](http://github.com/ashbb/shoes_hack_note/blob/master/md/hack026.md). 

Hope this helps,  
ashbb

**Comment by pronix** [comment]
after use branch always-on-top - all successfuly build
