### ISSUE TITLE
Font issue with Shoes 3.1.0 on OSX 10.6.8

### ISSUE THREAD

**Issue by atownley** [shoes/shoes-deprecated#160]
When trying to run Shoes from shoes-3.1.0.dmg I see the following:

[Font issue sample image](http://atownley.org/files/shoes-fonts.png)

The rest of the app (and demos) seem to work fine, but there is an issue displaying any of the fonts on the canvas itself.

$ ./shoes -v
shoes policeman (0.r1739) [universal.x86_64-darwin11.1.0 Ruby1.9.1]
$ uname -a
Darwin miyu.local 10.8.0 Darwin Kernel Version 10.8.0: Tue Jun  7 16:33:36 PDT 2011; root:xnu-1504.15.3~1/RELEASE_I386 i386

Also, even running from the command line, I didn't see any errors, so I'm not sure how best to provide additional information.  Google didn't give me any ideas on how to pass any additional --verbose or --debug arguments to Shoes for more output.

Hopefully, this is an easy fix...

Cheers,

ast

**Comment by wasnotrice** [comment]
Thanks :) When you launch Shoes.app, do you get any messages in Console.app?

**Comment by wasnotrice** [comment]
Did you, by chance, just launch Shoes straight from the .dmg? If you do that, you'll get the boxes:)

If so, copy Shoes.app to another location on your disk (like /Applications or ~/Desktop), and give it a shot from there.

**Comment by atownley** [comment]
Will have to check the other machine at the office to be sure, but not intentionally.  I originally copied it to the Applications directory before trying to mess with it at work.  However, this morning it's working properly when launched from the Applications directory on a different machine.

I guess it's a non-issue.  Might be worth adding to the FAQ somewhere, because I couldn't find any obvious troubleshooting tips for this issue.

Will close this issue as now having working environment and can move forward with my tinkering.  Thanks for the suggestion!
