### ISSUE TITLE
gem usage in shoes app

### ISSUE THREAD

**Issue by Anonyfox** [shoes/shoes-deprecated#162]
hi there!

on my windows 7 machine i am not able to load any gems specified in the "Shoes.setup"-block.
To be correct, shoes kills the c++ runtime when it is trying to build native extensions after downloading a gem. 

Same Procedure runs fine under my Ubuntu Linux.

shoes version: r1514

**Comment by steveklabnik** [comment]
Can you give me an example of some of the gems, so I can reproduce?

**Comment by Anonyfox** [comment]
Shoes.setup do
    gem 'json'
    gem 'sqlite3'
    gem 'activerecord'
    gem 'simple-rss'
end

^
|
this are the gems i need in my app. it crashes at the first gem, json, when building native extensions

**Comment by steveklabnik** [comment]
Ah! Native extension gems don't work with Shoes. At least, they're not guaranteed to. It works on linux because you have build tools installed. If you had them installed on Windows, it'd work as well.

**Comment by Anonyfox** [comment]
Thanks for clarifying!

**Comment by steveklabnik** [comment]
Yep! It's something I really wish we could fix. Oh well. :/ And someday, I'd like to work on getting better error messages for that...
