### ISSUE TITLE
rake build fails on Debian testing 64-bit

### ISSUE THREAD

**Issue by ngiger** [shoes/shoes-deprecated#169]
The following patch fixes the problem that we cannot find the libcurl.so under Linux (Debian wheezy AMD64-bit)
diff --git a/make/linux/tasks.rb b/make/linux/tasks.rb
index 2a99e28..065d752 100644
--- a/make/linux/tasks.rb
+++ b/make/linux/tasks.rb
@@ -33,7 +33,7 @@ class MakeLinux
       ln_s  "libgif.so.4", "dist/libungif.so.4"
       # cp    "/usr/lib/libjpeg.so", "dist/libjpeg.so.8"
       find_and_copy "libjpeg.so", "dist/libjpeg.so.8"
-      cp    "/usr/lib/libcurl.so", "dist/libcurl.so.4"
-      find_and_copy "libcurl.so", "dist/libcurl.so.4"
     cp    "/usr/lib/libportaudio.so", "dist/libportaudio.so.2"
     cp    "/usr/lib/libsqlite3.so", "dist/libsqlite3.so.0"
     # cp    "/usr/lib/libsqlite3.so", "dist/libsqlite3.so.0"

**Comment by steveklabnik** [comment]
Sweet, thanks! I'd apply this, but since it's a patch and not a pull request, it'll take me a few minutes, since I have to do more than click some buttons. ;)

Consider it applied, though. If someone else wants to do so, feel free.

**Comment by jrgifford** [comment]
@steveklabnik Just tested, it works, submitting pull request in a moment (and yes, i shall credit @ngiger.)

**Comment by petervandenabeele** [comment]
Now that the associated pull request is merged, should this issue not be closed?

**Comment by steveklabnik** [comment]
Absolutely, I don't know why @jrgifford's commit didn't do it. Whatever. :)
