### ISSUE TITLE
Trying to get buttons in a table is not working

### ISSUE THREAD

**Issue by FrankDMartinez** [shoes/shoes-deprecated#170]
Hi,
Running Shoes Policeman on Mac 10.7.2, the script at http://pastebin.com/jNtTECkZ prompts a "bad arguments" error on line 48. Replace line 48 with line 50, and the program runs fine. However, I would like to be able to have a button which 'does stuff' as a header instead of an inactive, plain text header. Sooo, Anyone have any idea what I am doing wrong or possibly able to point Me in the direction of a potential solution?

**Comment by ashbb** [comment]
Hi xuinkrbin,

Try to add `.to_s` like this: `p = button h[0].to_s`. ;-)

ashbb

**Comment by FrankDMartinez** [comment]
D'oh! I don't know why I did not try that. I guess I keep thinking of symbols as strings. Thanks!
