### ISSUE TITLE
Moving to ruby 1.9.3-p0 ?

### ISSUE THREAD

**Issue by petervandenabeele** [shoes/shoes-deprecated#173]
Are there known issues with going to MRI ruby 1.9.3?

I will set it up here with 1.9.3 and report if I see issues.
(essentially that is patching the .rvmrc file)

**Comment by steveklabnik** [comment]
I would love to see it. Big issue is Windows, which we still don't have working on 1.9.2.

**Comment by petervandenabeele** [comment]
OK thanks.

Why is the .rvmrc then set to 1.9.2 (if it doesn't work on Windows with 1.9.2) ?

_If_ that .rvmrc would not affect Windows anyways (I don't know that, just an open
"if" statement), then we could already set it to 1.9.3 for the rvm users.

I can confirm flawless install and operation on Ubuntu 10.04 and 11.10
with a .rvmrc set to 1.9.3, also tested with a number of the shoes samples.

**Comment by steveklabnik** [comment]
Because windows has a different build process that does not use your
'current ruby,' so the .rvmrc is irrelevant.

**Comment by steveklabnik** [comment]
... I'm not opposed to moving it up to 1.9.3 for mac and linux though.
Which would be the .rvmrc. feel free to pull request. :)
On Dec 29, 2011 10:07 AM, "Peter Vandenabeele" <
reply@reply.github.com>
wrote:

**Comment by petervandenabeele** [comment]
I ran the cucumber tests on shoes policeman (0.r1748) [i686-linux Ruby1.9.2]
with ruby 1.9.3-p0 and hit this Ruby bug.

/home/peterv/.rvm/gems/ruby-1.9.3-p0/gems/json-1.6.3/lib/json/common.rb:66: [BUG] unknown type 0x22 (0xc given)
ruby 1.9.3p0 (2011-10-30 revision 33570) [i686-linux]

I retested on ruby-1.9.3-head (currently 1.9.3-p6) and the bug was not triggered.

Details: https://gist.github.com/1539736

That was on this gemset:

peterv@ASUS:~/b/github/petervandenabeele/shoes$ gem list

**\* LOCAL GEMS ***

builder (3.0.0)
bundler (1.0.21)
cucumber (1.1.0)
diff-lcs (1.1.3)
gherkin (2.5.1)
json (1.6.1)
mechanize (2.0.1)
net-http-digest_auth (1.1.1)
net-http-persistent (1.9)
nokogiri (1.5.0)
rake (0.9.2.2, 0.9.2)
rspec (2.6.0)
rspec-core (2.6.4)
rspec-expectations (2.6.0)
rspec-mocks (2.6.0)
shoes-cucumber (0.0.2)
shoes-mocks (0.0.2)
term-ansicolor (1.0.6)
webrobots (0.0.11)

I suggest waiting with upgrade to 1.9.3-pxxx until a new patch release for MRI ruby,
retesting then and upgrading .rvmrc if that passes all tests.

Actually, I had expected a larger body of cucumber tests.
There where some Rspec tests, but these where irrelevant for my set-up
(only for homebrew, but I only have Linux systems I can test on).

**Comment by steveklabnik** [comment]
How strange. The JSON gem should work just fine on p0...

> Actually, I had expected a larger body of cucumber tests.

Right now, the tests are total bullshit: _why never wrote any tests, he didn't believe in them. The 'tests' that exist are sorta bullshit, more of a basic sanity check than anything else. We're trying to come up with a good testing strategy, but testing legacy code is hard, testing GUIs is even harder...

**Comment by petervandenabeele** [comment]
This issue was closed with the merge of pull request

https://github.com/shoes/shoes/pull/174

That pull request also refers to the discussion on ruby-talk about the
problems I had with the cucumber tests on my system.
