### ISSUE TITLE
Deps getting copied twice

### ISSUE THREAD

**Issue by steveklabnik** [shoes/shoes-deprecated#177]
In 4ae4eb1, we moved to 1.9.3. This made `dist/pango/modules` and a few other things get copied over with r-r-r permissions, rather than the correct rw-r-r permissions that happen under 1.9.2.

So why are they getting copied twice?

/cc @wasnotrice @petervandenabeele

**Comment by petervandenabeele** [comment]
On my system (Linux 32 bit), I don't see a dist/pango directory ...

Also, the only files that do not have the  u+w bit set (that are not user writeable)
seem to be those 4:

```
peterv@ASUS:~/b/github/shoes/shoes$ find . ! -perm -u+w./.git/objects/pack/pack-6dcb14d2826e516ffe958ed42c5fa1a19e9e4f71.idx
./.git/objects/pack/pack-6dcb14d2826e516ffe958ed42c5fa1a19e9e4f71.pack
./.git/objects/pack/pack-211f91c5e18f456b9b66cec876041d7efc6c8b7a.idx
./.git/objects/pack/pack-211f91c5e18f456b9b66cec876041d7efc6c8b7a.pack

peterv@ASUS:~/b/github/shoes/shoes$ ls -l ./.git/objects/pack/pack-6dcb14d2826e516ffe958ed42c5fa1a19e9e4f71.idx
-r--r--r-- 1 peterv peterv 13112 2012-01-04 22:23 ./.git/objects/pack/pack-6dcb14d2826e516ffe958ed42c5fa1a19e9e4f71.idx
```

**Comment by ccoupe** [comment]
1.9.3 ?!?!  I don't remember that discussion on the ML and BTW the distributed .rvmc doesn't work with my RVM setup. I think you're running too fast. Chill down or jump the shark.

**Comment by petervandenabeele** [comment]
1) Could you explain how the distributed .rvmrc does not work on your system please?

I added a --create for the shoes gemset

rvm --create 1.9.3@shoes

At least on my set-up (Linux 32 bit, rvm version 1.10.0) this works, both with
an existing gemset 'shoes' and when a new 'shoes' gemset needs to be created.

What is your environment and version of rvm?

2) The discussion was indeed not on the ML. There was a limited discussion here:

https://github.com/shoes/shoes/issues/173
https://github.com/shoes/shoes/pull/174

3) Do you see other problems with version 1.9.3 besides the .rvmrc problem

**Comment by steveklabnik** [comment]
@ccoupe 1.9.3 was supposed to be 100% backwards compatible with 1.9.2. So I figured we'd give it a shot. Windows is still a problem, of course.

This issue is probably enough for me to revert the 1.9.3, at least until it's resolved.

**Comment by petervandenabeele** [comment]
Fine for me.

**Comment by steveklabnik** [comment]
This doesn't really happen for me anymore.
