### ISSUE TITLE
Transparency doens't work in pngs only gifs on windows

### ISSUE THREAD

**Issue by atomicules** [shoes/shoes-deprecated#18]
See this Stackoverflow question: [Masks and transparency](http://stackoverflow.com/questions/623511/masks-and-transparency/2086416#2086416)

For instance, the following code, 

```
Shoes.app do
banner "hello this is a very long string", :top => 200
mask do
    image "test.gif", :top => 0
end
end
```

worked with a test.gif which was a 480x320 image with a solid oval in the middle. The rest of the image was transparent. This left the text appearing where the solid oval was in the image.

It does not work with a similar PNG.

(Whoops, tried to label this as Mustard, but mucked up. Certainly not a priority fix).

**Comment by ashbb** [comment]
Hi i5m,

On Windows, it looks like both Raisins (Shoes-0.r1134) and Policeman (0.r1413) work the above code well. I confirmed with the following image files.

http://www.rin-shun.com/shoes/test.gif

http://www.rin-shun.com/shoes/test.png

Could you confirm again?

ashbb

**Comment by atomicules** [comment]
Hi ashbb, 

how very strange. I've checked again and it works in both Raisins and Policeman. Perhaps it was to do with how I created the PNG? Although I just created another one from scratch using Paint.NET and it worked as well.

Closing out this issue.
