### ISSUE TITLE
Shoes fails to build on mac Lion. 

### ISSUE THREAD

**Issue by facetoe** [shoes/shoes-deprecated#183]
hello, I tried to build shoes on mac lion and got this error:

Fragmachines-MacBook:shoes fragmachine$ bundle install
Fetching source index for http://rubygems.org/
Using rake (0.9.2)
Installing builder (3.0.0)
Installing diff-lcs (1.1.3)
Installing json (1.6.1) with native extensions
Installing gherkin (2.5.1) with native extensions
Installing term-ansicolor (1.0.6)
Installing cucumber (1.1.0)
Installing net-http-digest_auth (1.1.1)
Installing net-http-persistent (1.9)
Using nokogiri (1.5.0)
Installing webrobots (0.0.11)
Installing mechanize (2.0.1)
Installing rspec-core (2.6.4)
Installing rspec-expectations (2.6.0)
Installing rspec-mocks (2.6.0)
Installing rspec (2.6.0)
Installing shoes-mocks (0.0.2)
Installing shoes-cucumber (0.0.2)
Using bundler (1.0.21)
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.
Fragmachines-MacBook:shoes fragmachine$ rake osx:deps:install
rake aborted!
No such file or directory - list

Tasks: TOP => osx:deps:install => osx:deps:homebrew:install => osx:deps:homebrew:install_libs
(See full trace by running task with --trace)
Fragmachines-MacBook:shoes fragmachine$ rake osx:deps:install --trace
*\* Invoke osx:deps:install (first_time)
*\* Invoke osx:deps:homebrew:install (first_time)
*\* Invoke osx:deps:homebrew:customize (first_time)
*\* Execute osx:deps:homebrew:customize
*\* Invoke osx:deps:homebrew:install_libs (first_time)
*\* Execute osx:deps:homebrew:install_libs
rake aborted!
No such file or directory - list
/Users/fragmachine/Ruby/shoes/make/darwin/homebrew.rb:110:in ``'
/Users/fragmachine/Ruby/shoes/make/darwin/homebrew.rb:110:in`brew_installed?'
/Users/fragmachine/Ruby/shoes/make/darwin/homebrew.rb:55:in `installed?'
/Users/fragmachine/Ruby/shoes/make/darwin/homebrew.rb:46:in`install'
/Users/fragmachine/Ruby/shoes/make/darwin/homebrew.rb:30:in `install_packages'
/Users/fragmachine/Ruby/shoes/Rakefile:241:in`block (4 levels) in <top (required)>'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/task.rb:205:in `call'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/task.rb:205:in`block in execute'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/task.rb:200:in `each'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/task.rb:200:in`execute'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/Users/fragmachine/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/monitor.rb:201:in`mon_synchronize'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/task.rb:176:in`block in invoke_prerequisites'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/task.rb:174:in `each'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/task.rb:174:in`invoke_prerequisites'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/Users/fragmachine/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/monitor.rb:201:in`mon_synchronize'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/task.rb:176:in`block in invoke_prerequisites'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/task.rb:174:in `each'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/task.rb:174:in`invoke_prerequisites'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/Users/fragmachine/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/monitor.rb:201:in`mon_synchronize'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/task.rb:144:in`invoke'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/application.rb:112:in `invoke_task'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/application.rb:90:in`block (2 levels) in top_level'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/application.rb:90:in `each'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/application.rb:90:in`block in top_level'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/application.rb:84:in`top_level'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/application.rb:62:in `block in run'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/application.rb:129:in`standard_exception_handling'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2/bin/rake:32:in`<top (required)>'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/bin/rake:19:in `load'
/Users/fragmachine/.rvm/gems/ruby-1.9.2-p290/bin/rake:19:in`<main>'
Tasks: TOP => osx:deps:install => osx:deps:homebrew:install => osx:deps:homebrew:install_libs
Fragmachines-MacBook:shoes fragmachine$ 

I've got xcode 4.1 installed.

**Comment by wasnotrice** [comment]
Looks like that's something I broke last night. Thanks for the report. I'll check it out

**Comment by facetoe** [comment]
Thanks that built perfectly.

**Comment by wasnotrice** [comment]
Great!
