### ISSUE TITLE
Alert in a thread bombs

### ISSUE THREAD

**Issue by steveklabnik** [shoes/shoes-deprecated#184]
This, for example, works:

``` ruby
app = Shoes.app do
 def hello
   para "hello"
 end
end

Thread.new do
 app.hello
end
```

Changing it to an alert totally bombs for me on OSX as well.

**Comment by ccoupe** [comment]
Yeah. I remember that alerts in threads fails in Linux too.  Way back to Shoes2 code.  Ruby thread.new knows nothing about Shoes or it's GUI thread(s) that Shoes Throwing up a Modal dialog in a Ruby thread is just asking for GUI trouble. IMO, this is a insolvable problem unless Shoes defines it's own Ruby Thread class that ties into the Ruby and GUI toolkit threads.  Madness lives there.

One can design around the limitation in Shoes.  The solution is a big note in the Shoes Manual: Do not create Shoes Windows or Dialogs in Ruby Threads. Just don't do it.

**Comment by steveklabnik** [comment]
> Madness lives there.

Agreed. Let's mark this as 'wontfix' for now, because if it does get solved, it sure isn't gonna be any time soon.
