### ISSUE TITLE
Shy files are unserialized as class Hash, not Shy, using 1.9.3

### ISSUE THREAD

**Issue by wasnotrice** [shoes/shoes-deprecated#187]
I think this has to do with the new default YAML library in 1.9.3. It works properly using the Shoes 3.1 beta build (ruby 1.9.2). This was tested with a `dictionary.shy` that was serialized using the 1.9.2-based Shoes, so I don't know if there's also a problem with the serialization side (I'm not sure if a `.shy` created with 1.9.3 would work). In any case, this is potentially a backward-compatibility issue.

<div class="thumbnail"><a href="https://skitch.com/wasnotrice/8ehyh/shoes"><img style="max-width:638px" src="https://img.skitch.com/20120310-bhg54a6bxyg4sxq6eqs564p7m1.medium.jpg" alt="Shoes" /></a>

Here's a copy of [dictionary.shy](http://dl.dropbox.com/u/610739/shoes/dictionary.shy)

**Comment by steveklabnik** [comment]
Yeah, YAML has been undergoing lots of changes; yet another @_why relic that's on the way out.

I'm not sure what the best way to handle this is. gonna think about it.

**Comment by ashbb** [comment]
Hi Eric,

I tried the following to confirm your problem with [Shoes-0.r1783 for Windows](http://www.rin-shun.com/shoes/shoes-0.r1783.exe). 
- create `c:\tmp\book` directory and put `class-book.rb` and `class-book.yaml`
- run shoes.exe (r1783)
- click `Package an App.` link
- select `book` directory and create `book.shy`
- run shoes.exe again
- click `Open an App.` link
- select [book.shy](http://www.rin-shun.com/shoes/book.shy)

There was no error...

Could you share your `dictionary.shy`? I'd like to try it out.

**Comment by ashbb** [comment]
Oops, now I realized your [dictionary.shy](http://dl.dropbox.com/u/610739/shoes/dictionary.shy). I'll check it out from now.

**Comment by ashbb** [comment]
Your [dictionary.shy](http://dl.dropbox.com/u/610739/shoes/dictionary.shy) seems to work well with [Shoes-0.r1783 for Windows](http://www.rin-shun.com/shoes/shoes-0.r1783.exe).

I can see a `Enter a Word` textblock, an edit_line and a `ok` button on the Shoes window. Although I get the `No definition found for xxxx. Sorry this doesn't actually work.` message, whenever I put any word into edit_line.

**Comment by wasnotrice** [comment]
@ashbb thanks for testing this out. You found the desired behavior. I chose a silly example :).

I wonder if your ruby 1.9.3 was compiled with the `Syck` yaml library that used to be the standard. Mine compiled with `Psych`:

```
huckle:shoes eric$ irb
1.9.3p125 :001 > require 'yaml'
 => true 
1.9.3p125 :002 > YAML
 => Psych 
```

**Comment by wasnotrice** [comment]
And just for reference,

```
huckle:shoes eric$ rvm use 1.9.2-p290
Using /Users/eric/.rvm/gems/ruby-1.9.2-p290
huckle:shoes eric$ irb
1.9.2p290 :001 > require 'yaml'
 => true 
1.9.2p290 :002 > YAML
 => Syck
```

**Comment by ashbb** [comment]
Hi Eric,

You are right!

I ran the following snippet with my Shoes-0.r1783 for Windows.

``` ruby
Shoes.app do
  para require 'yaml'
  para YAML
end
```

I got this result:

<pre>
false Syck
</pre>


and this error message on Shoes console window:

<pre>
Warn: It seems your ruby installation is missing psych (for YAML output).
</pre>

**Comment by wasnotrice** [comment]
@ashbb so maybe we need to decide whether we should include the standard ruby 1.9.3 (Psych) or a modified one (Syck). I do think this issue is a pretty easy fix, and there isn't _that_ much yaml in Shoes. Also, note that my Shoes built with Psych does create and extract `.shy`s fine, so it's just an issue with Psych extracting `.shy`s that were created by Syck.

Edit: by 'include', I mean include in a 3.1 Shoes release

**Comment by PragTob** [comment]
I think if it is really easy to add, then we should include Psych as it is the future and part of 1.9.3 which we wanted to include :-)

**Comment by mpapis** [comment]
not sure if it's fully related:
1. for psych you need `libyaml` in rvm we build it before building ruby 1.9.3, but a system existing lib could be theoretically reused (I do not know how to handle it on windows)
2. the yaml outputs from ruby 1.9 are incompatible with 1.8  ...  this is why I always build my gems with 1.8 rubies ...
3. have you considered breaking compatibility with existing shoes installations (btw. any stats on how many are there)

**Comment by wasnotrice** [comment]
@mpapis great points. We would have to add libyaml to our list of dependencies.

I did a quick test of a `.shy` I produced with my 1.9.3 Shoes (Psych), and it produced errors on my 1.9.2 Shoes (Syck). So this is definitely a concern. No data is lost, but the old code will not parse it correctly, which means that apps packaged with a standard 1.9.3 ruby Shoes will not be openable by older Shoeses.

I think this is not the release to break backwards compatibility. Might be an argument for sticking with 1.9.2 for this release, and moving to 1.9.3 in a later 4.0 release.

**Comment by steveklabnik** [comment]
> (btw. any stats on how many are there)

https://github.com/shoes/shoes/downloads

**Comment by wasnotrice** [comment]
After playing with this a little bit, I think the solution might be as simple as just adding a `require 'syck'` before `require 'yaml'`. See how it works in irb: https://gist.github.com/2023662

I'd vote for sticking with 1.9.3 and using Syck as above for this release (noting with sadness that, since it is not maintained, we have to transition away at some point). Thoughts?

**Comment by mpapis** [comment]
if there is nothing users need to do - I'm fine with it ;)

**Comment by steveklabnik** [comment]
:+1:
