### ISSUE TITLE
location() not available from urls

### ISSUE THREAD

**Issue by evanfarrar** [shoes/shoes-deprecated#2]
It would seem that the "location" method is a perfect way to do some reflection while using shoes url scheme (see the book example). However, that method is defined on app, and is thus not available from subclasses of shoes, and in the methods used for Shoes URLs.
- Version of Shoes you are running, including operating system version.

shoes policeman (0.r1226) [i486-linux]
- Shoes error console message (if applicable)

undefined method 'location' for (<#Class>::TestLocation)

Here is a snippet of code to replicate it:
    class TestLocation < Shoes
    url '/', :works
    url '/no_works', :not_works
    def not_works
      para("this one does not:")
      para(location)
    end
    def works
      p = para("this one works:")
      para(p.app.location)
      para(link("try the other way",:click => "/no_works"))
    end
    end
    Shoes.app

**Comment by ashbb** [comment]
Hi evanfarrar,

Try the following snippet. I think it works.
I confirmed on Windows (both Raisins (0.r1134) and Policeman (0.r1414)) only though.

<pre><code>
class TestLocation < Shoes
  url '/', :works
  url '/no_works', :not_works
  def not_works
    para("this one does not:")
    para(app.location)
  end
  def works
    p = para("this one works:")
    para(app.location)
    para(link("try the other way",:click => "/no_works"))
  end
end
Shoes.app
</code></pre>

**Comment by atomicules** [comment]
Evan, ashbb, 

tested ashbb's snippet on OSX PPC Raisins and Policeman and it works.
