### ISSUE TITLE
Text can't have alpha

### ISSUE THREAD

**Issue by atomicules** [shoes/shoes-deprecated#20]
See this Stackoverflow question: [Make text transparent in Shoes.app](http://stackoverflow.com/questions/1214308/make-text-transparent-in-shoes-app)

Alpha works on stroke and fill, but not on text. Example app from Pesto:

```
Shoes.app do
      para "Text", :stroke => rgb(1.0,0.0,0.0,0.5), :fill => rgb(0, 1.0, 0, 0.5), :size => 100
      stroke rgb(0,0,1.0,0.5)
      strokewidth 4
      nofill
      oval 10, 10, 50
end
```

**Comment by steveklabnik** [comment]
I'm closing all feature request Issues, in favor of moving them to the wiki instead. This'll make it easier to lay them out into planning for future releases. Please see [here](https://github.com/shoes/shoes/wiki/Shoes-roadmap). Thanks!
