### ISSUE TITLE
strokewidth returns self; manual says it should return a number

### ISSUE THREAD

**Issue by wasnotrice** [shoes/shoes-deprecated#200]
The manual says that strokewidth should return a number. It actually returns self. It doesn't seem like Shoes is trying to get all return-self-for-method-chaining-y, so I think the manual is correct and the implementation is a bug. Not a very high-priority bug, but probably relatively easy to fix.

Here's a sample app that illustrates:

``` ruby
Shoes.app do
  sw = strokewidth(4)
  para sw
  line 0, 50, 500, 50
end
```

The line gets the strokewidth, but the para says `(Shoes)`

**Comment by steveklabnik** [comment]
+1 bug, yeah. Yay for @_why and weird edge cases!

**Comment by wasnotrice** [comment]
I'm telling you, specifying the interface for brown shoes is going to uncover a lot :)

**Comment by steveklabnik** [comment]
Absolutely. :D

**Comment by wasnotrice** [comment]
Wait a minute! Now, I was looking at the wrong method. So the manual actually does say that `strokewidth` on the app returns self. However (and this is what I was looking at), `strokewidth` on an element returns the number, which is consistent with the rest of the element methods.

So...there is not a bug, exactly. And there's no need to return the value--you have it already since you just passed it in. Why is it different, I wonder?

I mean, there is a system to the built-in methods. There are just exceptions:
1. If the method creates an object, return the object (arc, arrow, line, oval, rect, shape, star)
2. If the method doesn't create an object, return self (cap, nofill, nostroke, rotate, strokewidth, transform, translate)
3. Unless the method is fill or stroke, in which case, return the fill or stroke

**Comment by steveklabnik** [comment]
Weird. Okay.

At least by _exposing_ these kinds of things, we can decide to clean them up later if they're not working. :)
