### ISSUE TITLE
Runtime Error on Windows 7

### ISSUE THREAD

**Issue by friedheim** [shoes/shoes-deprecated#205]
Error "Windows Visual C++ Runtime Library: This application has requested the Runtime to terminate it in an unusual way." I have installed Shoes 3 with video support, the newest version, downloaded yesterday, version 0.r1514. This error comes ofter some minutes using a shoes program, packaged and running without packaging.
The program I am running is very simple and always crashs after short time:

Shoes.app {
   flow do
      @nr1 = edit_line
      para "&"
      @nr2 = edit_line

```
end
flow do
    @plus = button "+"
    @minus = button "-"
    @mal = button "*"
    @durch = button "/"
end
@plus.click do
  @result.text = @nr1.text.to_f + @nr2.text.to_f
end
@minus.click do
    @result.text = @nr1.text.to_f - @nr2.text.to_f
end
@mal.click do
    @result.text = @nr1.text.to_f * @nr2.text.to_f
end
@durch.click do
    @result.text = @nr1.text.to_f / @nr2.text.to_f
end

@result = para ""
```

}

I know, that the error is very common, but I didn't find more special log information, but if you tell me, where I can find it, I will privide.

**Comment by steveklabnik** [comment]
Thanks! I'm not 100% sure where there'd be more logs, as my windows dev is really poor.

We're speculating that this has to do with ruby 1.9.1's terrible threads, and so we're hoping the move to 1.9.3 will fix it. Or using JRuby-based Brown Shoes...

**Comment by friedheim** [comment]
when will this move to 1.9.3 happen? Thanks

Am 21/05/2012 19:15, schrieb Steve Klabnik:

**Comment by steveklabnik** [comment]
Master builds with 1.9.3 on Mac and Linux. We're still trying to sort out Windows. We sorely lack expertise in this area, so if you know anything, let me know.... we're working hard, but it's a big job, and we're a small team...

**Comment by ccoupe** [comment]
You might have better luck with the no-video version (or not).  Ashbb has built a new shoes with 1.9.3 and he claims it works on Win 7.  Sadly, his r17xx version was announced on the mailing list and you'd have to search the ML to find it.

**Comment by ashbb** [comment]
Hi huettiemail,

> The program I am running is very simple and always crashs after short time:

Umm,... strange. I've been running the code you showed in the first post with Shoes 3 (0.r1514) on my Windows 7 laptop. But it is still working. It doesn't crash at least for ten minutes.

Look at [this](http://librelist.com/browser//shoes/2012/2/26/red-shoes-for-windows-with-ruby-1-9-3p125/#a391477c45fabfa46397780d0b75aaef). That is my [r1783](http://www.rin-shun.com/shoes/shoes-0.r1783.exe) version Cecil mentioned. 

Hope it helps,
ashbb

**Comment by steveklabnik** [comment]
Yeah, it seems to be about 30% of computers.

I've installed Hackety on about 50 identical Windows 7 notebooks, and about a third of them experience the crash. They're totally identical.

**Comment by friedheim** [comment]
I now tried the version without video support and it works fine, for what is this video version? I didn't find any advantage. Thanks for the help, so I will go on investigate shoes, for sure it seems very cool! Thanks!
