### ISSUE TITLE
Unable to run shoes on Fedora 17

### ISSUE THREAD

**Issue by blackheaven** [shoes/shoes-deprecated#206]
Hi, 

I followed the wiki to build shoes on my Fedora 17 and, when I try to launch it, I have the following instead of no error message are displayed during installation process :
  cannot load such file -- rubygems/specification

For your help,
By advance,
Thanks.

**Comment by steveklabnik** [comment]
What's you're `gem -v`?

**Comment by blackheaven** [comment]
Thank you for yuor answer.
$ gem -v
1.8.24

**Comment by steveklabnik** [comment]
Hmmm, strange. What about `ruby -v`?

**Comment by blackheaven** [comment]
$ ruby -v
ruby 1.9.3p194 (2012-04-20 revision 35410) [i386-linux]

Thank you for your help.

**Comment by steveklabnik** [comment]
Crazy! I assumed it was because Fedora tends to have really old stuff... but it seems you're up to date. I currently have no idea why this is happening.

**Comment by blackheaven** [comment]
I have installed fedora 17 to be compatible to shoes,
I'm cursed!

**Comment by jrgifford** [comment]
Interesting. Let me boot my Fedora 17 VM and take a look at this, i had Shoes working earlier on it. Something on rawhide must have changed over the past few weeks...

**Comment by blackheaven** [comment]
Thanks for yor help (do not forget to disable the updates-testing repository).

**Comment by blackheaven** [comment]
Have you got the same issue ?

For your help,
By advance,
Thanks.

**Comment by jrgifford** [comment]
I haven't been able to replicate. Works fine for me. 32 bit or 64?

**Comment by blackheaven** [comment]
32 bits.
Did you run the fedora installation process ?

**Comment by jrgifford** [comment]
Yes, I did run the fedora install process - however, i did run into a snafu. if you could try again based off the instructions [here](https://github.com/shoes/shoes/wiki/Building-Shoes-on-Linux) that'd be great. I've just tested on a clean install of 32 bit Fedora 17. Not sure why this is happening.

**Comment by JohnMurray** [comment]
I'm getting this same error on Fedora 17 (64-bit)

ruby version: **ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]**
gem version: **1.8.24**

exact error: **cannot load such file -- rubygems/specification**

I followed the instructions per your link. The only issue that I had is that **libpixman-devel** could not be found so I installed **pixman-devel** from the repos.

**Comment by JohnMurray** [comment]
I just wanted to check if there were any updates? I _hate_ to have to work on this on Windows...

**Comment by JohnMurray** [comment]
I noticed that there is a libruby.so within the dist folder. Is this used if you were to package up the application and ship it? Just curious but, I think that is where the errors are coming from.

I was able to get rid of the **cannot load such file -- rubygems/specification** by inserting the **rubygems** folder inside the RubyGems source [here](v1.8.24).

However, I was then presented with a new error:

``` bash
cannot load such file -- stringio
```

The problem is that stringio is a C file and I cannot simply drag and drop to fix... So, still working on that one, but making progress! Please let me know if you all have any ideas!

**Comment by JohnMurray** [comment]
**UPDATE**

Okay, so I was able to resolve all of the _load_ issues. I simply did the following:

``` bash
wget http://ftp.ruby-lang.org/pub/ruby/1.9/ruby-1.9.3-p194.tar.gz
tar -xzf ruby-1.9.3-p194.tar.gz
cd ruby-1.9.3-p194/
./configure --prefix=/tmp/ruby
make && make install
cp -R /tmp/ruby/lib/ruby/1.9.1/x86_64/* ${shoes_dir}/dist/ruby/lib
```

I got one message saying it wouldn't copy over a folder where there was a file with the same name (_IO_ I think) and I just ignored it for now.

Now, when I run `${shoes_dir}/dirst/shoes` I get the following errors:

``` bash
${shoes_dir}/dist/ruby/lib/rbconfig.rb:9: warning: already initialized constant TOPDIR             │                                                                                                       
${shoes_dir}/dist/ruby/lib/rbconfig.rb:11: warning: already initialized constant CONFIG            │                                                                                                       
${shoes_dir}/dist/ruby/lib/rbconfig.rb:202: warning: already initialized constant MAKEFILE_CONFIG  │                                                                                                       
element size differs (11 should be 10)
```

No frigg'n clue what to do now. Either way, there is no way this can be the correct installation process. There has to be something that is missing from the current installation instructions (as it applies to Fedora 17).

**Comment by jrgifford** [comment]
I'll look into this tomorrow. I wasn't able to replicate last time, maybe I'm missing something...

**Comment by JohnMurray** [comment]
If it helps, I had **_just**_ installed the Fedora (64-bit) instance and the only thing I had installed prior were Chrome, Vim, wget, and [Rust](http://rust-lang.org). So, at that point my install was pretty basic.

Also, I had to install **pixman-devel** instead of **libpixman-devel** since it couldn't be found. I'm assuming that these are, in fact, the same package with a slightly different name.

**Comment by freemanoid** [comment]
I can confirm this issue. Fedora 17, i386.

**Comment by freemanoid** [comment]
Hmm.. I just remove the folder with shoes and recompile it from the sources according to the offical guide and its ok.

**Comment by PragTob** [comment]
Happy to hear, but weird!

**Comment by JohnMurray** [comment]
hmm... @ouyoutouchmytralala  Can you elaborate further when you say `I just remove the folder with shoes and recompile it`

Do you mean to say that you just deleted the entire source directory and re-compiled from source? If so, that's not working for me... Or, do you mean that you removed the `shoes` folder inside of `#{shoes_dir}` and then re-compiled? I tried that as well and got `No such file or directory - shoes/version.h`

**Comment by jrgifford** [comment]
## I think he means he ran what is essentially "rake clean && rake"

James Gifford
cell: 2162238574

**Comment by blackheaven** [comment]
I moved to shoes 4.

**Comment by JohnMurray** [comment]
@blackheaven with the implication that it solved you issue I'm guessing (since you closed the ticket)?

**Comment by blackheaven** [comment]
Yes, it did.
