### ISSUE TITLE
Window's loses focus of keypress events when using buttons/edit_line

### ISSUE THREAD

**Issue by atomicules** [shoes/shoes-deprecated#21]
See the following:

1) Question on Stackoverflow: [Why is keypress not called after clicking on native controls?](http://stackoverflow.com/questions/594767/why-is-keypress-not-called-after-clicking-on-native-controls)

and 

2) thread on the GMane email archive of the old mailing list:  [<alt-/> for console. Not with an entry!](http://thread.gmane.org/gmane.comp.lib.shoes/1682)

These are likely related issues.

1) The example taken from the SO question:

```
Shoes.app do
    keypress do |k|
        if k==:f1
            alert("Foo bar")
        end
    end
    button "foo"
end
```

> Pressing F1 causes the alert box to pop up but. Once i click the button "foo" i.e. if the
> focus changes to a native control in the app. the keypress events are no longer captured

Note that if you can clear the app and redraw then you can get the keypress events back. The below code is a novelty fix for the problem code above:

```
Shoes.app do
    def drawbutton
        @holder.clear do
            button "foo" do
                drawbutton
            end
        end
    end

    @holder = stack 

    drawbutton

    keypress do |k|
        if k==:f1
            alert("Foo bar")
        end
    end
end
```

2) ALT + / should bring the Shoes console up, but it is easy to lose the ability, say by clicking in an edit_line. Again clear and redraw will bring the ability back. The below code is what Hugh Sasse put as demonstrating how to lock out the console:

```
Shoes.app do 
  stack do 
    para("Enter text, press button. <alt-/> won't work.")
    flow do
      @entry = edit_line
      @button = button("add_para") do
        para(@entry.text)
      end
    end
  end
end
```

**Comment by steveklabnik** [comment]
Can anyone test if this is still the case? Running the first example, if I hit F1, and then the button, and then F1 again, I get the alert twice.

**Comment by atomicules** [comment]
Steve,

I just checked with Shoes 3 (1514) on windows XP and the first example now works as intended. 

The second issue ("<alt-/> for console. Not with an entry!") is still a problem.

However, I think this can be closed out, although it would be nice to know exactly what fixed this rather than saying "ashbb's magic".

**Comment by steveklabnik** [comment]
Yeah, I'm going to re-file this as just the alt-/ thing here: https://github.com/shoes/shoes/issues/issue/69
