### ISSUE TITLE
Cannot run from source

### ISSUE THREAD

**Issue by ozpos** [shoes/shoes-deprecated#212]
Hi all,

I have successfully built and executed shoes in lubuntu 12.04 by following the Debian installation instructions but, how do you run shoes.rb ?

**Comment by steveklabnik** [comment]
The directory where you compiled it has a 'dist' directory. There's a shoes executable in there, so ./dist/shoes.

I'm going to close this since it isn't a bug, but if you still have problems, let's work them out!

**Comment by ozpos** [comment]
Hi thanks for the response. Yes I can execute ./dist/shoes but how can I execute shoes.rb directly with the ruby interpreter ?

P.S. sorry for the dup my browser did not refresh and show the created issue.

**Comment by steveklabnik** [comment]
I'm not sure what you're asking. You don't need to 'execute shoes.rb'.

Do you mean use shoes within your existing Ruby?

**Comment by ozpos** [comment]
Having forked and cloned shoes and built and tested for the command line vis. ./dist/shoes  I am now trying to execute from source using the RubyMine IDE.

Or run some thing like ruby shoes.rb form the command line.

**Comment by steveklabnik** [comment]
You use shoes via ./dist/shoes. You don't use it from the command line. You also can't use shoes inside of your existing Ruby. Shoes _is_ a custom Ruby.

When you run ./dist/shoes, it pops up a box, asking you to choose an app, right?

**Comment by ozpos** [comment]
Sure it does but I remember when I used the original shoes and it was possible to run shoes.rb with the interpreter and pass it a shoes example source file.

It must be possible to debug the shoes DSL as it interprets a shoes application source example script.

**Comment by ozpos** [comment]
I would expect to debug shoes in the same way I debug camping.

There I fork and clone and build the camping gem and execute camping passing it a camping app.  When I load the project into RubyMine and I single step I enter the camping.rb source and can see whats going on.

**Comment by steveklabnik** [comment]
> when I used the original shoes and it was possible to run shoes.rb with the interpreter and pass it a shoes example source file.

I haven't known about this ever working.... As far ask I know, you have to './dist/shoes my_shoes_app.rb'. Is that what you want? Of course, most people put dist on their $PATH, so they can just 'shoes my_shoes_app.rb'

**Comment by steveklabnik** [comment]
.. we haven't changed anything significant about how Shoes runs, so if you used to be able to do it, you can probably do it now. Know that when @_why was working on things, it went through a bunch of revisions, though. Where you using Raisins? (Shoes 2?) or Shoes 1?

**Comment by ozpos** [comment]
Thanks, yes I can run for example './dist/shoes samples/simple-form.rb' from a shell but this does not work from within the IDE like it does with a camping app.

Any ideas ?

**Comment by steveklabnik** [comment]
Ahh, I have no idea. I don't use IDEs.

@jrgifford, didn't you start using RubyMine?

**Comment by ozpos** [comment]
What would it take to be able to run 'ruby ./lib/shoes.rb samples/simple-form.rb' ?

**Comment by steveklabnik** [comment]
A lot. Shoes _is_ a Ruby interpreter, so running it inside another one doesn't make a lot of sense.

**Comment by ozpos** [comment]
Do'nt you mean a DSL ?

Surely the ruby interpreter must execute shoes.rb as it is ruby source code!

**Comment by steveklabnik** [comment]
Nope, literally an interpreter: https://github.com/shoes/shoes/blob/develop/bin/main.skel

Note https://github.com/shoes/shoes/blob/develop/bin/main.skel#L71

**Comment by ozpos** [comment]
Are you familiar with shoes4 ?

**Comment by steveklabnik** [comment]
Yes, we're doing a total re-write. It will be run-able from your normal interpreter.

**Comment by ozpos** [comment]
Many thanks I will concentrate my efforts there.

**Comment by jrgifford** [comment]
@steveklabnik Nope, I don't use rubymine. That's @PragTob.

**Comment by PragTob** [comment]
@jrgifford @steveklabnik Yep that's me but I'm still getting started with it. I'm using it for working on shoes4, when I write shoes apps I mostly use good old gedit and have a custome run command for shoes short-cutted, should be easy in RubyMine as well. Dunno how to just yet though :-)
