### ISSUE TITLE
can't paste in edit_line or edit_box (10.8)

### ISSUE THREAD

**Issue by kickback101** [shoes/shoes-deprecated#217]
Hey guys

I am unable to paste in editlines or editboxes using hotkeys on 10.8 when running scripts. I have to paste it manually using right click. It's very time-consuming. Is there any solution?

**Comment by ashbb** [comment]
Umm,... on Windows 7, `ctrl-v` is available in editlines or editboxes. Sorry, I can't confirm on Linux now. Hope someone Linux user will reply.

**Comment by kickback101** [comment]
sorry, forgot to mention i was running Mac OS X 10.8, manually pasting it in the editbox or editline works, but the hotkeys don't work, none of them: cmd-v, cmd-c, cmd-a all do nothing

**Comment by steveklabnik** [comment]
This is a duplicate of #52.

Still haven't figured out what is wrong. :/
