### ISSUE TITLE
Ruby "load" doesn't work

### ISSUE THREAD

**Issue by shideneyu** [shoes/shoes-deprecated#221]
Hi guys, after many tests I have found this issue, to simplify a bit:

--- a.rb

```
@a = "hello world !"
```

--- shoes.rb

```
Shoes.app :width => 750, :height => 550 do
  load 'a.rb'
  alert @a
end
```

It only displays an empty alert box.

On irb:

```
load 'a.rb'
=> true
puts @a
hello world!
=> nil
```

I was a bit puzzled, I'm new to shoes and I discovered this while programming.

**Comment by steveklabnik** [comment]
What does the shoes console say? I beat your path is wrong.

**Comment by shideneyu** [comment]
Thanks for your quick reply;
The shoes console doesn't got any output;
Here is my oh-my-zsh console's output (it is the same output whatever shoes app I run, so I don't think it's related)

```
/home/shideneyu/informatique/logiciels/shoes/dist/ruby/lib/x86_64-linux/rbconfig.rb:9: warning: already initialized constant TOPDIR
/home/shideneyu/informatique/logiciels/shoes/dist/ruby/lib/x86_64-linux/rbconfig.rb:11: warning: already initialized constant CONFIG
/home/shideneyu/informatique/logiciels/shoes/dist/ruby/lib/x86_64-linux/rbconfig.rb:202: warning: already initialized constant MAKEFILE_CONFIG
```

I checked and rechecked and the path is good

I'm running on rbenv and 1.9.3-p194

**Comment by steveklabnik** [comment]
I mean the shoes console, hit control-a or apple-a or command-a.

**Comment by shideneyu** [comment]
It is blank;
http://image.noelshack.com/fichiers/2012/40/1349105955-screenshot-2.png

I pressed alt - slash

I haven't succeed to make control-a work

I'm running on Fedora 17

**Comment by steveklabnik** [comment]
Alt-slash is it, sorry. I always remember keyboard shortcuts wrong; they
get in my muscle memory. :(

**Comment by shideneyu** [comment]
:D No worries; do you think it is because of my conf ? Or maybe I've done it wrong? I think we can reproduce this easily in order  to check

**Comment by steveklabnik** [comment]
I'm not sure, to be honest, I avoid `load` like the plague.

**Comment by shideneyu** [comment]
I'm surely not a good rubyist, however I need this in order to get a variable. I would like not to instantiate a new class each time I would like to get a variable to get a return of a system shell command.
In fact, in my 'a.rb', I assign my @a variable with the return of a shell command.
However it doesn't work even if I assign the @a variable with a simple string :(

**Comment by steveklabnik** [comment]
Try 'require', not load. You don't use the .rb with require.

**Comment by shideneyu** [comment]
I have studied the question and the differences between these two methods; I've tested it  a few secs ago and It doesn't work as well

On irb 'require' works

After having done some more testing 30 minutes ago, I have found that when setting a condition, Shoes return "true" when loading the file. But he doesn't like the passed variable since he doesn't retrieve it

So, both "load" and "require" are working, but they don't seem to give me back my variable

**Comment by steveklabnik** [comment]
Okay. well first of all, I need to read. Setting `@a` inside of your other file will NOT set it in this one, even if you load/require it. So your code would never work. Sorry.

Can you share your code with me in general?

**Comment by shideneyu** [comment]
https://github.com/shideneyu/sometests

Sorry I didn't understand if what you said is "your code will never work because you're doing it wrong", or if you just remembers what the facts are?

Yeah, I created this repository, it shows what the problem is.
Sorry I have to leave, I won't be able to reply till tommorrow.

Thanks

**Comment by steveklabnik** [comment]
> "your code will never work because you're doing it wrong"

Yes, this is what I mean.

I will check it out! Have a good evening. :)

**Comment by steveklabnik** [comment]
I've submitted a pull request.

Regardless, this isn't a bug in Shoes, so I'm closing the ticket.

**Comment by ashbb** [comment]
@shideneyu Try out the following. You will see 'hello world!'. ;-)

Solution 1

``` ruby
# a.rb
@a = 'hello world!'

# test.rb
Shoes.app do
  eval IO.read('a.rb')
  alert @a
end
```

Solution 2

``` ruby
# a.rb
$a = 'hello world!'

# test.rb
Shoes.app do
  load 'a.rb'
  alert $a
end
```

**Comment by shideneyu** [comment]
Wow thanks, it works as well
