### ISSUE TITLE
require 'json' on mac

### ISSUE THREAD

**Issue by yanguango** [shoes/shoes-deprecated#23]
On mac os x,require 'json' throw "no such file to load 'json/ext/parser'".On window there is no this problem.I don't know there are problems in my code or it's a shoes's bug.

**Comment by atomicules** [comment]
This seems like it can't find the gem. Have you done Shoes.setup to install the gem?

**Comment by yanguango** [comment]
in the irb，the json gem works well

**Comment by atomicules** [comment]
But in IRB, you will be using the OSX system Ruby. Shoes comes with it's own version of Ruby and must also have it's own Gems installed.

**Comment by yanguango** [comment]
oh,i really don.t know this point.But how can i use the Shoes's ruby and how to install the gem to Shoes's ruby?

**Comment by atomicules** [comment]
Try doing the following in your Shoes application:

```
Shoes.setup do
    gem 'json'
end
require 'rubygems'
require 'json'
Shoes.app do
     #Your applicaton
end
```

**Comment by atomicules** [comment]
Also, for this particular gem (json), this issue can be considered closed for Shoes Policeman since it is now included with Shoes.

**Comment by steveklabnik** [comment]
Closing, json included with policeman.
