### ISSUE TITLE
Quantal dependency issue

### ISSUE THREAD

**Issue by mikedanese** [shoes/shoes-deprecated#231]
Nothing with Shoes, but there seems to be a dependency issue in the apt-get repo for Ubuntu 12.10. Following the instructions on the wiki, one of the packages required for the build from source `portaudio19-dev` requires an older version of `libjack` than what is shipped. Adding `libjack0` to that `apt-get install` list will fix the dependency issue allowing `portaudio19-dev` to install but this will remove newer versions of `libjack`. This could break dependent programs elsewhere on the system or cause Shoes to break if a package is installed later on requiring the newer `libjack`.

I would suggest looking in to upgrading from `portaudio19-dev` to `libportaudio -dev` or `libportaudio2-dev`.

**Comment by PragTob** [comment]
Thanks for the info, let's see what our main Ubuntu man @jrgifford says about that.

However, for upgrading libs I wouldn't give you too much hope - the team is mainly working on Shoes4 these days.

**Comment by jrgifford** [comment]
eek. this is confusing. i'll look into this and get back to you.

**Comment by mikedanese** [comment]
Great. More of an inconvenience than a problem but I thought I would go ahead and post the issue, and maybe it would help someone out later on. Looking forward to Shoes 4! Thanks for the hard work!
