### ISSUE TITLE
Failed to build gem native extension

### ISSUE THREAD

**Issue by veered** [shoes/shoes-deprecated#234]
I am trying to use curb (https://github.com/taf2/curb) in a shoes app (https://gist.github.com/Veered/5032155). When I load the app into shoes I get this error http://imgur.com/ULWGBCM. I am running OSX 10.8.2 and installed Shoes using the binary provided at http://shoesrb.com/downloads

For debugging purposes I tried compiling shoes and was met with something like 300 errors that I couldn't figure out how to get rid of. So hopefully there is a solution that doesn't require me to deal with that steaming pile of ughh.

P.S. How do you copy things from the Shoes console?

**Comment by steveklabnik** [comment]
If you want to use gems with C extensions, you need to build a custom Shoes with the gem embedded in it. I'm embarrassed to report that there's no documentation on how to do this. :/

shoes/shoes development is frozen as we work on Shoes 4, which is located at shoes/shoes4. You might want to give it a try.

**Comment by veered** [comment]
Hmm... ok thanks. Can shoes4 deal with native extensions?

**Comment by wasnotrice** [comment]
The current backend runs on jruby, so no extensions. There are [alternatives](https://github.com/jruby/jruby/wiki/C-Extension-Alternatives) though. When we get an MRI backend using Qt or Cairo/Pango, then extensions ought to work.
