### ISSUE TITLE
build and run/debug - ubuntu 12.04

### ISSUE THREAD

**Issue by ozpos** [shoes/shoes-deprecated#238]
Hi all,
The project builds but I cannot run or debug it.
Using:- 
    Rubymine 5.4.1
    rvm
    ruby-1.9.3-p392
From the command line:-
    no such file to load -- rubygems
From within the IDE:-
    require 'shoes/inspect' 
    errors with uninitialised constant 'Shoes'

Any help would be welcome.
John

**Comment by steveklabnik** [comment]
Bummer.

I'd suggest using Shoes 4 or Green Shoes in the meantime.

**Comment by ozpos** [comment]
Hi, I am already using Green Shoes and Shoes 4.  I could do with Shoes 3 
in order to check out the behaviour of the original dsl.
What about a binary for ubuntu 12.04 ?
Have one ?
Can you build one ?
John

**Comment by PragTob** [comment]
Linux binaries have been hard... I dont't think we got any. @jrgifford ?

I use a Debian based Linux (Mint) and my build succeeds, no idea where that no rubygems error comes from.. have you tried following the build guides for both Ubuntu and debian step by step?

**Comment by ozpos** [comment]
Yes, why are they so hard ?
I would have thought windose should be the difficult one!

**Comment by PragTob** [comment]
Oh well... I dunno why they are sooo hard, I'd say fragmentation but am not sure...  haven't worked on making that happen. Just know that what we offer as an install atm doesnt work and there are reasons why the fix isn't easy.

I'd love to get my hands on one of those machines where the rubygems doesn't work... I think when it failed for me once I did a clean checkout or rake clean && rake

**Comment by ozpos** [comment]
Thank you for your honesty.  Also bin there and done that clean thing 
more than once.  Maybe I should dust off an M$ disk ?

**Comment by PragTob** [comment]
Right now I can't really guarantee for shoes3 to work anywhere, sadly. That's why the work on shoes3 is so important. It's worth a try.

I just don't get the errors people are getting cause for me they are not there so I got now way to help people, worst kind of problems :-(

**Comment by ozpos** [comment]
Do you have a ubuntu 12.04 platform ?

**Comment by steveklabnik** [comment]
They're hard because of the way that _why originally decided to package them, a .run file. Also, 'so hell' with runtime dependencies.

The last known good binary was built and uploaded here: https://github.com/shoes/shoes/downloads

**Comment by PragTob** [comment]
I got Linux Mint Debian Edition based upon Debian and Ubuntu is also based on Debian so its close. However I had a Linux Mint which was based upon Ubuntu 12.04 until last summer and building shoes worked there (had to use the Debian instructions though).

**Comment by ozpos** [comment]
I cannot find the Debian install instructions.  I do'nt suppose you have 
a link ?

**Comment by steveklabnik** [comment]
https://github.com/shoes/shoes/wiki/Building-Shoes-on-Linux#building-on-debian

**Comment by ozpos** [comment]
Sorry fatigue must be setting in.

**Comment by ozpos** [comment]
So it built without problems.
john@john-lenovo:~/RubyMineProjects/Shoes/shoes #results in:-
no such file to load -- rubygems
john@john-lenovo:~/RubyMineProjects/Shoes/shoes3.1$ ./dist/shoes 
#results in:-
internal:gem_prelude:1:in `require': cannot load such file -- 
rubygems.rb (LoadError)
     from <internal:gem_prelude>:1:in`<compiled>'
uninitialized constant Encoding::UTF_7

Any thing to go on ?

**Comment by steveklabnik** [comment]
:/

That's the dreaded error that made me stop working on Red Shoes.

**Comment by plexus** [comment]
That sucks :/

I googled the error anyway and it seems someone managed to get around it
(specifically for Shoes)
http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-talk/382744 . I
suppose you've seen that already but thought I'd mention anyway.

I managed to compile and run on Ubuntu 13.04 though. I only came across
some minor issues, I added notes to the wiki.

**Comment by ozpos** [comment]
Followed that to the letter and the same UTF_7 error persists even 
though I have removed the line.

**Comment by ozpos** [comment]
I am getting really close. What the f is going on!

**Comment by plexus** [comment]
I might have a binary built on 12.04 on another laptop, will check tomorrow
if you're interested.

**Comment by jrgifford** [comment]
@PragTob is right. i've spent way too many hours of my life trying to get shoes to compile on the various Linux boxes I've got.

Doing a cross-distro build is almost entirely out of the question, I tried. Hard. And since we're doing shoes 4 soon, we won't have to deal with this, we'll just create RPMs and .deb's that installs jruby, then installs the gem, then is done. :P

**Comment by ozpos** [comment]
Yes, please put me out of my misery.

**Comment by plexus** [comment]
Sorry, seems I was mistaken. It's actually 12.10. But maybe try it anyway.
These are archives of the dist/ directory after building red shoes on
ubuntu 12.10 and 13.04.

http://arnebrasseur.net/red_shoes_ubuntu_12.10.tar.bz2
http://arnebrasseur.net/red_shoes_ubuntu_13.04.tar.bz2

**Comment by plexus** [comment]
Uploaded a version for 12.04 as well :

http://arnebrasseur.net/red_shoes_ubuntu_12.04.tar.bz2

And I turned my method of doing it in a bash script. It installs
ruby-build, chruby, shoes and ruby-1.9.3-p392 all under /tmp/shoes_build,
so it's relatively isolated.

https://gist.github.com/arnebrasseur/4194d8c47e9493019e04

**Comment by PragTob** [comment]
if this works out for @ozpos could you please link it in the wiki as help for the others @arnebrasseur ? And thanks for your work!!! :-D

**Comment by plexus** [comment]
Already added it to the wiki as an alternative. There's one thing that
bothers me about it though. I'm setting up a symlink to the systems
libruby-1.9.1.so. This is very ugly and I'm surprised it even works. i
wouldn't be surprised to see random crashes with this approach.

It seems ruby-build links ruby statically so there's no shared object file.
If anyone knows anything about that please shout... I hope to figure out
how to get ruby-build to produce the libruby-*.so...

**Comment by ozpos** [comment]
Hi Arne,
Thank you very much it works a treat.  While waiting for responses from 
shoes4 team I fixed margins in green_shoes, check it out !
John

**Comment by ozpos** [comment]
It works !!!
@ozpos

**Comment by steveklabnik** [comment]
Wooo!

**Comment by wasnotrice** [comment]
Thanks @arnebrasseur !!!

**Comment by PragTob** [comment]
:+1: for @arnebrasseur !!!!

**Comment by plexus** [comment]
:blushes:
