### ISSUE TITLE
Shoesrb website is down.. Is there Alternate way to access docs?

### ISSUE THREAD

**Issue by ghost** [shoes/shoes-deprecated#239]

**Comment by steveklabnik** [comment]
It's not down for me.

See shoes/shoesrb.com for the source, you can see them there. They're also in this repo, I'm on my phone, but I think in docs or static.

**Comment by steveklabnik** [comment]
Oh, and command or control m should bring up the manual inside of shoes.

**Comment by PragTob** [comment]
I believe what he means is that [the manual](http://shoesrb.com/walkthrough) is down/not accessible.

And that's the case for me as well, probably connected to the move to github pages. Will open an issue in the web repo as well. And invent a new urgent tag.

**Comment by ghost** [comment]
Should i open this issue in this repo https://github.com/shoes/shoesrb.com ??

**Comment by PragTob** [comment]
I already did: shoes/shoesrb.com#32 .

Thanks for reporting it, I will leave it open around here since this probably is the place people would check first (like you did ;-) ).

**Comment by steveklabnik** [comment]
Ah! Sorry, about that.

**Comment by PragTob** [comment]
All fixed and should not be any problem anymore.
