### ISSUE TITLE
Tab order reversed on Windows

### ISSUE THREAD

**Issue by csomay** [shoes/shoes-deprecated#24]
```
Shoes.app do
  stack do
    edit_line
    edit_line
    button "One"
    button "Two"
  end
end
```

On Windows, the Tab order is Button2->Button1->edit line2->edit line1 instead of edit line1->edit line2->Button1->Button2
I used the r1377 version from here on windows: http://www.rin-shun.com/shoes/
On linux, I built the latest from this repo (r1312).

**Comment by ashbb** [comment]
Hi csomay,

At last, fixed this issue. Please confirm with Shoes-0.r1420. Download from [here](http://shoes.heroku.com/downloads).

Regards,  
ashbb

**Comment by atomicules** [comment]
Too clever, by half. Great work ashbb.

**Comment by csomay** [comment]
Works perfectly now, thank you!

One minor bug remains, but it might be a shortcoming of Windows:
After starting the example in the OP, pressing Shift-Tab goes to
edit line1->Button1->edit line2->edit line1->Button2 instead of
Button2->Button1->edit line2->edit line1->Button2

**Comment by ashbb** [comment]
csomay,

Thank you for confirmation!  
Yes, I followed the behavior of Raisins (Shoes-0.r1134) for Windows.  
In Raisins for Windows, at first need to press `tab` to focus on top of elements (edit line1 in this case), `shift-tab` is not available. So, I decided to focus on top of elements with first `tab` or `shift-tab`.

But now, I realized that your suggestion was the same behavior as Policeman for Linux (Shoes-0.r1419). So, I changed the spec as same as Linux. ;-)

Please confirm again with [Shoes-0.r1421](http://shoes.heroku.com/downloads).

**Comment by csomay** [comment]
This is perfect. Thank you very much!

**Comment by steveklabnik** [comment]
Closed due to working. :)
