### ISSUE TITLE
Download links are broken on the website

### ISSUE THREAD

**Issue by BillNace** [shoes/shoes-deprecated#240]
http://shoesrb.com/downloads/shoes-3.1.0.run
and
http://shoesrb.com/downloads/shoes-3.1.0.dmg

give 404 errors.

(Probably the windows download as well)

**Comment by PragTob** [comment]
Hi there,

thanks for reporting! This is a known issue over at shoes/shoesrb.com#27 and related to our move to github pages.

Sorry for the inconvenience :-(

**Comment by PragTob** [comment]
Ah I fixed that. Sorry!
