### ISSUE TITLE
Compile fails on Linux Ruby 2.0.0

### ISSUE THREAD

**Issue by nofxx** [shoes/shoes-deprecated#246]
``` code
...
hpricot_css.c: In function ‘hpricot_css’:
hpricot_css.c:3399:9: warning: comparison between pointer and integer [enabled by default]
  if ( p == eof )
         ^
linking shared-object hpricot_scan.so
creating Makefile
compiling unicode.c
compiling generator.c
generator.c:11:18: warning: extra tokens at end of #ifndef directive [enabled by default]
 #ifndef RHASH_TBL(h)
                  ^
linking shared-object generator.so
creating Makefile
compiling unicode.c
compiling parser.c
parser.rl:9:18: warning: extra tokens at end of #ifndef directive [enabled by default]
In file included from /usr/include/ruby-2.0.0/ruby.h:33:0,
                 from parser.rl:1:
parser.rl: In function ‘JSON_parse_object’:
/usr/include/ruby-2.0.0/ruby/ruby.h:445:18: error: expected ‘(’ before ‘!’ token
 #define RTEST(v) !(((VALUE)(v) & ~Qnil) == 0)
                  ^
parser.rl:118:20: note: in expansion of macro ‘RTEST’
/usr/include/ruby-2.0.0/ruby/ruby.h:445:18: warning: value computed is not used [-Wunused-value]
 #define RTEST(v) !(((VALUE)(v) & ~Qnil) == 0)
                  ^
parser.rl:118:20: note: in expansion of macro ‘RTEST’
parser.rl:118:68: error: expected ‘;’ before ‘{’ token
make: *** [parser.o] Error 1
rake aborted!
Extension build failed
/tmp/yaourt-tmp-nofxx/aur-shoes-git/src/shoes/make/linux/tasks.rb:12:in `block in copy_ext'
/tmp/yaourt-tmp-nofxx/aur-shoes-git/src/shoes/make/linux/tasks.rb:10:in `chdir'
/tmp/yaourt-tmp-nofxx/aur-shoes-git/src/shoes/make/linux/tasks.rb:10:in `copy_ext'
/tmp/yaourt-tmp-nofxx/aur-shoes-git/src/shoes/make/make.rb:76:in `block (2 levels) in common_build'
/tmp/yaourt-tmp-nofxx/aur-shoes-git/src/shoes/make/make.rb:76:in `block in common_build'
/tmp/yaourt-tmp-nofxx/aur-shoes-git/src/shoes/make/make.rb:70:in `each'
/tmp/yaourt-tmp-nofxx/aur-shoes-git/src/shoes/make/make.rb:70:in `common_build'
/tmp/yaourt-tmp-nofxx/aur-shoes-git/src/shoes/Rakefile:201:in `block in <top (required)>'
```

In file included from /usr/include/ruby-2.0.0/ruby.h:33:0 , looks like some GTK issue?
GCC 4.8.1

**Comment by jrgifford** [comment]
no clue what is the problem, other than that 1.9.2 > 1.9.3 went fine.

i think at this point we've got the codebase on hold, since we have
shoes/shoes4 in the making, using jruby.

## 

James Gifford
cell: 2162238574
Snowy Penguin Solutions, LLC | http://snowypenguinsolutions.com

**Comment by PragTob** [comment]
hpricot is deprecated either way :-) I didn't try compiling it with ruby 2.0 yet... did you try to compile it with 1.9.3 and did it work? Just to make sure that it is a problem with 2.0 and not another problem :-)

**Comment by nofxx** [comment]
I taught it was hpricot too, but hpricot compiles fine on 2.0.0.
Will try to compile on 1.9.3, but I'm 99% it will work, installed before lot of times.

**Comment by steveklabnik** [comment]
I recently compiled on Linux no problems, Debian.

**Comment by Jmlevick** [comment]
+1, Shoes won't compile when using ruby 2.0.0 but it will do with 1.9.3, How can we add support to 2.0.0 version? Also, bundling with "bundler --pre" version results in a execution bug, it needs bundler 1.3.x to build successfully.

**Comment by PragTob** [comment]
We won't add support for 2.0. Currently we are working on [shoes4](https://github.com/shoes/shoes4) which is the upcoming version and a complete rewrite. It's in pre alpha but only < 10 issues remaining for the alpha mile stone. However as JRuby updates it will also support Ruby 2.0 features.

**Comment by PragTob** [comment]
@nofxx shoes 3.2 has ruby 2 support in the meantime :)

**Comment by nofxx** [comment]
@PragTob ah, good to know man. Thank you.
