### ISSUE TITLE
Copy() in Shoes

### ISSUE THREAD

**Issue by xslackx** [shoes/shoes-deprecated#250]
Hello guys, I'm doing a project,
there is a button called script
it has the function to copy the text written in edit_line.

But I can not ..
this is a part of the code ..

def data

para "SERVICE DESK ************\* *********\* \ n"
para "User name (a): #{@n.text} \ n"
para "Testing conducted by educat / user: #{@t.text} \ n"
para "There was refusing to perform procedures? #{@r.text} \ n"
para "Completing the analysis: #{@co.text} \ n"
para "Aware of Backup: #{@ci.text} \ n"
para "Opening hours: #{@h.text} \ n"
para "Contact #{@co.text} \ n"
para "***********************************\* \ n"
end

flow do

@script = button "Script"
@script.click do
clipboard = data
end

But do not copy, just pass the data def, down the window.
I've tried \ cx
the same thing happens

I appreciate if you can help me!

**Comment by PragTob** [comment]
Hi there,

I don't see an edit_line there in your code. Do you want to copy all the text that your put into all the different paras?

Cheers,
Tobi

**Comment by xslackx** [comment]
There is only one part of the code,
example: fill several edit_line, made ​​a button called copy, which copies studies it was written in all edit_line, open a notepad and neck with CTRL + V

**Comment by PragTob** [comment]
I was asking because you were mentioning edit_line.

It seems like you want to assign the value of the clipboard to the return value of the data value. I take it you expect that to be the all the strings in there e.g.  `"SERVICE DESK ************* ********** \ n (...) Completing the analysis: #{@co.text} \ n (...)"` ?

Sorry that's not how it works, para just writes the string on the app and returns a para object, each of them an own para object. What you could do is create an array and put all the strings in there (one for each para) and then return that data. This could look like this:

``` ruby
def data
  my_data = []
  my_data << "SERVICE DESK ************* ********** \ n"
  # ...

  my_data << "Contact #{@co.text} \ n"
  my_data << "************************************ \ n"
  my_data.each do |string| para string end
  my_data.join # makes it into a string again
end
```

Hope that helps.

**Comment by xslackx** [comment]
But still the question is, it still does not copy, it happens

http://uploaddeimagens.com.br/imagens/aa-png--24

and when I try to paste elsewhere without success
it pastes the date below

**Comment by ashbb** [comment]
@xslackx Try out the following snippet. :)

``` ruby
Shoes.app do
  stack do
    user_name = "User name (a): "
    para user_name
    @n = edit_line
    button "Script" do
      self.clipboard = user_name + @n.text
    end
  end
end
```

**Comment by xslackx** [comment]
Yes, yes, yes.
So even if I was looking, I tried all ways and was not able to, thank you that helped me, now I help several others to optimize the work we do helping people with computers from schools in São Paulo

**Comment by ashbb** [comment]
> now I help several others to optimize the work we do helping people with computers from schools in São Paulo

Wow, fantastic! Glad to hear that. Have fun with Shoes! :-D

**Comment by xslackx** [comment]
Thanks for the tips, see the end result!
Ruby Shoes = Fun

http://uploaddeimagens.com.br/imagens/final-png--9

**Comment by PragTob** [comment]
Looks cool :+1: !

I take it we can close this one here then :-)
