### ISSUE TITLE
error installing shoes

### ISSUE THREAD

**Issue by pdipietro** [shoes/shoes-deprecated#254]
Hi all,
I just downloaded shoes on a fresh linux ubuntu 13.10 installation.
When running shoes-3.1.0.run it returns ...

pdipietro@ubuntu:~/Downloads$ sudo bash shoes-3.1.0.run
Verifying archive integrity... All good.
Uncompressing Shoes.......................................................................................................................................................................................................................................................................................................
shoes-3.1.0.run: line 391: ./shoes: No such file or directory

The file is corrupted at line 391: it seems not to correctly convert unicodes.

Any suggestion?
By the way, any experience about using shoes with neo4j?

TIA
Paolo

**Comment by PragTob** [comment]
Hi there,

the downloadable .run file sadly does not work on current distributions. For now the only thing, that I can recommend you is [compiling yourself](https://github.com/shoes/shoes/wiki/Building-Shoes-on-Linux).

We are working hard on shoes4 to replace the old shoes but it's not quite ready yet.

No experience using shoes with neo4j but it's just ruby and I saw at least one talk about neo4j and Ruby :-)

Cheers,
Tobi

**Comment by pdipietro** [comment]
Hi Tobi,

I just downloaded and installed Shoes4 on an Ubuntu 13.10 machine.

When running, I got the following error:

Any idea?

TIA
Paolo

pdipietro@ubuntu:~/shoes4$ bin/ruby-shoes samples/simple-sound.rb
LoadError: Couldn't load backend Shoes::Swt'. Error: no such file to 
load -- swt
org/jruby/RubyKernel.java:1084:in `require'
/home/pdipietro/.rvm/rubies/jruby-1.7.8/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55:in 
`require'
/home/pdipietro/.rvm/rubies/jruby-1.7.8/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53:in 
`require'
/home/pdipietro/shoes4/lib/shoes/swt.rb:2:in`(root)'
org/jruby/RubyKernel.java:1084:in `require'
/home/pdipietro/.rvm/rubies/jruby-1.7.8/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55:in 
`require'
/home/pdipietro/.rvm/rubies/jruby-1.7.8/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53:in 
`require'
/home/pdipietro/shoes4/lib/shoes.rb:1:in`(root)'
/home/pdipietro/shoes4/lib/shoes.rb:46:in `load_backend'
/home/pdipietro/shoes4/lib/shoes/configuration.rb:10:in`backend'
/home/pdipietro/shoes4/lib/shoes/app.rb:41:in `initialize'
/home/pdipietro/shoes4/lib/shoes/app.rb:15:in`app'
org/jruby/RubyKernel.java:1103:in `load'
/home/pdipietro/shoes4/samples/simple-sound.rb:1:in`(root)'
/home/pdipietro/shoes4/lib/shoes/cli.rb:1:in `(root)'
bin/ruby-shoes:6:in`(root)'
   load_backend at /home/pdipietro/shoes4/lib/shoes.rb:49
        backend at /home/pdipietro/shoes4/lib/shoes/configuration.rb:10
     initialize at /home/pdipietro/shoes4/lib/shoes/app.rb:41
            app at /home/pdipietro/shoes4/lib/shoes/app.rb:15
         (root) at /home/pdipietro/shoes4/samples/simple-sound.rb:1
           load at org/jruby/RubyKernel.java:1103
         (root) at /home/pdipietro/shoes4/lib/shoes/cli.rb:1
    execute_app at /home/pdipietro/shoes4/lib/shoes/cli.rb:73
         (root) at bin/ruby-shoes:6
pdipietro@ubuntu:~/shoes4$ jruby --version
jruby 1.7.8 (1.9.3p392) 2013-11-14 0ce429e on Java HotSpot(TM) 64-Bit 
Server VM 1.7.0_45-b18 [linux-amd64]

Il 25/11/2013 18:15, Tobias Pfeiffer ha scritto:

**Comment by PragTob** [comment]
Hmm strange, it seems like the 'swt' gem is not installed. Is it listed in `gem list` - it should be installed by bundler.

**Comment by pdipietro** [comment]
swt (0.18) already appears in the gem list.

Il 25/11/2013 23:39, Tobias Pfeiffer ha scritto:

**Comment by pdipietro** [comment]
Well, now it runs after restarting the shell. Thank you. Paolo

Il 25/11/2013 23:39, Tobias Pfeiffer ha scritto:

**Comment by PragTob** [comment]
Okay that's weird behavior... :-(

**Comment by PragTob** [comment]
I'll close this issue here as we got enough other open won't install issues and there is now a shoes4 running there :-)
