### ISSUE TITLE
Remove weird GUI opener and allow running from command line

### ISSUE THREAD

**Issue by JosephShering** [shoes/shoes-deprecated#259]
I feel that the special GUI program that can open *.rb files really breaks my workflow. I'd much prefer the ability to run the gui from command line like this: `shoes main.rb`

**Comment by PragTob** [comment]
Hi there @JosephShering - you should totally be able to do that.

Haven't used an official shoes install for a while but if you compiled it for yourself (at linux) you'll find the appropriate binary at `#{your_shoes_directory}/dist/shoes` - that's what I always use. Feel free to include it in your $PATH.

**Comment by ccoupe** [comment]
Try the -h switch from the command line to get some other options too.

**Comment by PragTob** [comment]
Closing this since it's already there and no followup question. @JosephShering if you need help please comment again/reopen!
