### ISSUE TITLE
keypress ignores deadkeys

### ISSUE THREAD

**Issue by fela** [shoes/shoes-deprecated#26]
I'm using policeman on Linux. Deadkeys (as when using the us_intl[1] character layout) are ignored by `keypress` (it behaves as if they aren't pressed at all...).

fn1. http://en.wikipedia.org/wiki/Keyboard_layout#US-International

**Comment by ashbb** [comment]
Hi Fela,

Thank you for the post. :)

But Policeman doesn't support Deadkeys so far, sorry...

Now on Linux, right-alt/-ctl/-shift keys are not available.  
On Windows, they are available, but just do the same behavior as left-alt/-ctl/-shift keys.  
On OSX, I'm not sure but I guess the same as Linux.

We'll add `Deadkeys support` into ToDo list. ;-)

Regards,  
ashbb

**Comment by steveklabnik** [comment]
I'm closing all feature request Issues, in favor of moving them to the wiki instead. This'll make it easier to lay them out into planning for future releases. Please see [here](https://github.com/shoes/shoes/wiki/Shoes-roadmap). Thanks!

**Comment by steveklabnik** [comment]
I'm closing all feature request Issues, in favor of moving them to the wiki instead. This'll make it easier to lay them out into planning for future releases. Please see [here](https://github.com/shoes/shoes/wiki/Shoes-roadmap). Thanks!
