### ISSUE TITLE
How to choose a different display

### ISSUE THREAD

**Issue by joseairosa** [shoes/shoes-deprecated#260]
Hello,

I'm running shoes in my raspberrypi which has a PiTFT attached onto it.

Because I'm running the terminal form a SSH connection I get `(shoes-bin:4487): Gtk-WARNING **: cannot open display:`.

My display resides in `/dev/fb1/`. How can I run shoes in that selected display?

Thank you.

**Comment by ccoupe** [comment]
This more of an X11/Linux issue and not really one Shoes can solve since we just use Gtk2 and X11 like every graphical app on Linux. You need to get X11 running on your /dev/fb1 device.  The pi forums are probably a better place to find hints.

**Comment by joseairosa** [comment]
@ccoupe Thank you for your help. I'll try and see if I can find help for that at the forums.

**Comment by ccoupe** [comment]
I have a pi but I use a hdmi monitor and it's own keyboard. Shoes works in that situation. I vaguely remember reading somewhere about the PiTFT and X11.

**Comment by joseairosa** [comment]
Thanks @ccoupe. Can you run it from command line or do you need to have run `startx` before?

**Comment by ccoupe** [comment]
It has to be run after startx. either from a LXDE terminal or from a LXDE menu entry.  Shoes requires all the graphics libraries on the pi be available and running before it starts. X11 can be confusing and very flexible after some experience.
