### ISSUE TITLE
Can't extend class

### ISSUE THREAD

**Issue by ghost** [shoes/shoes-deprecated#27]
On Policeman
Code:

<pre><code>class Shoes::Para
  def foo
     "i am foo"
  end
end
p = para
p.foo #=> undefinied method 'foo' for (Shoes::Para):Shoes::Para
</code></pre>

**Comment by ashbb** [comment]
Yeah, that's a bug. But it's difficult to fix so far.
So, please use alternative ways:

```
class Shoes::Types::Para
  def foo
     "i am foo"
  end
end

Shoes::Para.class_eval do
  def bar
    "i am bar"
  end
end

Shoes.app do
  p = para
  para p.foo
  para p.bar
end
```

You can see the output: `i am foo i am bar` on the Shoes window.

**Comment by steveklabnik** [comment]
I'm going to close this as a 'wontfix', basically. You can still accomplish this with a workaround, and once we go to Shoes 4, this will no longer be an issue.
