### ISSUE TITLE
The thing still exists in 10.10.5!

### ISSUE THREAD

**Issue by Tjarko-Holtjer** [shoes/shoes-deprecated#276]
Is there any open-source that checks whether the assertion can be done... #Apple ?
Now with rooksd and even system preferences which cannot read the internet preferences from time to time... I am lucky that half of that preferences is in the mail, but #MicrosoftOutlook2011 is more stable than #AppleMail.

**Comment by ccoupe** [comment]
Huh? Did you enter this in the wrong window?

**Comment by Tjarko-Holtjer** [comment]
Sorry Cecil, I think you are right, but I am a newbe on Github… Can you place it right, Please, and tell me how to in the future?

**Comment by ccoupe** [comment]
I can "close" it here but I can't move it to where ever you wanted to complain to. There are 1000's (perhaps 1000 x 10) of projects on github. I can only manage comments on 3 of them.  I'll close this issue which is all I can do for my little section of github You will have to find the github project that bothers you and re comment there.

**Comment by Tjarko-Holtjer** [comment]
Thank you for this; This must be redirected to IBM Trusteer services, but I ask them for their Github connection… Thank you for notifying me as well!
