### ISSUE TITLE
 Building on Ubuntu instruction fails for 14.04 LTS

### ISSUE THREAD

**Issue by matkoniecz** [shoes/shoes-deprecated#277]
https://github.com/shoes/shoes/wiki/Building-Shoes-on-Linux#building-on-ubuntu no longer works

> sudo apt-get install git libcairo2-dev libpixman-1-dev libpango1.0-dev libgif-dev libjpeg-dev libgtk2.0-dev vlc libvlc-dev portaudio19-dev libsqlite3-dev libcurl4-openssl-dev libxslt1-dev makeself curl libxslt-dev libxml2-dev libcurl4-openssl-dev libungif4-dev ruby1.9.1-full
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Note, selecting 'libxslt1-dev' instead of 'libxslt-dev'
> E: Unable to locate package libungif4-dev

**Comment by ccoupe** [comment]
You appear to be using Shoes 3.1 which is old and very out of date. Shoes 3.2 is up to date and even has binaries for Linux if you don't want to build from source.  Much of the 3.2 work was done on Ubuntu 14.04 so I know it works ;-) See https://github.com/Shoes3/shoes3/wiki/Building-Shoes-on-Linux if you want to build from source.

**Comment by matkoniecz** [comment]
Then it would be probably a good idea to replace link to https://gist.github.com/plexus/4194d8c47e9493019e04 with something that works.

**Comment by ccoupe** [comment]
I no idea who or what plexus is or does or why you think anyone here can update that page.

**Comment by matkoniecz** [comment]
Sorry, I just noticed that https://github.com/Shoes3/shoes3/wiki/Building-Shoes-on-Linux containing link to this page is fork of this project. Sorry for confusion.
