### ISSUE TITLE
Add Styles to text

### ISSUE THREAD

**Issue by Kavi6** [shoes/shoes-deprecated#284]
hi, 
how can i solve this issue?
getting lines from file and substitute some string in the line, with the same string, but with bold text

**Comment by PragTob** [comment]
Hi there,

I think what you are looking for is our styling methods, You can find text related methods [here](https://github.com/shoes/shoes4/blob/master/shoes-core/lib/shoes/dsl/text.rb) - so you can use `span` with various options or something like `strong`. Some documentation is [in the manual](http://shoesrb.com/manual/Element.html#span) - you can find [sample usage all across the samples](https://github.com/shoes/shoes/blob/d14b041d0be3d82bb6b6a19fe90883c94b9601cf/samples/simple-timer.rb).

**Comment by PragTob** [comment]
ah didn't see that this was the shoes repo and not the shoes4 repo, so some links go to shoes4 but the samples work in both, the manual is actually for shoes3 abut the implementation I linked to isn't that relevant then :)
