### ISSUE TITLE
Edit lines float magically above other things in GTK.

### ISSUE THREAD

**Issue by evanfarrar** [shoes/shoes-deprecated#3]
Edit lines float magically above other things in GTK. This can be very strange when the edit line is contained in a scrolling slot.

I tried this with 1247 and a few other builds of shoes, including raisins. All have the same problem. I am running ubuntu jaunty.

Check out this code which replicates my problem.

```
Shoes.app(:height => 500) do
  background red
  flow(:height => 200)
  flow(:height => 250) do
    background blue
    stack(:scroll => true, :height => 200) do
      50.times { edit_line; list_box; radio; }
    end
  end
end
```

**Comment by ashbb** [comment]
Delete list_box like this:

```
50.times { edit_line; radio; }
```

This issue can be solved.

I think this is a problem of list_box.

**Comment by steveklabnik** [comment]
> This issue can be solved.

Enough said.
