### ISSUE TITLE
Document making a standalone app

### ISSUE THREAD

**Issue by steveklabnik** [shoes/shoes-deprecated#31]
I've seen a few people on ruby-talk ask about making a standalone app, like Hackety. There's NO documentation about this. There should be.

**Comment by ashbb** [comment]
A tiny note is [here](http://github.com/ashbb/shoes_hack_note/blob/master/md/hack028.md). It's not a good documentation, though...

Hope this helps. :)

**Comment by steveklabnik** [comment]
It's true, it's a start. What I'd like to see is "here's what goes in app.yaml, and why" and if there's anything else in particular that needs to be around for the whole process to work.

**Comment by steveklabnik** [comment]
I'm closing all feature request Issues, in favor of moving them to the wiki instead. This'll make it easier to lay them out into planning for future releases. Please see [here](https://github.com/shoes/shoes/wiki/Shoes-roadmap). Thanks!
