### ISSUE TITLE
Shoes 3 Mac OS X Leopard dependency paths are wrong?

### ISSUE THREAD

**Issue by timcharper** [shoes/shoes-deprecated#32]
```
timcharper@timcharper:~/Downloads $ /Applications/Shoes.app/Contents/MacOS/shoes-launch 
dyld: Library not loaded: /tmp/dep/lib/libgthread-2.0.0.dylib
  Referenced from: /Applications/Shoes.app/Contents/MacOS/./shoes-bin
  Reason: image not found
/Applications/Shoes.app/Contents/MacOS/shoes-launch: line 7:  2665 Trace/BPT trap          DYLD_LIBRARY_PATH="$APPPATH" PANGO_RC_FILE="$APPPATH/pangorc" ./shoes-bin "$@"
timcharper@timcharper:~/Downloads $ /Applications/Shoes.app/Contents/MacOS/shoes-bin 
dyld: Library not loaded: /tmp/dep/lib/libgthread-2.0.0.dylib
  Referenced from: /Applications/Shoes.app/Contents/MacOS/shoes-bin
  Reason: image not found
Trace/BPT trap
```

**Comment by steveklabnik** [comment]
Hrm. This was similar to a bug that I had in the Snow Leopard build, and it got worked out... is this a build that you built, or is it the one on the Downloads page?

**Comment by steveklabnik** [comment]
Since I haven't heard from you in a while, I'm closing this issue. If you'd still like help building, please get in touch with me, or post to the shoes mailing list at shoes@librelist.com, and we'd be more than happy to try and work it out.

**Comment by timcharper** [comment]
Sorry... I missed your prior correspondance.  let me try to run the latest build.

**Comment by steveklabnik** [comment]
No worries!

It still might be broken. Please make sure that you're using the `develop` branch, as that's the absolute latest code.

I'd really love to get a working build, but I don't have a 10.5 machine. :/

**Comment by timcharper** [comment]
bummer, I have upgraded my machine to 10.6. It's probably about time that we all moved on? :-)

**Comment by steveklabnik** [comment]
Ha, I wish. The 10.6 build should work great for you, though!

**Comment by timcharper** [comment]
Yep, the 10.6 build works just great :-) thank you for the correspondence

**Comment by steveklabnik** [comment]
Excellent. Keep me posted if you have any other questions or anything. :D
