### ISSUE TITLE
Tray Icons

### ISSUE THREAD

**Issue by steveklabnik** [shoes/shoes-deprecated#33]
"MrZombie" over on Ruby-talk (I'll post a link as soon as it gets archived somewhere) suggested a feature where we'd make the ability for a Shoes app to make a tray icon.

**Comment by ashbb** [comment]
Oh suggestion, thanks.  
But sorry, I can't imagin the feature you suggest (want to add) to Shoes.  
What is Tray Icons? Could you explain your request a bit more detail?

**Comment by steveklabnik** [comment]
Like this: http://imgur.com/Uwk25

Or the ones on the bottom right on Windows.

**Comment by ashbb** [comment]
Umm... just looks like the area where places icons...  
If so, you can write your Shoes app with image method and :click option.  
I think it's not so difficult. What feature do you need?

**Comment by steveklabnik** [comment]
Like this: http://www.guidebookgallery.org/pics/gui/desktop/firstrun/winxppro-2-1.png

Where the bubble points to? With MSN messenger and the Tour?

I think we're just getting things confused.

**Comment by ccoupe** [comment]
Does the original poster want to trigger the notifications API's of the platforms? So shoes could pop up a notication (bubble, icon, what ever) in the systems dock, tray or system panel/menu bar.  I think there is some work going on to unify them cross platform but maybe thats a just a Linux dbus unification effort.  The api's exist.

**Comment by steveklabnik** [comment]
I'm closing all feature request Issues, in favor of moving them to the wiki instead. This'll make it easier to lay them out into planning for future releases. Please see [here](https://github.com/shoes/shoes/wiki/Shoes-roadmap). Thanks!
