### ISSUE TITLE
"Global Keypresses"

### ISSUE THREAD

**Issue by steveklabnik** [shoes/shoes-deprecated#34]
Like, "When someone hits alt-f5, bring my app to the front." kinds of things.

I'm assuming something in gtk lets you do something like this.

**Comment by ashbb** [comment]
How about using `Shoes.APPS`?  
This is a tiny sample snippet. Do you need another feature?

```
q = {}
%w[ashbb Steve Fela].each do |name|
  blk = lambda do
    q[self] = []
    keypress{|k| Shoes.APPS.each{|s| q[s] << k}}
    msg = para
    every{msg.replace q[self]}
  end
  Shoes.app title: name, width: 300, height: 300, &blk
end
```

**Comment by steveklabnik** [comment]
I'm closing all feature request Issues, in favor of moving them to the wiki instead. This'll make it easier to lay them out into planning for future releases. Please see [here](https://github.com/shoes/shoes/wiki/Shoes-roadmap). Thanks!
