### ISSUE TITLE
Can't build Shoes on 32-bit OSX Leopard

### ISSUE THREAD

**Issue by micahrj** [shoes/shoes-deprecated#35]
I was not able to compile the latest Shoes. After installing all (I think) the dependencies, then it complained that I did not have a 64-bit computer. So I edited the Rakefile to take out all the "-arch x86_64"s, but then it gave me a huge load of error messages, most of them syntax errors. Here they are:

(Now with Gist!)

http://gist.github.com/485170

**Comment by steveklabnik** [comment]
No worries about the long paste; but you can use http://gist.github.com to make it a bit easier. ;)

First things first: how did you install glib?

**Comment by micahrj** [comment]
I don't think I've ever explicitly installed glib, but brew says that it already has it installed, so it probably installed it for me when installing other stuff.

**Comment by steveklabnik** [comment]
hm. Okay.

See, when I build on Snow Leopard, I actually build 99% of the dependancies by hand... but, what it looks like here is that you don't have the glib development headers installed. I'm not sure how to do that with brew, it's glib2-devel on macports.

I'd try to get that going first.

**Comment by atomicules** [comment]
Micah, It might be worth just rolling back the Rakefile a bit. For instance, I can build all the latest code on 10.5 PPC, but I have to use [my branch of an older Rakefile](http://github.com/i5m/shoes/blob/osxppc/Rakefile). As of yet I just haven't had the time to look and see what breaks it for me in the newer Rakefile.

**Comment by steveklabnik** [comment]
Since I haven't heard from you in a while, I'm closing this issue. If you'd still like help building, please get in touch with me, or post to the shoes mailing list at shoes@librelist.com, and we'd be more than happy to try and work it out.
