### ISSUE TITLE
Shoes Policeman won't launch in OSX (10.6 and 10.5)

### ISSUE THREAD

**Issue by maca** [shoes/shoes-deprecated#36]
Hi, Shoes Policeman Mac OS X build won't lauch in none of my computers (10.6 and 10.5).

I get the following console messages:

7/21/10 3:05:41 PM [0x0-0x63063].org.hackety.shoes[1754] /Volumes/NO MAME/Curso Ruby/Hackety Hack/Shoes.app/Contents/MacOS/shoes-launch: line 7:  1755 Trace/BPT trap          DYLD_LIBRARY_PATH="$APPPATH" PANGO_RC_FILE="$APPPATH/pangorc" ./shoes-bin "$@" 

7/21/10 3:05:41 PM com.apple.launchd[171]([0x0-0x63063].org.hackety.shoes[1754]) Exited with exit code: 133 

7/21/10 3:08:25 PM [0x0-0x66066].org.hackety.shoes[1773] dyld: Library not loaded: /tmp/dep/lib/libgthread-2.0.0.dylib 

7/21/10 3:08:25 PM [0x0-0x66066].org.hackety.shoes[1773]   Referenced from: /Volumes/NO MAME/Curso Ruby/Hackety Hack/Shoes.app/Contents/MacOS/./shoes-bin

7/21/10 3:08:25 PM [0x0-0x66066].org.hackety.shoes[1773]   Reason: image not found 

7/21/10 3:08:25 PM ReportCrash[1775] Formulating crash report for process shoes-bin[1774] 

7/21/10 3:08:25 PM ReportCrash[1775] Saved crashreport to /Users/sistemasinteractivos/Library/Logs/CrashReporter/shoes-bin_2010-07-21-150825_macario-3.crash using uid: 501 gid: 20, euid: 501 egid: 20 

7/21/10 3:08:25 PM [0x0-0x66066].org.hackety.shoes[1773] /Volumes/NO MAME/Curso Ruby/Hackety Hack/Shoes.app/Contents/MacOS/shoes-launch: line 7:  1774 Trace/BPT trap          DYLD_LIBRARY_PATH="$APPPATH" PANGO_RC_FILE="$APPPATH/pangorc" ./shoes-bin "$@" 

Thanks
7/21/10 3:08:25 PM com.apple.launchd[171]([0x0-0x66066].org.hackety.shoes[1773]) Exited with exit code: 133

**Comment by steveklabnik** [comment]
Hey maca-

Which version of Shoes is this? Where did you grab it from?

**Comment by maca** [comment]
Hi, I've folled the link in the Hackety Hack site:
http://wiki.github.com/shoes/shoes/recentbuilds

It is Shoes 3

**Comment by steveklabnik** [comment]
Okay. So you used the 10.5 intel build?

**Comment by maca** [comment]
Well, I've been out of luck, I tried to run the 10.5 build in my 10.5.8 machine but it won't launch, here's the console output:

http://gist.github.com/486247

And I've also tried running the 10.6 build in my 10.6 laptop and it won't launch either.
I've tried in a friends newer macbook with 10.6 and it worked. I think that has to do with the processor since my macbook is first generation 32 bits. I soon as I get home I will post the console output.

What both of my machines have in common is that I am using Ruby Version Manager and Homebrew for package management.

Thanks

**Comment by maca** [comment]
Yep I've tried 10.5 build in at least 3 different computers with Os X 10.5 with no success

**Comment by steveklabnik** [comment]
Okay. I forget who built the 10.5 build; it was built a few weeks ago by someone, so the code is probably out of date...

The 10.6 build is 64 bit, so that would have been your problem.

**Comment by maca** [comment]
Thanks, I've tried building a 10.5 following the instructions but I couldn't. Is there a valid 10.5 build?

**Comment by steveklabnik** [comment]
I only have access to a 64 bit 10.6 machine, and so I can't build one myself... there's another guy who posted to the mailing list, said he was going to make one... 

What happened when you tried to build it? Was it similar to what was reported [over here](http://github.com/shoes/shoes/issues#issue/35)?

**Comment by steveklabnik** [comment]
Since I haven't heard from you in a while, I'm closing this issue. If you'd still like help building, please get in touch with me, or post to the shoes mailing list at shoes@librelist.com, and we'd be more than happy to try and work it out.
