### ISSUE TITLE
remove doesn't refresh

### ISSUE THREAD

**Issue by fela** [shoes/shoes-deprecated#37]
running http://gist.github.com/490925 shows keeps showing the removed para, until you resize the window (or make a refresh happen in some other way)

I'm using Linux

**Comment by ashbb** [comment]
The remove method does just only passing the object to Ruby's GC (Garbage Collection). So, if you want to repaint Shoes window immediately, use clear method.

**Comment by fela** [comment]
Okay, thanks. That's a little different than what I would have expected, perhaps it should be put clearer in the manual. Also, the manual says, about `clear()`, that it is _"effectively identical to looping through the contents of the slot and calling each element's remove method"_, this doesn't seem to be quite accurate.

**Comment by ashbb** [comment]
Yeah. More properly, clear method calls each element's remove method and then calls shoes_canvas_repaint_all() function in C.
