### ISSUE TITLE
background object does not expand in scrollable slot

### ISSUE THREAD

**Issue by ccoupe** [shoes/shoes-deprecated#38]
I don't have a simple test case yet but ashbb found :
" Workaround is putting rect object under the slot" 

that would be _visually_ under the stack slot  which means you declare the rect first and then declare the stack in the rect. 

More obvious in Linux. I think.

**Comment by ashbb** [comment]
Thank you for the post. :)  
A simple test case is this:

```
Shoes.app do
  stack left: 50, top: 50, width: 300, height: 300, scroll: true do
    background green
    @msg = para
  end
  e = every do |i|
    @msg.text += "#{i}\n"
    e.stop if i > 20
  end
end
```

And a workaround is this:

```
Shoes.app do
  nostroke
  rect left: 50, top: 50, width: 300, height: 300, fill: green
  stack left: 50, top: 50, width: 300, height: 300, scroll: true do
    @msg = para
  end
  e = every do |i|
    @msg.text += "#{i}\n"
    e.stop if i > 20
  end
end
```

I think this is not a bug. Because background is not a color option of slot, but a normal element in Shoes. They are independent.

**Comment by ccoupe** [comment]
I can confirm that Linux behaves differently than Windows on this problem. One of them has a bug.
