### ISSUE TITLE
alert in thread freezes the application

### ISSUE THREAD

**Issue by fela** [shoes/shoes-deprecated#39]
The following code freezes on my machine. I'm using Linux.

```
Shoes.app do
  Thread.new do
    alert("Hello, world!")
  end
end
```

**Comment by fela** [comment]
actually to reproduce this it seems enough to do
    Thread.new do
      alert("Hello, world!")
    end

and I just noticed that a program with just one `alert` statement never returns

**Comment by ashbb** [comment]
I confirmed this issue,
- Raisins (0.r1134) for Windows: no freeze, but nothing happen (not open alert message window)
- Policeman (0.r1486) for Windows: freeze

> I just noticed that a program with just one alert statement never returns

Yes, I think you are right. So, a workaround is this:

```
Shoes.app do
  Thread.new do
    timer(0.01){alert("Hello, world!")}
  end
end
```

This snippet works with both Raisins and Policeman.

**Comment by ccoupe** [comment]
I ran across this error in the packager. It doesn't make much sense to put up a model dialog in  a new thread, when I think about.  Should the thread suspend until the Alert is removed? Should all threads?

**Comment by fela** [comment]
The code doesn't make much sense on its own because I only posted the smallest example to reproduce the freeze. But if the code contains also other instructions it might make more sense. What I was trying to do in HH was to execute the user programs in a new Thread, but this way any program containing a dialog will not work

**Comment by ccoupe** [comment]
In linux/osx, fork()/system()/spawn()/etc  might work for your script loader There is a lot of global state in a shoes process that you may or may not want to pass to a loading script. Just thinking out loud.

**Comment by steveklabnik** [comment]
Yeah, with threads being tricky already, and things changing with newer ruby versions, I'm going to close this issue as well. Maybe this'll need reinvestigated in the future. Let's worry about it then.
