### ISSUE TITLE
Shoes.setup bombs on windows

### ISSUE THREAD

**Issue by ruuzo** [shoes/shoes-deprecated#4]
having a Shoes.setup block bombs on windows...actually a bug in rubygems 1.3.0 which is a dependency of shoes...Gem.set_paths calls Etc.getpwuid.uid where Etc.getpwuid returns nil on windows, bombing with NoMethodError

fix could be to upgrade dependencies to rubygems 1.3.1 or later

helpful link: http://jira.codehaus.org/browse/JRUBY-3197

**Comment by greatseth** [comment]
Hey, try this branch I started: http://github.com/greatseth/shoes/tree/rubygems-1.3.5

I just copied the appropriate files over those in req/rubygems, but I'm not sure if there'll be more to it than that.

**Comment by atomicules** [comment]
I've never had any problem with Shoes.setup on Windows (well Proxies, but that's not really Shoes' fault). However, I notice in Ashbb's latest builds Rubygems has been updated to 1.3.1. I.e. doing:

```
Shoes.app do
    para Gem::RubyGemsVersion
end
```

reports "1.3.1". So it's probable this issue will get closed out when Policeman is done.

**Comment by ashbb** [comment]
Now Policeman (Shoes-0.r1414 for Windows) includes rubygems 1.3.6 and can execute samples/simple-rubygems.rb fine.

**Comment by steveklabnik** [comment]
This is still an issue on OSX.

**Comment by steveklabnik** [comment]
Actually, I'm going to close this, and make a new one for OSX.
