### ISSUE TITLE
strange behaviour of sleep in timer

### ISSUE THREAD

**Issue by fela** [shoes/shoes-deprecated#41]
`sleep` in `timer` blocks the whole app, I'm not sure if that is what people expect..

```
Shoes.app do flow do
  Thread.new do
    animate(1) do
      para "*"
    end
  end

  Thread.new do
    sleep 5
    para "starting timer"
    timer(0.01) do
      sleep 5
    end
  end
end end
```

It might be kinda an acceptable behavior (although I think that the best behavior always is the most obvious one..), but this makes the workaround of issue 39 not work for me :S

**Comment by fela** [comment]
Do you think that this or issue 39 is going to be fixed in Police? Because it would be really useful for Hackety Hack, as quite some lessons use `ask` and `sleep`, and I need some workaround that works transparently to the user. Unfortunately now I can't wrap the user program neither into a thread nor a timer. 

If not let me know, and I'll try to find some other solution, but right now I can't think of anything..

**Comment by ashbb** [comment]
I think it's better to _not_ use `sleep` method. `sleep` stops everything, so your code can't do anything.

> Because it would be really useful for Hackety Hack, as quite some lessons use ask and sleep

Umm... I don't think `sleep` is so useful.  
Could you show us a few real snippets? Someone may find a solution.

**Comment by fela** [comment]
I'm using `sleep` because it was in _why's original lessons. Maybe I have to rewrite the lessons, but I don't have much time for whyday.. 

What I want to accomplish is that the user program sleeps but Hackety Hack continues running, now I'm not able to do that. I would run the user program in a separate thread (without `timer`), were it not for #39.

**Comment by ashbb** [comment]
I guess _why's original lessons are old.  
I found http://www.mail-archive.com/shoes@code.whytheluckystiff.net/msg00193.html in the old Shoes ML. Hope this helps.

**Comment by fela** [comment]
Not really as I want to solved in a way transparent to the user. The counterintuitive fact about my originally posted code is that if you remove the `timer` method it works just fine.

**Comment by fela** [comment]
I was wondering how modal dialogs did the trick of not blocking the whole application (just the user interaction part), and based on the implementation of the gtk dialogs I've came up with the following code idea that seems to work, at least in some cases

```
// callback
static gboolean
shutdown_wait_loop (gpointer loop)
{
  if (g_main_loop_is_running (loop))
    g_main_loop_quit (loop);
  gboolean call_again = FALSE;
  return call_again;
}

static void
wait(guint interval)
{
  GMainLoop *loop = g_main_loop_new (NULL, FALSE);
  g_timeout_add(interval, shutdown_wait_loop, loop);

  GDK_THREADS_LEAVE ();
  g_main_loop_run (loop);
  GDK_THREADS_ENTER ();

  g_main_loop_unref (loop);
}
```

Perhaps if the users closes the container of the widget running the wait code bad things could happen, but I thought to just share my findings

**Comment by steveklabnik** [comment]
I'm going to close this, since it's not really a bug, just some unusual behavior.
