### ISSUE TITLE
Can't package a script that includes a downloaded Shoes for Linux

### ISSUE THREAD

**Issue by ccoupe** [shoes/shoes-deprecated#43]
Linux only problem. When packaging a script,  it downloads the Shoes (.run), unpacks that .run with Minitar and then adds the script and packs it up into a new run. Minitar can't handle symbolic links so the resulting run, will not find the ruby libraries properly softlinked on the destination.  Minitar works OK for .shy file sharing but not for packaging Shoes for Linux.  Fixing it doesn't appear to be worth the effort (IMO).

**Comment by atomicules** [comment]
Can this be considered closed now, considering your recent work? (Issues 44, 45)

**Comment by ccoupe** [comment]
Your choice. The problem is hidden by the new GUI but it's still a bug that needs documented somewhere.

**Comment by steveklabnik** [comment]
I'm going to document this in the roadmap.
