### ISSUE TITLE
Programatically minimize a Shoe window

### ISSUE THREAD

**Issue by eargollo** [shoes/shoes-deprecated#47]
It would be nice if a Shoe app had a method for minimize the window. So that it could be programatically minimized though, for example, a click in a button or any other action.

Maybe this should be extended also to maximize and minimize to system tray.

**Comment by cs9000** [comment]
Yes! And ability to show/hide so can force one window on top.

**Comment by steveklabnik** [comment]
I'm closing all feature request Issues, in favor of moving them to the wiki instead. This'll make it easier to lay them out into planning for future releases. Please see [here](https://github.com/shoes/shoes/wiki/Shoes-roadmap). Thanks!
