### ISSUE TITLE
Policeman Windows XP - video flickers badly and crashes

### ISSUE THREAD

**Issue by jontyjont** [shoes/shoes-deprecated#48]
Trying the video sample...

Memory usage also creeps up until shoes crashes too

**Comment by ashbb** [comment]
Oh, yeah. This is a known bug. Please launch Shoes 3 with `--nolayered` option like this: `shoes --nolayered`

**Comment by jontyjont** [comment]
Thanks ashbb - much more stable with that! However doesn't play the video well - probably my ultra slow broadband connection.

**Comment by ashbb** [comment]
Okay. At first download [mp4 file](http://www.rin-shun.com/shoes/AdventureTimewithFinnandJakeFinnTime.mp4) by hand. Then edit simple-video.rb like this: `@vid = video "AdventureTimewithFinnandJakeFinnTime.mp4"`. You can watch the video with Shoes from local disk.

**Comment by jontyjont** [comment]
Thanks again - using a locally available video with nolayered works well, however I have found that hovering the mouse over the video controls; the play, pause etc. causes the video to be interrupted  - a grey screen results, the video returns once the mouse moves away after a few seconds. Odd!

**Comment by ashbb** [comment]
Yes. Video flickers when mouse hovers/leaved.  
But, video returns after a few seconds? Umm,... I'm not sure, but maybe need more machine power... or find another solution...
