### ISSUE TITLE
Flow slots

### ISSUE THREAD

**Issue by andhapp** [shoes/shoes-deprecated#5]
Edit lines in a flow do not line up.

<b>Version:</b> shoes policeman (0.r1249) [i386-darwin9.8.0]

<b>Error messages:</b> No error messages on the console

To replicate run the following code:

<pre>
Shoes.app do
 flow do
   @one = edit_line :size => 9, :width => 65
   @two = edit_line :size => 9, :width => 65
 end
end
</pre>

**Comment by atomicules** [comment]
Hi Anuj/andhapp,

I've been going through some of the Shoes questions on Stackoverflow and found this same issue issue mentioned here: [Alignment of edit_line](http://stackoverflow.com/questions/584256/alignment-of-editline). There is an answer that mentions a possible fix:

In [shoes/shoes/ruby.c](http://github.com/shoes/shoes/blob/master/shoes/ruby.c#L3437-3442)

```
#ifdef SHOES_QUARTZ
    //place.x += 4; place.ix += 4; //Comment out these lines to align boxes
    //place.y += 4; place.iy += 4; //Comment out these lines to align boxes
    place.h += 4; place.ih += 4;
    place.w += 4; place.iw += 4;
 #endif
```

I built Shoes on OSX PPC with this fix and it did indeed align the text boxes, but I didn't do any extensive checking to see if it had other undesirable consequences elsewhere.

**Comment by atomicules** [comment]
A commit for this fix, but tagged as osxppc only for now: http://github.com/i5m/shoes/commit/50e64a6a44cc1b8b8dad40599919f74c819423fd

**Comment by ashbb** [comment]
Hi andhapp and i5m,

Shoes for Windows doesn't seem to have this issue.

**Comment by andhapp** [comment]
Hey ashbb,

I haven't had time to go through this. But, I will try and give it a try and get upto speed with the latest Shoes development.

Cheers.
