### ISSUE TITLE
build fail on fedora13

### ISSUE THREAD

**Issue by pronix** [shoes/shoes-deprecated#50]
for start build require set in Rakefile
$LOAD_PATH << `pwd`.chop

but during compile i get this error

cp -r req/sqlite3/lib/sqlite3.rb dist/ruby/gems/1.9.1/gems/sqlite3-ruby-1.3.0/lib
cp -r req/sqlite3/lib/sqlite3 dist/ruby/gems/1.9.1/gems/sqlite3-ruby-1.3.0/lib
cp -r req/sqlite3/lib/extconf.rb dist/ruby/gems/1.9.1/gems/sqlite3-ruby-1.3.0/lib
mkdir -p dist/ruby/gems/1.9.1/gems/sqlite3-ruby-1.3.0/lib
ruby: No such file or directory -- extconf.rb (LoadError)
rake aborted!
Extension build failed
/home/dima/project/shoes/Rakefile:95:in `block in <top (required)>'
(See full trace by running task with --trace)

**Comment by steveklabnik** [comment]
The $LOAD_PATH issue makes me suspect you're running Ruby 1.9.2, is this the case? Shoes needs to be built with 1.9.1.

**Comment by steveklabnik** [comment]
I'm going to close this since we haven't heard from you in a while. Feel free to re-open if it's still a problem.
