### ISSUE TITLE
shoes --ruby is broken on 64-bit linux

### ISSUE THREAD

**Issue by DRMacIver** [shoes/shoes-deprecated#51]
It consistently segfaults, at least on my version. It could be due to a dependency  not making it happy or something though: I'm running a reasonably up to date version of arch linux, so some libraries may be unusually recent versions.

Anyway, an example which segfaults:

```
shoes --ruby -e 'puts "hello world"'
```

**Comment by ccoupe** [comment]
Shoes is not a GUI wrapper for any script of your choice. That example does not invoke the Shoes.app class. 

You must have build Shoes yourself the hard way (from source), so which version of ruby and which version of shoes did you build? 

There are thread race conditions in Linux/Shoes/1.9.x but the above example probably should fail for all versions.

**Comment by DRMacIver** [comment]
Shoes damn well is a GUI wrapper for any script of your choice if you want it to be able to use gems with native components, which is where the issue was encountered. They need to be able to run the external build scripts. As it currently stands no gem with a native dependency will build because of it. The above example was picked to remove dependencies, but even simpler ones like

```
shoes --ruby -e ''
```

fail. 

I encountered this building it on ruby 1.9.1 at commit a5006e80fd72377b2ca737ab82466cebd03ddfb6

**Comment by ccoupe** [comment]
The inability to build native gems is well known. It was discussed on the Mailing list a few weeks back. I wrote a Developers Guide (see the wiki) to explain what Shoes is, the gem issue is discussed there.

**Comment by DRMacIver** [comment]
Whatever. I discussed this in the IRC channel, and was told to file it as a bug. If you want to consider your software segfaulting in the course of apparently reasonable activities to be acceptable behaviour, that's not my problem. It's already demonstrated itself as unusable for me, so I really don't care.

**Comment by ccoupe** [comment]
Thank you for filing a bug report, DRMacIver ! We appreciate your feedback. We failed your expectations and we are sorry that we couldn't serve you properly. We wish you the best in finding the software and support you deserve.

**Comment by steveklabnik** [comment]
I've reworded this issue slightly, and posted it as a new issue, here: http://github.com/shoes/shoes/issues/issue/59

The core is that apparently shoes --ruby is horribly broken, and arguing over the validity of the value of 'puts hello' isn't constructive.
