### ISSUE TITLE
Shoes not working on OSX 10.6?

### ISSUE THREAD

**Issue by FrankDMartinez** [shoes/shoes-deprecated#53]
Hi,

I tried using Shoes on OSX 10.6.

The Shoes application does not work as advertised.

It launches and bounces for a few seconds in the 'dock' and then disappears.

Any suggestions?

Anyway I can provide extra information to resolve this?

Thanks.

**Comment by steveklabnik** [comment]
Can you try the second build?

http://shoesrb.com/downloads

**Comment by FrankDMartinez** [comment]
Thanks, Steve.

That build does seem to work, yes.

**Comment by steveklabnik** [comment]
Cool. It's only a few revisions behind. I think when I built that last one, something screwy happened...

**Comment by FrankDMartinez** [comment]
I also am contending with a 10.5 machine.  Should that build work with the 10.5 or would I find a workable Shoes build for that platform elsewhere on GitHub?

**Comment by steveklabnik** [comment]
We weren't able to find anyone to build one. You could try building from source, but it's not the easiest thing to do :/. 

http://github.com/shoes/shoes/wiki/Building-Shoes-64-bit-for-Snow-Leopard
http://github.com/shoes/shoes/wiki/BuildingShoesOnOSX

There were a lot of changes in OSX from 10.5 to 10.6...

**Comment by FrankDMartinez** [comment]
I'll give it a shot.  No promises, though.  ;-)

**Comment by steveklabnik** [comment]
That would be really fantastic. If I can be of any help at all, steve+shoes@steveklabnik.com will get a hold of me. A 10.5 build would be really great.

**Comment by FrankDMartinez** [comment]
Sure thing.  I did hit a snag but will post the remarks on that effort in a separate issue.
