### ISSUE TITLE
Trying to build Shoes for Mac 10.5; Hit a snag ...

### ISSUE THREAD

**Issue by FrankDMartinez** [shoes/shoes-deprecated#54]
Hello,

As the title says, I was trying to build for Mac 10.5.  I got all the way up to step 12 (building RubyGems) on http://github.com/shoes/shoes/wiki/BuildingShoesOnOSX when My console output looked like so, http://pastebin.org/212103.  Any thoughts of how to proceed?

Thanks

**Comment by steveklabnik** [comment]
Does this help at all? It seemed to fix it for him... http://groups.google.com/group/rubyonrails-talk/browse_thread/thread/4808a6e45ce2fb11/7d7511b914ee7a92?show_docid=7d7511b914ee7a92&pli=1

I've never seen this error before. :/

**Comment by atomicules** [comment]
This is probably a conflicting path issue. What do you get if you do: `which ruby`, etc?

**Comment by FrankDMartinez** [comment]
@i5m: I see "/opt/local/bin/ruby", which differs from the path to the ruby binary I used in "sudo /Users/Frank/Downloads/shoeMaker/dep/bin/ruby setup.rb".

@steve: I'll give it a go.  I don't know if I'll be able to try this today, though.  So, it may take a while.  When I have an answer though, I will post it.

Thanks.

**Comment by steveklabnik** [comment]
No worries, whenever you get around to it. Open Source can't exactly say 'DO IT NOW!,' we're just thankful for some contribution. :)

**Comment by FrankDMartinez** [comment]
Some progress.  Apparently RubyGems comes by default with Ruby 1.9.2 and does not need to be installed separately.  I am now stuck, however, at "Build Shoes step 6".  When I run 'rake', I receive this message http://pastebin.org/318087.  Any thoughts?

**Comment by steveklabnik** [comment]
Oh! I knew that. Sigh. Technically, Policeman only supports 1.9.1, so one built with 1.9.2 would be non-conforming. That said, the only reason we didn't do it with 1.9.2 is because it was released a week before the Shoes 3 deadline...

Anyway, yeah, so if it can't find rake... what does 'which rake' say?

**Comment by FrankDMartinez** [comment]
/Users/Frank/Downloads/shoeMaker/dep/bin/rake, which is the rake I installed in the temporary directory.

**Comment by steveklabnik** [comment]
Hrm. 

Doing some googling, I found this gist: http://gist.github.com/519744

**Comment by steveklabnik** [comment]
Since I haven't heard from you in a while, I'm closing this issue. If you'd still like help building, please get in touch with me, or post to the shoes mailing list at shoes@librelist.com, and we'd be more than happy to try and work it out.
