### ISSUE TITLE
Hpricot chokes on ASCII-8bit in Shoes

### ISSUE THREAD

**Issue by zzak** [shoes/shoes-deprecated#55]
While trying this simple example of parsing a Google search query in Shoes, I got a strange unicode error from Hpricot, see this gist:

https://gist.github.com/59ec645589475ba77c23

**Comment by steveklabnik** [comment]
Confirmed on OSX.

**Comment by atomicules** [comment]
Perhaps similar to the other encoding issues we came across? 
http://gist.github.com/289714
http://groups.google.com/group/shoooes/browse_thread/thread/a3c9ddefce27e5b8
http://groups.google.com/group/shoooes/browse_thread/thread/4ffb5db404a55bf1

By the way, crashes on windows XP with Shoes 3 (r1514)

**Comment by ashbb** [comment]
On my Windows 7 laptop with Shoes 3, the following two worked well.
- https://gist.github.com/59ec645589475ba77c23
- http://gist.github.com/289714

And after I edited [shoes/lib/shoes.rb line 22](http://github.com/shoes/shoes/blob/master/lib/shoes.rb#L22) a little like this, just added `US_ASCII`:

```
%w[ASCII_8BIT UTF_16BE UTF_16LE UTF_32BE UTF_32LE US_ASCII].each do |ec|
```

the following also worked well.
- http://gist.github.com/257819

<pre>
Shoes.setup do
  gem 'mechanize'
end

require 'rubygems'
require 'mechanize'

Shoes.app do
  Agent = Mechanize::Mechanize.new
  page = Agent.get('http://www.google.com/')
  para page.body
end
</pre>

**Comment by steveklabnik** [comment]
I've played around with this, and it seems that Ash's edit to shoes.rb would fix this. I want to do a little more testing, but the workaround works for now.

**Comment by steveklabnik** [comment]
Fixed with commit [078608](http://github.com/shoes/shoes/commit/078608ccbf0d44681852bc39e8267bb401e96db7)
