### ISSUE TITLE
Downloadable Shoes

### ISSUE THREAD

**Issue by zzak** [shoes/shoes-deprecated#57]
Regarding the official github repo and this page: http://shoesrb.com/downloads

The shoes installers links point to varying locations, from さとし's box, to steve's github and even whymirror.

All versions of shoes should be downloadable from the official github repository, and likewise all the download links on the site should follow suit.

**Comment by steveklabnik** [comment]
Sounds fine by me. I'll get on this tonight.

**Comment by steveklabnik** [comment]
Done.
