### ISSUE TITLE
Shoes Manual

### ISSUE THREAD

**Issue by zzak** [shoes/shoes-deprecated#58]
## The following is extracted from a shoes-web wiki entry discussion

I've had an idea for a wiki manual. This would allow people to contribute to the manual easily.

The question is: is this really necessary? Perhaps we should just split the manual into easier-to-edit files.

Post any comments/criticism here:

---

_devyn_: post new comments at the bottom.

_ultrasaurus_: Currently, the Shoes manual is well-crafted documentation.  Wikis almost by definition are not.  I think it is important that the manual be thoughtfully edited and that changes can be carefully tracked.  Therefore, I would not advise wiki editing of the manual.  

_devyn_: I realize, but I could make some kind of wiki2git script, so we could choose what changes get pulled into the manual...
The point is, I think that many people are more comfortable editing Textile in a browser than on the command line. We could have git2wiki too, so the formats are inter-convertible...
Git + the command line is not great for people who are just learning how to program, and might scare them away from helping out with the project.

_devyn_: I want to bring this up again, this time with a little proof on my side. http://love2d.org/wiki/ is very nice documentation. I think we should do something like this.

_zak_: Firstly, this discussion belongs in github issues, or on the mailing list, as I'm sure some of the other members would like to participate in the discussion. I'll add this to the issues and report back here.

**Comment by zzak** [comment]
I agree, the manual should be kept separate from the site and red shoes core, especially since there will be multiple versions of shoes at some point and each will have to maintain a separate manual, which most of it will just be duplication. However I think a git repository will do just fine and provide us everything we'll need to maintain and distribute the manual's source to various shoes related situations.

I'll set up an issue on shoes core about this, as I've got some changes in line for the manual and I'd like to resolve the duplication involved in updating shoes manuals.

**Comment by steveklabnik** [comment]
I'm going to close this for now, because we're discussing it on the ML, here: http://librelist.com/browser//shoes/2010/10/28/a-few-thoughts-about-the-manual/

People don't get email updates here, if we come to some sort of decision on what action needs to be taken, let's make issues about those.
