### ISSUE TITLE
"shoes --ruby" is broken.

### ISSUE THREAD

**Issue by steveklabnik** [shoes/shoes-deprecated#59]
This is a slight reworking of the issue here: http://github.com/shoes/shoes/issues/#issue/51

Apparently, `--ruby` just doesn't work. I tried this on my build:

`shoes --ruby -e "Shoes.app"`

And it bombs with

```
dyld: Library not loaded: ./deps/lib/libruby.dylib
  Referenced from: /Applications/Shoes.app/Contents/MacOS/libshoes.dylib
  Reason: Incompatible library version: libshoes.dylib requires version 1.9.1 or later, but libruby.dylib provides version 1.8.0
Trace/BPT trap
```

Is there a valid use case for shoes --ruby? Is this a misfeature? Should it be fixed?

**Comment by steveklabnik** [comment]
This is called when shoes tries to build gems with native extensions, so... that might be one of the reasons that is broken.

**Comment by ccoupe** [comment]
IMHO, it's low priority for Red Shoes.  is Shoes --ruby documented anywhere? That should be fixed before someone, once again believes Shoes is the Ruby they know.

**Comment by steveklabnik** [comment]
Adding this to the [roadmap](https://github.com/shoes/shoes/wiki/Shoes-roadmap), under 'native shoes extensions.'
