### ISSUE TITLE
Stack slots

### ISSUE THREAD

**Issue by andhapp** [shoes/shoes-deprecated#6]
edit_line and edit_box dont line up (on the left)

<b>Version:</b> shoes policeman (0.r1249) [i386-darwin9.8.0]

<b>Error messages:</b> No error messages on the console

To replicate run the following code:

<pre>
Shoes.app do
 stack do
   @line = edit_line :size => 9, :width => 65
   @block = edit_box :size => 9, :width => 65, :height => 100
 end
end
</pre>

**Comment by atomicules** [comment]
Seems like this is related to issue 5. Please see my comment there.
