### ISSUE TITLE
Blue Bar

### ISSUE THREAD

**Issue by steveklabnik** [shoes/shoes-deprecated#60]
Imported from steveklabnik/issues:

A weird blue bar is showing up on the manual screen: http://cl.ly/1OAx

This seems to be happening when images are displayed?

Comments
devyn June 16, 2010 | link | edit | delete
not to do with images. http://cl.ly/1OmH http://cl.ly/1Oen http://cl.ly/1OAx

all have images in them.

**Comment by phinze** [comment]
No blue bar here on OSX Lion:

<img src="https://github.com/phinze/shoes-experiments/raw/master/screenshots/blue-bar-osx-lion-issue-60.png" />

**Comment by steveklabnik** [comment]
No longer on Snow Leopard HEAD either. :)
