### ISSUE TITLE
Shoes3 can't use relative paths in Linux

### ISSUE THREAD

**Issue by robbrit** [shoes/shoes-deprecated#64]
If I have the shoes3.run script in the same folder as a file called test.rb, the following should work:

```
./shoes3.run test.rb
```

or

```
./shoes3.run ./test.rb
```

Instead of working, I get the following error:

```
No such file or directory - test.rb
/tmp/selfgz14949/lib/shoes.rb:439:in `read'
/tmp/selfgz14949/lib/shoes.rb:439:in `read_file'
/tmp/selfgz14949/lib/shoes.rb:427:in `visit'
(eval):1:in `<main>'
```

It seems like Shoes is trying to load the file from the /tmp directory wherever it is extracted. The file loads fine when I pass in an absolute path.

**Comment by ccoupe** [comment]
Yes.  It depends on where that ./shoes3.run came from. If it came from the packager in Shoes, then the .run extracts the script into /tmp and puts the Shoes executable into ~/.shoes/shoes.run which different from the packaged script .run

All .runs respond to --help on the command line.
~/.shoes/shoes.run --help suggests that the relative path needs ' -- ' ahead of the ./test.rb or test.rb

**Comment by robbrit** [comment]
It came from the downloads page on shoesrb.com.

Is it possible to make it so that it uses a relative path by default instead of having to put the --?

**Comment by ccoupe** [comment]
Your best workaround is to build shoes from Source - it's not that hard and if there are problems we can fix them on the mail list or on the irc. Really it's better and you'll be happier.  

The run file is more like a tar ball, that has to be expanded every time to run a script. It's purpose is to run the shoes script packed inside the .run. it's not really designed to be a general purpose Shoes launcher.  

In Windows and OSX we can provide "Apps". Not so easy for Linux.  Ideally we would provide a .deb and a .rpm to install Shoes but we aren't there  yet.

**Comment by steveklabnik** [comment]
I'm going to close this, since it's not really fixable.
