### ISSUE TITLE
Can't tab between fields.

### ISSUE THREAD

**Issue by steveklabnik** [shoes/shoes-deprecated#65]
If I run this app

Shoes.app do
  edit_line
  edit_line
end

And hit tab, it doesn't move between fields.

Can anyone confirm on windows/linux?

**Comment by zzak** [comment]
Unable to reproduce with Shoes 3.0.0 in Ubuntu Linux 10.04 using the following example:

```
Shoes.app do
  edit_line
  edit_line
end
```

I give this a try on Windows once I setup (red) shoes on 7.

**Comment by phinze** [comment]
Heyo, believe I tracked the cause of this one down. Seems to be a problem in `native/cocoa.m` which would suggest that the problem is osx-specific.

Pull request with a fix is here: https://github.com/shoes/shoes/pull/144
