### ISSUE TITLE
Gradients don't seem to work.

### ISSUE THREAD

**Issue by steveklabnik** [shoes/shoes-deprecated#66]
This isn't like the simple-sphere example, where it straight-up breaks. Most gradients just simply don't appear.

**Comment by zzak** [comment]
Can you get the basic gradient example to work? 

http://github.com/shoes/shoes-contrib/blob/master/basic/gradient-shoes.rb

It seems okay on linux.

**Comment by steveklabnik** [comment]
![shoes gradient example](http://imgur.com/QCaMw.png)

Nothing in the console.

**Comment by steveklabnik** [comment]
Closing, #84 is a dup.
