### ISSUE TITLE
shoes-contrib art/faded.rb fails

### ISSUE THREAD

**Issue by zzak** [shoes/shoes-deprecated#68]
Was just testing some of the shoes-contrib examples on a fresh install of Shoes 3 Policeman on Windows 7.

The following example is broken, with no errors reported to console: https://github.com/shoes/shoes-contrib/blob/master/art/faded.rb

It's just one huge red circle instead of a gradual circle opacity pattern.

**Comment by ashbb** [comment]
Revised a little like this. Then it works on my Windows 7 with Shoes 3.

```
Shoes.app :width => 600, :height => 600 do
  nostroke
  #draw_circle(self, 0.9, 600)

  def draw_circle(app, color, size)
    r = size/2
    app.fill gray(color)
    app.oval app.width/2 - r, 0, size, size
    draw_circle(app, color - 0.04, 3*size/4) if (color > 0.4)
  end
  draw_circle(self, 0.9, 600)
end
```

**Comment by steveklabnik** [comment]
Interesting. So is this a bug? Hm.

**Comment by steveklabnik** [comment]
yeah, I dont think this counts as a bug. Running it on my Policeman, I get 'no method error' because you haven't defined `draw_circle`. Makes sense. Define methods before you use them!

Moving it after works. I've pushed to shoes-contrib, and closing this.
