### ISSUE TITLE
Alt-/ gets locked out sometimes

### ISSUE THREAD

**Issue by steveklabnik** [shoes/shoes-deprecated#69]
Originally from here: https://github.com/shoes/shoes/issues#issue/21

```
Shoes.app do 
  stack do 
    para("Enter text, press button. <alt-/> won't work.")
    flow do
      @entry = edit_line
          @button = button("add_para") do
        para(@entry.text)
      end
    end
  end
end
```

After entering text in the box, the console won't come up.

Confirmed on XP only right now, I'll test on OSX soon.

**Comment by ashbb** [comment]
In Windows, native widgets - edit_line, edit_box, button, etc. - don't pass <alt-/> or return or etc. to Shoes. I'm not sure there is a loophole.

So, how about using Shoes.hook method for one of the alternative ways?

<pre>
def Shoes.hook
  window width: 200, height: 100 do
    button('manual'){Shoes.show_manual}
    button('console'){Shoes.show_log}
  end
end

Shoes.app do
  stack do
    para("Enter text, press button. <alt-/> won't work.")
    flow do
      @entry = edit_line
      @button = button("add_para") do
        para(@entry.text)
      end
    end
  end
end
</pre>


As you press `enter` key in the edit_line, small window will be come up.

**Comment by steveklabnik** [comment]
This actually works correctly on OSX, the window comes up.

I'm not sure if this is fixable or not. Lemme look into it some more, it just might be broken. :/

**Comment by steveklabnik** [comment]
This has to deal with the stealing of focus. I'd say this is a nofix for policeman, at least right now.
