### ISSUE TITLE
edit_line does not wrap properly

### ISSUE THREAD

**Issue by andhapp** [shoes/shoes-deprecated#7]
when edit_line contains a string that needs to wrap, you can see the top of the text of the second line on the bottom of the field.

<b>Version:</b> shoes policeman (0.r1249) [i386-darwin9.8.0]

<b>Error messages:</b> No error messages on the console

To replicate run the following code:

<pre>
Shoes.app do
 stack do
   @line = edit_line :width => 100
   @line.text = "some/long/file/path/that/doesn't/seem/to/wrap/too/well"
 end
end
</pre>

**Comment by evanfarrar** [comment]
Not a problem in GTK/Ubuntu. edit_line's overflow to the left and do not wrap.

**Comment by andhapp** [comment]
Does not wrap?...but it is meant to wrap because the length of the text is more than the width of the box.

**Comment by ashbb** [comment]
Hi andhapp,

> the length of the text is more than the width of the box.

That's right.   　
But doesn't need to wrap, because it can scroll in a horizontal direction.

**Comment by andhapp** [comment]
Hey ashbb,
Ohh...so line_width is the area that would be displayed because going by the name it seems it is basically the width of the text that should be displayed and anything greater than the width should just go the next line. Is that correct?

**Comment by ashbb** [comment]
andhapp

Umm... I'm not sure. But my understanding is:
- edit_line: scroll in a horizontal direction  
- edit_box : turn down at right edge

**Comment by andhapp** [comment]
ashbb,

Ok. I will have a look at the internals later today. Do you know who is heading OS X development?
