### ISSUE TITLE
Crashes after 15 minutes?

### ISSUE THREAD

**Issue by steveklabnik** [shoes/shoes-deprecated#74]
Reported on IRC:

21:10 < Newhydra> hey, have you guys had a problem on windows where shoes apps quit after running for 10-15 minutes?
21:11 < Newhydra> unexpected error
21:11 < Newhydra> happens with basically anything I write or any example programs (and the shoes manual)
21:29 < Newhydra> (the error is "microsoft visual c++ runtime library runtime error, c:\program files\common files\shoes\0.r1514\shoes.exe, the application has requested the runtime to terminate it in an unusualy way, please contact the aplpication's support team for more information"

Could this be related to https://github.com/shoes/shoes/issues/labels/windows%20xp#issue/72 ?

**Comment by whiny-nil** [comment]
I can confirm this bug (not the reason) on Vista too.  It happens when I am using Hackety Hack.

**Comment by steveklabnik** [comment]
Tagged, thanks.

**Comment by serialhex** [comment]
just fyi, i get this bug on win 7 also.  it happens randomly while i'm using shoes (i dont need to be running an app either, sometimes just having the splash screen will do it).
hex

**Comment by steveklabnik** [comment]
tagged for Win7.

It has to do with 1.9.1's threads, apparently... i've been working on getting a 1.9.2 shoes going, but it's complicated...
