### ISSUE TITLE
:font option for edit_box

### ISSUE THREAD

**Issue by glurp** [shoes/shoes-deprecated#75]
@a=edit_box($code , :height=>550 ,:font => "FreeSans 10")
dos nothing

too bad for edit shoes code in shoes app :)

**Comment by steveklabnik** [comment]
I'm closing all feature request Issues, in favor of moving them to the wiki instead. This'll make it easier to lay them out into planning for future releases. Please [see here](https://github.com/shoes/shoes/wiki/Shoes-roadmap). Thanks!
