### ISSUE TITLE
Unprintable characters in text

### ISSUE THREAD

**Issue by andriusch** [shoes/shoes-deprecated#77]
So I'm working on encoder-decoder for my cryptography class. It simulates sending data through network by corrupting some bits (changing 0s to 1s and vice versa). This means that when sending string through network I may get some unprintable characters (for example sending "Data" I receive "Dat\xE1"). Now I need to display this in edit_box, but text does not show up if it contains unprintable characters.

**Comment by ccoupe** [comment]
Yes, Ruby is really picky about encoding.  Set your streams to ASCII-8BIT will help. Odds are that Ruby is throwing an exception to Shoes (printed on the shoes console). You'll also need a font assigned to the edit_box that has representation of all the incorrect characters.  Even then I suspect you are in for frustration try to get this work.

**Comment by steveklabnik** [comment]
I'm closing this, since it's a user error. It makes sense to me that trying to print unprintable characters is undefined behavior.
