### ISSUE TITLE
Compile error on Debian based systems.

### ISSUE THREAD

**Issue by ghost** [shoes/shoes-deprecated#78]
I'm compiling rake or rake --trace command but cant compile this project.

Error:
~/Projects/shoes# rake --trace
(in /root/Projects/shoes)
rake aborted!
undefined method `require_relative' for main:Object
/root/Projects/shoes/Rakefile:4
/usr/lib/ruby/1.8/rake.rb:2149:in`load'
/usr/lib/ruby/1.8/rake.rb:2149:in `raw_load_rakefile'
/usr/lib/ruby/1.8/rake.rb:1897:in`load_rakefile'
/usr/lib/ruby/1.8/rake.rb:1948:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:1896:in`load_rakefile'
/usr/lib/ruby/1.8/rake.rb:1880:in `run'
/usr/lib/ruby/1.8/rake.rb:1948:in`standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:1878:in `run'
/usr/bin/rake:28

**Comment by steveklabnik** [comment]
Whoops! Our debian (and ubuntu) instructions are apparently slightly out of date. It says ruby 1.8-dev, but Ruby 1.9 is needed to build Shoes.

Can you try installing ruby1.9 and ruby1.9-dev, and compiling again? if that works, I'll update the instructions. Thanks!

**Comment by zzak** [comment]
You can try using [rvm](http://rvm.beginrescueend.com/) to manage your ruby versions as well.

Sorry I missed that bit in the documentation, I'm just so used to building my own rubyies with rvm and avoiding the Ubuntu repo's entirely.

**Comment by steveklabnik** [comment]
Since I haven't heard from you in a while, I'm closing this issue. If you'd still like help building, please get in touch with me, or post to the shoes mailing list at shoes@librelist.com, and we'd be more than happy to try and work it out.
