### ISSUE TITLE
Feature: Upload method

### ISSUE THREAD

**Issue by andhapp** [shoes/shoes-deprecated#8]
Upload method, which will automatically use a multi-part form post when it detects that one of its values is a file or IO object. 

(Not in usual bug format as it is a feature)

**Comment by steveklabnik** [comment]
This could probably be backported from Hackety. We have an HTTP library that does this.

**Comment by steveklabnik** [comment]
I'm closing all feature request Issues, in favor of moving them to the wiki instead. This'll make it easier to lay them out into planning for future releases. Please [see here](https://github.com/shoes/shoes/wiki/Shoes-roadmap). Thanks!
