### ISSUE TITLE
Shoes 3.0 fails to run on Windows XP

### ISSUE THREAD

**Issue by adroc** [shoes/shoes-deprecated#80]
After installing shoes, I try to run in my new shoes.  I get a brief hour glass.  In the task manager I see a shoes.exe process start and disappear on it's own.

**Comment by steveklabnik** [comment]
Hm. No other output?

**Comment by adroc** [comment]
Correct, no other output.

**Comment by steveklabnik** [comment]
I can't reproduce this.
