### ISSUE TITLE
Shoes doesn't build properly on OS X 10.5

### ISSUE THREAD

**Issue by steveklabnik** [shoes/shoes-deprecated#83]
This is an outstanding issue, and none of the people who've taken a shot at it have been able to make it work.

**Comment by hannahherbig** [comment]
Hi. I've got a 2006 iMac that I got a few days ago from someone that didn't need it anymore. It's got Leopard on it. How can I help to make Shoes work on it? Is there someone I can talk to on some sort of messenger (IRC, Google Talk, Jabber/XMPP, AIM)?  I'd be happy to help get Shoes to work on Leopard.

**Comment by steveklabnik** [comment]
Hi! This would be most excellent! I'd love to help take a crack at this.

Here's the thing: I'm going to be taking off work to work on Shoes full-time. I won't be doing this for another ten days or so. So what do you say that we reconvene then and take a crack at it?

If you're champing at the bit to get going before then, you can check on the Shoes mailing list. A few people were working on this a few weeks ago: http://librelist.com/browser/shoes/ specifically http://librelist.com/browser//shoes/2011/5/24/building-shoes-for-32-bit-osx/

**Comment by hannahherbig** [comment]
Sounds like a plan.

**Comment by wasnotrice** [comment]
There may be two separate issues:
- Leopard
- Your iMac might have a 32-bit processor (like mine). Check Apple > About This Mac > Processor. Mine (32-bit) reads: 
  
  ```
  1.83 GHz Intel Core Duo
  ```
  
  I think if you get past the Core Duo and into the Core 2 Duos, you are in 64-bit land.

**Comment by steveklabnik** [comment]
@wasnotrice yep, "Core Duo" is 32 bit, "Core 2 Duo" is 64.

We planned to support 32-bit with 10.5, and 64-bit with 10.6+. Haven't gotten the 10.5 build working.

**Comment by wasnotrice** [comment]
> @wasnotrice yep, "Core Duo" is 32 bit, "Core 2 Duo" is 64.
> 
> We planned to support 32-bit with 10.5, and 64-bit with 10.6+. Haven't gotten the 10.5 build working.

And this is totally fine, of course. I just wanted to help clarify the situation, because some 2006 iMacs are 32-bit and some are 64-bit. Also, there is no reason that a 32-bit machine would have to be running 10.5 and not 10.6 (my 32-bit iMac runs 10.6). Support for 32-bit was only dropped in 10.7 ;(

**Comment by steveklabnik** [comment]
Absolutely. :)
