### ISSUE TITLE
Background blue when using a gradient

### ISSUE THREAD

**Issue by wouterdebie** [shoes/shoes-deprecated#84]
The background of my Shoes app turns blue when I try to use a gradient on OSX.

The code is that causes this is:

```
Shoes.app :height => 400, :width => 950 do 
  background(gradient('#000', '#FFF'))
end
```

**Comment by steveklabnik** [comment]
Strange. Confirmed on my system, too.

**Comment by steveklabnik** [comment]
Oh, this is a dup of #66. I'm going to close that one, though, so that we can both get updates when I fix it.

**Comment by ashbb** [comment]
The code works well on my Windows XP and 7. Confirmed with Shoes 3 (0.r1514). Looks like an issue for only OSX.

**Comment by steveklabnik** [comment]
Thanks ash.

**Comment by phinze** [comment]
FYI this works for me using current `HEAD` running on OSX Lion:

<img src="https://github.com/phinze/shoes-experiments/raw/master/screenshots/gradient-test-osx-lion.png" />

**Comment by steveklabnik** [comment]
This also works with HEAD on Snow Leopard. I'm considering it closed.
