### ISSUE TITLE
Can't change the title of a button

### ISSUE THREAD

**Issue by steveklabnik** [shoes/shoes-deprecated#86]
```
Shoes.app do
  @button = button "Change Me" do
    @button.text = "I'm changed"
  end
end
```

I checked in the code, text= isn't implemented.

**Comment by atomicules** [comment]
You closed this ([issue 19](https://github.com/shoes/shoes/issues/closed/#issue/19)) as a feature request ;-)

**Comment by steveklabnik** [comment]
hahaha, dammit! I forgot.
