### ISSUE TITLE
edit_line#change doesn't register for tab/return

### ISSUE THREAD

**Issue by steveklabnik** [shoes/shoes-deprecated#87]
Not 100% sure this is a bug, but an edit_line wont fire a change event when you hit enter inside.

Here's an app:

```
Shoes.app {
  edit_line {|e|
    alert(e.text)
  }
}
```

Type some text, it alerts on each keypress. Except enter. Is this intended, or a bug?

**Comment by pikajude** [comment]
Also isn't fired on tab, but that may not be a bug either.

**Comment by zzak** [comment]
/subscribe 

ill take a look at this later when I get a sec.

**Comment by ashbb** [comment]
This is intended. It should be said _a restriction_, but not a bug. If you want to catch all keys user input, use _keypress_ method.

**Comment by pikajude** [comment]
If the textbox is focused, keypress still doesn't catch it.
    Shoes.app {
      edit_line
      keypress {|k|
        alert(k)
      }
    }
