### ISSUE TITLE
Radio.checked? fails

### ISSUE THREAD

**Issue by ccoupe** [shoes/shoes-deprecated#89]
around line 5003 in shoes/ruby.c for radio buttons the code for checked? calls the code for check.checked?

It should call a radio specific hook not a check hook.

**Comment by steveklabnik** [comment]
Could you give me a test case for this, when you get the chance? I'll bang it out then.

**Comment by nashby** [comment]
``` ruby
 Shoes.app do
   r = radio; para strong("The Taste of Tea"), " by Katsuhito Ishii\n"
   radio; para strong("Kin-Dza-Dza"), " by Georgi Danelia\n"

   button "Check" do
     alert(r.checked?)
   end
 end
```

this example works as expected for me. @ccoupe do you have any problem with `checked?` method?

**Comment by steveklabnik** [comment]
This works for me as well, on OSX.

**Comment by ccoupe** [comment]
I'm going to close this issue. It was Linux specific and I've lost the test case. It was also low priority.
