### ISSUE TITLE
Feature: Extending :body

### ISSUE THREAD

**Issue by andhapp** [shoes/shoes-deprecated#9]
Allow :body option to accept an IO object (using an IO object allows for measuring upload progress) for doing REST style posts. (to sites like flickr / amazon S3 etc.)

(Not in usual bug format as it is a feature)

**Comment by steveklabnik** [comment]
I'm closing all feature request Issues, in favor of moving them to the wiki instead. This'll make it easier to lay them out into planning for future releases. Please [see here](https://github.com/shoes/shoes/wiki/Shoes-roadmap). Thanks!
