### ISSUE TITLE
does not install on debian

### ISSUE THREAD

**Issue by rchugunov** [shoes/shoes-deprecated#93]
root@debian:/usr/local/shoes# rake
(in /usr/local/shoes)
rake aborted!
no such file to load -- bundler
internal:lib/rubygems/custom_require:29:in `require'
<internal:lib/rubygems/custom_require>:29:in`require'
/usr/local/shoes/Rakefile:25:in `<top (required)>'
/usr/lib/ruby/1.9.1/rake.rb:2373:in`load'
/usr/lib/ruby/1.9.1/rake.rb:2373:in `raw_load_rakefile'
/usr/lib/ruby/1.9.1/rake.rb:2007:in`block in load_rakefile'
/usr/lib/ruby/1.9.1/rake.rb:2058:in `standard_exception_handling'
/usr/lib/ruby/1.9.1/rake.rb:2006:in`load_rakefile'
/usr/lib/ruby/1.9.1/rake.rb:1991:in `run'
/usr/bin/rake:28:in`<main>'

**Comment by steveklabnik** [comment]
You're going to have to `gem install bundler`.

I'm closing this, and adding it to the instructions.
