### ISSUE TITLE
Does my shoes app need to be in one rb file

### ISSUE THREAD

**Issue by onknows** [shoes/shoes-deprecated#95]
Hi,
The wiki https://github.com/shoes/shoes/wiki/A-Developer%27s-Tour-Through-Shoes answers a lot of questions but not the most trivial ones, I think, for first time users.

Do I need to put all my code in one rb file?

I used a require in my project of a rb file that I put in a dist directory. Shoe will run the project but I package and run on another computer Shoe will not be able to find the file. So it is not packaged. Does this mean that I have to put all code in one rb file?

Also, what to do with gem files? I suspect I have to also put them somewhere if they need to be included?

Shoes can be downloaded as part of the executing of the created application. Will this work behind a firewall?
Thanks and Regards,
Onno

**Comment by atomicules** [comment]
Onno,

> Do I need to put all my code in one rb file?

No. You can package up apps that have more than one file/folder, but you have to call the packager from the command line: `shoes --package`

> Also, what to do with gem files?

In an ideal world, you just do;

```
Shoes.setup do
    gem 'flickraw'
end
```

at the start of your shoes app and on first run it will download and install the gem if required. However...

> Will this work behind a firewall?

I've had lots of trouble here in the past, especially on windows. It's required manually setting http_proxy environment variables, and altering Shoes code to remove the `resolv-replace` bit which is actually meant to help on windows, but it will depend on your environment. This is for me at work behind a very difficult firewall.

So it maybe best practice to package up the gem locally (you'll have to do this manually, so how easy this is will depend on the gem) with your app and include Shoes itself if you are distributing it behind a firewall.

**Comment by steveklabnik** [comment]
I'm closing this, since it isn't really an Issue. Can you post to our mailing list with these questions in the future? shoes@librelist.com

**Comment by ashbb** [comment]
Hi Onno,

> Do I need to put all my code in one rb file?

No. :)  
You can make .shy file. Try out the following.
- save the following three .rb files (a.rb, b.rb, c.rb) under c:\tmp\abc directory

<pre>
# a.rb
require_relative 'b'
require_relative 'c'
include B
include C
Shoes.app do
  hello
  hi
end

# b.rb
module B
  def hello
    para 'hello'
  end
end

# c.rb
module C
  def hi
    para 'hi'
  end
end
</pre>

- open Shoes and click `Package an App' link  
- select c:\tmp\abc\a.rb file  
- fill in Project Name, Version, Your Name and click Build .shy button  
- you will get abc.shy file under c:\tmp directory  

Then just double-click abc.shy file to launch your Shoes app.

Hope this helps,  
ashbb
