### ISSUE TITLE
rect strokewidth versus line_to strokewidth

### ISSUE THREAD

**Issue by karatedog** [shoes/shoes-deprecated#96]
I set the strokewidth to 1.
Then I draw a rectangle with 'rect'  then recreate the previous rectangle by line_tos, inside a shape, then the two shape's stroke width will be different, the rectangle's strokewidth seems to be 2 pixels. However setting the stroke width on the rectangle to 0.5 does not help, as the rectangle becomes somehow semi transparent.

```
Shoes.app do
 def my_sqare(width, color, x1, y1, x2, y2)
strokewidth(width)
stroke(color)
nofill
shape do
  #rect(x1, y1, x2, y2, 0.8)
  move_to(x1, y1)
  line_to(x2, y1)
  line_to(x2, y2)
  line_to(x1, y2)
  line_to(x1, y1)
end
end

my_sqare(1, black, 50, 50, 100, 100)
```

**Comment by karatedog** [comment]
Hmm, I just found the answer by accident.

These generate different strokewidths:

```
shape do
  rect(x1, y1+50, x2, y2+50, 0.8)
end
```

or

```
rect(x1, y1+50, x2, y2+50, 0.8)
```

**Comment by ashbb** [comment]
Hi karatedog,

Do you mention about Green Shoes? ;-)

If so, yes you are right. Green Shoes' Rect and Oval paint a line around the INSIDE of a shape, not the outside. They are the same as Border.

Try out the following with Red Shoes and Green Shoes.
You can find the difference.

<pre>
Shoes.app do
 nofill
 strokewidth 20
 rect 0, 0, 100, 100
end
</pre>


I like this spec, but may need to prepare the Red Shoes compatible mode.

**Comment by karatedog** [comment]
I tried it in Red Shoes.
Is Green Shoes available on Linux? I only found the Windows installer.
Question 2: is it possible to somehow draw a top-level menu, a right-click menu in Shoes? 
I'm honing my Ruby skills (I'm a hobbyist), and I thought I just make a simple text editor. A top level menu can be faked, but it is ugly...

Thanks

**Comment by ashbb** [comment]
> I tried it in Red Shoes.

Oh, sorry. I didn't check your code in the first post. xx-P  
In Green Shoes, the rect() method is not available within the shape() block so far.

Now I understood your first problem.  
Yes, you are right. The rect() method seems to be not available any options. Look at this:

<pre>
Shoes.app do
 def my_sqare(width, color, x1, y1, x2, y2)
   strokewidth(width)
   nofill
   shape do
     rect(x1, y1, x2, y2, stroke: color)
   end
 end
 my_sqare(1, red, 50, 50, 100, 100)
end
</pre>


The above rectangle is black...

As the result of trial and error, I got a solution for your first problem. Try out the following. I'm not sure why, though. :-P

<pre>
Shoes.app do
 def my_sqare(width, color, x1, y1, x2, y2)
   strokewidth(width)
   stroke(color)
   nofill
   shape do
     rect(x1, y1, x2, y2, strokewidth: 0)
     move_to(x1, y1)
     line_to(x2, y1)
     line_to(x2, y2)
     line_to(x1, y2)
     line_to(x1, y1)
   end
 end
 my_sqare(1, black, 50, 50, 100, 100)
end
</pre>


> Is Green Shoes available on Linux?

Yes. Green Shoes is a gem. So, try out just: sudo gem install green_shoes

> Question 2: is it possible to somehow draw a top-level menu,
> a right-click menu in Shoes?

Shoes has not any menu functions. But, you can write by yourself. ;-)  
Look at [this sample](http://shoes-tutorial-note.heroku.com/html/00518_Combination_of_image_objects_show_hide_and_mouse_hover_leave.html). Not so cool, but an idea for pull down menu.

**Comment by karatedog** [comment]
Thanks!
