### ISSUE TITLE
windows 7 (64 bit) has errors

### ISSUE THREAD

**Issue by SyncDemon** [shoes/shoes-deprecated#97]
I run windows 7 (64bit) and I seem to have some difficulty compiling ruby shoes following the instructions at: https://github.com/shoes/shoes/wiki/Building-Shoes-on-Windows

I ran rake and while the script ran, the following happened:
"mktemp.exe has stopped working"
The command line is at "configure: creating ./config.status"
It has the close program button, so I closed it and the script continued executing.

Then "mktemp.exe has stopped working" again
Then command line had "configure: creating ./config.status" in the last line.
So I closed it again and the script continued executing.

It was eventually aborted and the error messages can be read at: http://pastie.org/1739789

I am not quite sure what the problem is. I was able to get it to work on a 32 bit version of windows 7 and even XP.

**Comment by steveklabnik** [comment]
Have you tried this since then, does this problem still persist?

I'm going to be re-doing the build system on Windows (see the [feature/1.9.2 branch](https://github.com/shoes/shoes/tree/feature/1.9.2) for my progress so far) soon, so it's possible this will become invalid after that.
